### ISSUE TITLE
No styling

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#1]
I'm not sure what I'm missing here, I have added this to my main.js

    import { UiAutocomplete } from 'keen-ui';

and registered the component. However if I use <ui-autocomplete> it will not style it, although the javascript seems to work.

**Comment by JosephusPaye** [comment]
If you are not using the standalone components, you have to include the `dist/keen-ui.css` file, which has all the styles.

**Comment by EmilMoe** [comment]
I think I am using the standalone component?

main.js:

~~~~
var Vue = require('vue');

import { UiAutocomplete } from 'keen-ui';

new Vue({
    el: '#app',
    components: {
        UiAutocomplete
    }
});
~~~~

**Comment by JosephusPaye** [comment]
No, the standalone components are built into the `lib` folder and can be used with:

```js
import UiAutocomplete from 'keen-ui/lib/UiAutocomplete';
```

The import you have above is actually being resolved from the `dist/keen-ui.js` file.

**Comment by EmilMoe** [comment]
Ah I see, I didn't get that point, thanks.

**Comment by HashemQolami** [comment]
@JosephusPaye I still do not get why importing the Vue files from the `./src` folder doesn't load the styles.

According to the `.vue` components files, all the stylus dependencies [seems to be imported](https://github.com/JosephusPaye/Keen-UI/blob/v0.8.9/src/UiAlert.vue#L82) properly. But it seems that the `<style>` content is ignored totally during the bundling. I am using webpack along with `vue-loader`.

Is it a `vue-loader` issue? or am I missing something?
