### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#10]
Right now I use the built in, but would be nice if all tooltips are replaced with something similar to this.

https://material.angularjs.org/latest/demo/tooltip

**Comment by JosephusPaye** [comment]
Tooltips just landed in 0.8.7: http://josephuspaye.github.io/keen-ui/#/ui-tooltip-docs

**Comment by EmilMoe** [comment]
Nice implementation and it works out of the box

However it seems that they are ignored on disabled items?

**Comment by JosephusPaye** [comment]
Yes, that's by design since disabled buttons do not trigger focus and hover events.
