### ISSUE TITLE
Should show property be required to be .sync? 

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#100]
I use Vuex. in Vuex I store state of some of my modals which can be shown in different situations. A lot of small components can "ask" some modal to appear. For example, imagine we have a user profile modal. This modal can be shown if I click user profile button or some other buttons. So looks like it's kind of application state variable.

As we know, in order to change Vuex storage we need to dispatch mutations through actions. However, in ui-modal component we have show property, which is required to be sync. By the way, when I used this property without .sync it didn't fire any errors or notifications. 

So, imagine we have "showFlag" variable in Vuex which is false by default. This variable is used in show property. When I click on some button, I call action like "showUserProfile" which dispatches mutation and sets showFlag = true. Then, when I hide the modal, it'll try to sync this flag directly. Instead I should use action.

Right now it works fine and I event didn't get any error:

```
<new-item-modal :show="modals['newItem']" @closed="hideModal('newItem')"></new-item-modal>
```

hideModal sets "modals['newItem']" to false.

Is it a good case for using vuex and how should we handle .sync in this case?

**Comment by JosephusPaye** [comment]
The reason `show` is sync is because you may want the parent to be updated when `show` changed from within the modal.

In your case for Vuex, you can use a computed property with a getter and setter to avoid directly mutating the store.

```js
computed: {
    showModal: {
        get() {
            return this.modals['newItem']; // from Vuex's store
        },

        set(show) {
            this.toggleModal('newItem', show); // toggleModal is an action that updates the store
        }
    }
}
```

**Comment by victor-ponamariov** [comment]
Is it possible to use object in computed property? Since I think it'd be not good to have many of the same computed properties for each modal.

In Vuex I store them like:

```
  modals: {
    newItem:        false,
    newOrder:       false,
    newPullRequest: false,
    newProject:     false,
    newBranch:      false,
    newUser:        false,
    newSupplier:    false,
    userProfile:    false
  }
```

When I tried to use computed property got an error that vue component tries to change store directly.

```
modalsVisibility: {
        get() {
          return this.modals
        },

        set(modals) {
          this.setModals(modals)
        }
      }
```

I realize this if because objects are passed by reference or something like this but I couldn't find an easy way to handle it. Vue just doesn't call set method for object computed property. Just don't want to copy-paste "showModal" for each modal

**Comment by EmilMoe** [comment]
@victor-ponamariov 

Yes you can do that with Vue, but you need to use `$set` in order to keep reactivity.

~~~~javascript
<template>
  <ui-modal
    :show.sync="modals.newItem">
  </ui-modal>
  <ui-modal
    :show.sync="modals.newOrder">
  </ui-modal>
</template>

....

data() {
  return {
    modals: {
      newItem: false,
      newOrder: false
    }
  }
}

methods: {
  showModal(modal) {
    this.modals.$set(modal, true);
  },
  hideModal(modal) {
    this.modals.$set(modal, false);
  },
  isVisible(modal) {
    return this.modals[modal] == true;
  }
}
~~~~

**Comment by victor-ponamariov** [comment]
What happens if "modals" is not component data but vuex data? :show.sync then changes vuex directly which is bad.

In case of modals I made N duplicated computed variables which are not arrays or objects so it works. But now, for example, I need to display customer list, each row has ui-checkbox and I need to track selected state.

So

```
<tr v-for="customer in customers">
        <td>
          <ui-checkbox :value.sync="customer.selected"></ui-checkbox>
        </td>
        <td>{{ customer.name }}</td>
        <td>{{ customer.email }}</td>
      </tr>
```

Customers stored in vuex. :value.sync changes customer list directly in vuex. Even if I have watcher:
```
watch: {
    'customers': {
        ...
    }
}
```

Sorry for asking questions here in issues, just couldn't get used to vue/vuex

**Comment by evanb2** [comment]
You just have to make a custom getter and setter:
```
modalShow: {
    get() {
      return this.$store.state.modalStore.show;
    },
    set(val) {
      this.$store.commit('SET_MODAL_SHOW', val);
    }
},
```

**Comment by JosephusPaye** [comment]
This is no longer a problem in v1.0, based on Vue 2.
