### ISSUE TITLE
Issue with UiIconButton and tooltip when showing UiModal

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#102]
I have a problem when I use UiIconButton with a tooltip to show an UiModal, when I close the modal the tooltip is stuck until I hover something with a tooltip. I think the issue must be related to bluring/unfocusing the tooltip container, since the UiModal adds an overlayer that doesn't work in this case?

**Comment by JosephusPaye** [comment]
This is the way it was designed. When you close the modal, focus is returned to the element that was focused before the modal was opened (in this case the UiIconButton). 

Just added a new `openTooltipOn` prop for UiIconButton and UiFab which will allow to set the tooltips to only open on hover.

**Comment by JosephusPaye** [comment]
What I describe above is now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9).
