### ISSUE TITLE
UiSelect and UiModal

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#103]
When I have a UiSelect inside my UiModal I have to add this `@closed=""` otherwise the select will close the modal when selected. Not a big deal but still what I would consider as a bug.

The bigger problem is that the UiSelect is only inside the modal, which means it can't drop down outside the modals borders. Some tweaking with z-index and or position is needed here.

**Comment by EmilMoe** [comment]
Removing these 2 on `.ui-modal-container` fix the problem in Google DevTools, but I'm not sure if it might break something else:

~~~~css
overflow-x: hidden;
overflow-y: auto;
~~~~

**Comment by JosephusPaye** [comment]
Yeah, that breaks the scrollbar for long modals. But I guess you could use it on a per-modal basis, like:

```css
.ui-modal-with-select .ui-modal-container {
    overflow-y: visible;
}
```

**Comment by EmilMoe** [comment]
There must be a solid way around this issue?

**Comment by EmilMoe** [comment]
What exactly is  long modals? Is it when they are set to full height or? If that's the case you can change behaviour of UiSelect wether or not the UiModal is "long" ?

**Comment by JosephusPaye** [comment]
Long modals (or scrolling modals) are modals which take up the full view-port height, therefore needing a scrollbar to view the rest of the modal content.

Like: 

![image](https://cloud.githubusercontent.com/assets/5924865/17453356/3ee181c0-5bbe-11e6-9baa-39538ac11711.png)

Your change disables the scollbar, which allows the UiSelect dropdown to overflow outside of the modal.

**Comment by EmilMoe** [comment]
In that case I think the UiSelect should change behaviour according to that.

**Comment by JosephusPaye** [comment]
Your workaround is good, as long as you don't use scrolling modals. I don't want to add it to the UiModal component since others might be using scrolling modals.

Closing for now.

**Comment by Christilut** [comment]
Wanted to report this but then I saw this issue, so here's the fiddle I made for it: https://jsfiddle.net/pm6o76tw/
