### ISSUE TITLE
UiModal event @disappeared

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#105]
Could we have an event on UiModal that's fired after the modal is disappeared from the screen? Or do you have a suggestion for making so?

I want to reset some fields when the modal is closed, but I don't want the user to see it which they do since @closed is fired at the same time the animation starts.

A work around would be to put it in a timer, but might be better to either wait with @closed till the animation ends or have @disappeared (something else) - I vote for the extra event.

**Comment by JosephusPaye** [comment]
I agree that the event should fire after the animation is complete. I think I'll just update `@closed` to do this. 

If you want to know when the modal starts closing, you can watch the `show` prop.

**Comment by JosephusPaye** [comment]
Actually went for new events, `revealed` and `hidden` because I don't want `opened` and `closed` to depend on CSS's [`transitionend`](https://developer.mozilla.org/en-US/docs/Web/Events/transitionend) event, which is not supported in IE9.

**Comment by JosephusPaye** [comment]
Landed in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9), check it out. https://josephuspaye.github.io/Keen-UI/#/ui-modal-docs
