### ISSUE TITLE
Two-way binding of UiTabs's activeTab

### ISSUE THREAD

**Issue by RenzHoly** [JosephusPaye/Keen-UI#106]

**Comment by rowanwins** [comment]
I've just pulled down the latest version of this repo and this seems to be occurring.

From what I understand in the UITabs component you want the activeTab property to always reflect which tab is active, and in the child UITab & UiTabHeader you want the active property to always reflect if the tab is active or not.

Can you please supply additional info?

**Comment by RenzHoly** [comment]
The tab can switch if I change activeTab property. But highlight of header and indicator looks bugly

**Comment by JosephusPaye** [comment]
`activeTab` is not really meant to be changed programmatically from outside the UiTabs component. Perhaps a `ui-tabs::select, 'tab-id'` event would be useful in this case.

**Comment by JosephusPaye** [comment]
A new `ui-tabs::select` event has been added in https://github.com/JosephusPaye/Keen-UI/commit/2a3b25d9fa7b2778531af3628d7b5347b7cdb32a, to be released with v0.8.9.

**Comment by RenzHoly** [comment]
Nice, thanks

**Comment by JosephusPaye** [comment]
[v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9) has been released with the `ui-tabs::select` event on [UiTabs](https://josephuspaye.github.io/Keen-UI/#/ui-tabs-docs).

**Comment by JosephusPaye** [comment]
In v1.0, there is a new `setActiveTab(tabId)` method on UiTabs.
