### ISSUE TITLE
Can't override the style of .ui-tabs-body

### ISSUE THREAD

**Issue by regrex** [JosephusPaye/Keen-UI#108]
I just don't need the border and padding set in .ui-tabs-body, so I want to override the default setting, but it doesn't work. What's wrong with this?

```
.ui-tabs { /* it's works */
  margin-bottom: 0;
}
.ui-tabs-body { /* doesn't work */
  border: 0;
  padding: 0;
}
```

**Comment by EmilMoe** [comment]
Sometimes I have had to use `! important`

**Comment by regrex** [comment]
@EmilMoe I try to put the override styles into global (not scoped) vue file, it's works. You can try it.

**Comment by EmilMoe** [comment]
Thanks. However I think if you change the behaviour in the Vueify file it shouldn't go global.

**Comment by JosephusPaye** [comment]
Closing for now, comment if you need help.
