### ISSUE TITLE
How do I pre-select UiSelect with multiple?

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#110]
How am I supposed to preselect? I have an array of titles and I have user.titles which is the titles the user has selected already (from database). I need to make those in user.titles selected in the UiSelect which is displaying titles.

**Comment by JosephusPaye** [comment]
The current implementation of UiSelect in v0.8.8 is a bit rough. The use case you are describing is possible  in the new version, just bear with me as it will be released soon.

**Comment by EmilMoe** [comment]
Thanks.. By soon I hope you mean this weekend, my own deadline is the 9th otherwise I will try to work around :-)

**Comment by JosephusPaye** [comment]
[v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9) has been released. 

The same suggestions [here](https://github.com/JosephusPaye/Keen-UI/issues/113#issuecomment-238871975) should help fix your issue.

**Comment by JosephusPaye** [comment]
In v1.0, you can simply update the `value` prop and the selected option will be updated accordingly. 

Remember to use an array for `value` if `multiple` is `true`.
