### ISSUE TITLE
UiSelect show the selected

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#113]
I hope that in the next update, that I only have to return the ID (value) of the selected item :-)

I have this computed which I believe is returning the object that matches, but it doesn't select anything. I have made it work before, but I don't know what's going wrong here.

~~~~javascript
            selected() {
                if (this.selectedId)
                    for (var i = 0; i < this.options.length; i++)
                        if (this.options[i].value == this.selectedId)
                            return this.options[i];
            }
~~~~

The UiSelect has this property

~~~~javascript
<ui-select
    :default="selected">
~~~~

**Comment by JosephusPaye** [comment]
Yeah, passing only the value string will be possible. However, to programmatically set the currently selected option, you will have to use the new `ui-select::set-selected` event.

**Comment by EmilMoe** [comment]
I don't understand how `:default` is supposed to work then?

I have `this.countries` for all options and `this.user.country` for the users country.

Each object has 3 keys: `id`, `value`, `text`.

How would you set the users country as the selected then?

**Comment by JosephusPaye** [comment]
`:default` only works for setting the pre-selected initially, e.g. when the component is first rendered.

But in the current version, there is a limitation that the same value passed to `default` must also be in the options array, which is probably why your usage isn't working.

**Comment by EmilMoe** [comment]
But if I use `:value` it will just set an outside object as the value? So it's basically impossible to preset anything? My example is a computed so it is returning an object from the `:options` array, but no effect.

**Comment by JosephusPaye** [comment]
[v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9) just landed, and you should be able to do this using:

```html
<ui-select :options="countries" :default="user.country" :value="user.selectedCountry"></ui-select>
```

The reason I have used `user.selectedCountry` is because the `value` prop is reset to null when the component is created, so you don't want to store your default value there.

**Comment by JosephusPaye** [comment]
In v1.0, you can simply update the `value` prop and the selected option will be updated accordingly. 

Remember to use an array for `value` if `multiple` is `true`.
