### ISSUE TITLE
How to use it globaly?

### ISSUE THREAD

**Issue by korneliuskristianr** [JosephusPaye/Keen-UI#117]
Hi master,
i've include this package files in my html layout, i tried put **&lt;ui-alert&gt;&lt;/ui-alert&gt;** BUT IT SHOW NOTHING IN THE BROWSER. It happend for another components too 

Please help :+1:

**Comment by vadimsg** [comment]
Check usage please.

**Comment by korneliuskristianr** [comment]
i've follow the instructions and i see the component using vuedevtools, the components is exist but show nothing. I've include files css too.

**Comment by korneliuskristianr** [comment]
Every time i used the component in my layout, my console have an error 
``` console
Uncaught TypeError: Cannot read property 'replace' of null
```

**Comment by JosephusPaye** [comment]
Could you create an online demo showing the issue? You can use this [Codepen template](http://codepen.io/pen?template=NrKmPQ), which already includes Vue and Keen UI latest.
