### ISSUE TITLE
UiMenu position bug with vueify

### ISSUE THREAD

**Issue by vadimsg** [JosephusPaye/Keen-UI#118]
I'm using vueify and there's a nasty bug with menu position. If menu is used inside .vue file component the top position of menu is incorrect.

https://github.com/vuejs/vueify

**Comment by JosephusPaye** [comment]
Could you provide more information or an online demo? You can use this [Codepen template](http://codepen.io/pen?template=NrKmPQ) which already includes the latest versions of Vue and Keen UI.

**Comment by vadimsg** [comment]
You can close this. Somehow issue resolved.
