### ISSUE TITLE
Use UiPopover for elements generated in loop

### ISSUE THREAD

**Issue by ADmad** [JosephusPaye/Keen-UI#119]
Checking the examples for UiPopover I see that it can be setup as below:

```html
<a v-el:trigger-b class="link-trigger">Hover here for the popover</a>
<ui-popover :trigger="$els.triggerB" open-on="hover">
</ui-popover>
```

Now my use case is I have multiple links generated in `v-for` loop and I want a separate popover for each. I can't figure how to specify the values of `v-el` and `:trigger` attributes. Can you please guide me to achieve what I want?

**Comment by JosephusPaye** [comment]
You could do this by creating a wrapper Link component which contains the link and the popover, then you can use `v-for` on this component.

**Comment by ADmad** [comment]
Checking the docs for UiButton I see it already supports associated popover which will also serve my needs. Thank you.
