### ISSUE TITLE
UiIconButton group

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#12]
Like you have in your examples, it would probably be needed (?) by others too to have a way to group icon buttons. I have added this to my styles, following a BEM structure.

    <div class="ui-icon-button__group">
      <ui-icon-button></ui-icon-button>
      <ui-icon-button></ui-icon-button>
    </div>

~~~~
.ui-icon-button {
    &__group {
        display: flex;
    }
}
~~~~

**Comment by JosephusPaye** [comment]
Yeah, this is something that I prefer to be done by the developer. The aim is to just develop the individual components, and leave it up to the developers on how to compose them together.

**Comment by EmilMoe** [comment]
I can see your point. An idea could be to add something in your docs describing how to implement it? So you avoid having it as a part of the component, but still help people how to archive it.

**Comment by jonagoldman** [comment]
Had the same issue. Had to compare my code with the css and html in the examples to see that a wrapping div with display flex is needed. Agree to mention this on the docs.

**Comment by JosephusPaye** [comment]
This has been added to the [UiButton](http://josephuspaye.github.io/Keen-UI/#/ui-button-docs) docs in [v0.8.8](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.8)
