### ISSUE TITLE
Input border radius in iOS Safari

### ISSUE THREAD

**Issue by danmindru** [JosephusPaye/Keen-UI#120]
Hi there, 
Looks like you forgot to set `border-radius: 0` for input & textarea. 
Let me know if I should make a PR.

![screenshot 2016-08-11 12 34 55](https://cloud.githubusercontent.com/assets/1515742/17586135/1cb17dfc-5fc0-11e6-83a3-730523c92d47.png)
![screenshot 2016-08-11 12 35 22](https://cloud.githubusercontent.com/assets/1515742/17586136/1cb361bc-5fc0-11e6-8a2c-e3092abcbc1b.png)

**Comment by JosephusPaye** [comment]
Thanks for the report. This will be fixed in the next version.

**Comment by danmindru** [comment]
Awesome! Thanks for the great work.

**Comment by JosephusPaye** [comment]
Fixed in v1.0.
