### ISSUE TITLE
Vue v2 Support?

### ISSUE THREAD

**Issue by dts** [JosephusPaye/Keen-UI#121]
Sorry if this is somewhere else, but I was wondering if there is a timeline for v2 support?  Does it already support V2, because the API changes are minimal?

**Comment by citycide** [comment]
See #95 - it's planned and I'm sure @JosephusPaye is looking into what's needed. As for what's actually needed... probably the events and data binding systems, since `.sync`, `$dispatch` and `$broadcast` are deprecated.

> Yes, there are plans for upgrading to Vue 2. But that will be after a stable 2.0 is released. There will be one more version of Keen UI on Vue 1.x: v0.8.9, which is mostly done and will be published soon.

**Comment by dts** [comment]
Whoopsie, I guess I forgot to check for closed issues!  Thanks for the response.  I'll keep it on my radar and might be able to work on it if I get spare cycles.
