### ISSUE TITLE
Porting to Vue 2 (Help?)

### ISSUE THREAD

**Issue by dts** [JosephusPaye/Keen-UI#122]
I'm trying to upgrade Keen-UI to support vue 2 (whose RC1 came out a few days ago).  I got everything running in a simple test harness (https://github.com/thehumaneffort/keen-ui/tree/next), and fixed a few trivial errors, but doing so did not cause anything to really work.  I'm unfamiliar with Vue (and Vue 2), so it's probably due to some lack of understanding.  I'd love to help out and get everything moved over, but I'm going to need a bit of help understanding things.  Does anybody have time to hold my hand through the first stages?

**Comment by dts** [comment]
I'm using the "docs" as a test harness, but I haven't found a way to dynamically serve it (hot loading-style), how do y'all go about wrenching on Keen-UI?

**Comment by rowanwins** [comment]
Gday @dts 

Check out [this issue](https://github.com/JosephusPaye/Keen-UI/issues/81#issuecomment-230960994) for a description on how to get a dev environment going for Keen Ui. 

Some components will probably transfer across to Vue 2 very simply while I suspect others will take a bit more work (eg those with parent-child communication). 

There is also now some draft [Vue 2.0 doco](http://rc.vuejs.org/guide/) so that should help. 

If you get stuck on anything yell out and I'll see if I can assist
Cheers

**Comment by LucasIcarus** [comment]
@rowanwins 
I'm working on the migration...

Here are 2 problems for now... I'm using ssr as test base, and 
```js
props: {
  trigger: {
    type: Element
  }
}
```
there is no Element Object in node... Can I change the type to `null`?

Here is the 2nd.. In the vue file which use ShowDropdown.js
```html
<template>
  <a v-el:foo></a>
  <menu :trigger="$els.foo"></menu>
</template>
```
with vue 2.0

```html
<template>
  <a ref="foo"></a>
  <menu :trigger="$refs.foo"></menu>
</template>
```

This would not work as that after $els has been merged with $refs and $refs isn't reactive... so the child-component will recieve undefined as prop trigger...

With drop.js use in the mixin, how can I pass the quote of sibling component to the another sibling component? with the query string and use `document.queryselector` in mounted? Any advice?

**Comment by JosephusPaye** [comment]
Hi @LucasIcarus,

This is something I noticed while looking at the changes in Vue 2. Passing a selector string to query will probably work, but then we will need to find a way to to make the triggers elements unique (perhaps by adding a UUID).

**Comment by LucasIcarus** [comment]
@JosephusPaye What now I use is to pass a string and use `$parent.$refs[string]`... and in v-for template, it becomes `$parent.$refs[string][0]`, in this situation, the string in `ref="string"` must be unique and a type check needed. Besides, it seems that $parent is not recommendly used? 

Coupling is another issue which need a discussion.. As a reuseable components, Maybe package with $parent and strong coupling between the components inside is acceptable ?

Good day~ Now is midnight in China and need some bed...

**Comment by LucasIcarus** [comment]
@JosephusPaye , @rowanwins ..
Kind of finish in pr https://github.com/JosephusPaye/Keen-UI/pull/148

Sorry fot the pr is hard to review on github Pages...

**Comment by beeplin** [comment]
hey guys, so how is it going porting to vue2? vue 2.0 has been released officially for several days.~

**Comment by juppdes** [comment]
any scheduled date? 
I love to use this in vue 2.

**Comment by ahopkins** [comment]
@juppdes There is a branch (https://github.com/JosephusPaye/Keen-UI/tree/next) that should be compatible with Vue 2. I'm looking forward to this too :+1:

**Comment by juppdes** [comment]
any news?

**Comment by moxx** [comment]
+1

**Comment by edbizarro** [comment]
+1

**Comment by roslaneshellanoo** [comment]
+1

**Comment by blomdahldaniel** [comment]
+1

**Comment by throrin19** [comment]
+1

**Comment by bosenok** [comment]
+1

**Comment by ViktorKonsta** [comment]
+1
