### ISSUE TITLE
Validation errors via event do not show without help-text prop

### ISSUE THREAD

**Issue by shabushabu** [JosephusPaye/Keen-UI#124]
When you set validation errors via `ui-input::set-validity` and the element does not have a `help-text` prop attached then none of validation errors will show up.

**Comment by shabushabu** [comment]
This happens on both `ui-textbox`and `ui-select`, btw.

**Comment by shabushabu** [comment]
Looking at the source code, I just realized that it can only happen if there are no validation rules set on the elements neither. Basically, I need validation rules that interact with other fields, so I removed the rules completely from any elements and do validation manually just before submitting the form.

**Comment by JosephusPaye** [comment]
Yeah, this is working as designed. The feedback div is hidden if no help text or validation rules are set.

**Comment by shabushabu** [comment]
Ok, but that means that the `ui-input::set-validity` event isn't really usable on those elements at the moment unless you're doing something like `help-text="&nbsp;"`. Is this something you're willing to change?

**Comment by JosephusPaye** [comment]
I think it's reasonable to have a prop to show the feedback div even if no help text or validation rules are set. I will see if it can be added in the next version.

**Comment by shabushabu** [comment]
Great, thanks!

**Comment by JosephusPaye** [comment]
This is fixed in v1.0. If the new `invalid` prop is `true` and the `error` prop is provided, the error message will be shown, independent of the help text.
