### ISSUE TITLE
ui-textbox - issue with using Regex

### ISSUE THREAD

**Issue by mariaczi** [JosephusPaye/Keen-UI#126]
Hi,

I can't get it working.
I need `ui-textbox` working as time field with HH:mm format, so for 24hr.
I found this: http://stackoverflow.com/questions/7536755/regular-expression-for-matching-hhmm-time-format and took regex from there: `^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$`.
Without any `\` it's throwing an error and does not work. When I will add `\` before every character:
`<ui-textbox name="time" validation-rules="regex:/^\(\[0-9\]\|0\[0-9\]\|1\[0-9\]\|2\[0-3\]):\[0-5\]\[0-9\]$/" label="Time" ></ui-textbox>` It's always throwing incorrect format.

Did anyone manage to get it working with regex validation?

**Comment by JosephusPaye** [comment]
If you want to use regex validation, you have to use an array of rules (and not a string). See here for a working example of your rules above: 

http://codepen.io/JosephusPaye/pen/yJwGNy

**Comment by mariaczi** [comment]
Great. Appreciate. It's working now.
Thanks for really nice package.
