### ISSUE TITLE
UiTextbox underline focus color

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#13]
When it's a multiline the underline changes color once in focus, but the single line textbox doesn't.

**Comment by JosephusPaye** [comment]
It seems to be working well for me and in the docs. Can you make a CodePen or JSFiddle demonstrating the issue?

**Comment by EmilMoe** [comment]
Sorry yes, it was my own CSS that screwed it. :-)

**Comment by ElementLi** [comment]
@EmilMoe Do you know how to change the border-bottom-color and the icon color for input focused?

**Comment by EmilMoe** [comment]
Try this:

~~~~css
.ui-autocomplete-input {
    border-bottom-color: red;
~~~~

But you need to replicate the exact CSS path, so you might have to add `.ui-autocomplete` around or something.
