### ISSUE TITLE
Validation messages

### ISSUE THREAD

**Issue by vadimsg** [JosephusPaye/Keen-UI#132]
Is it possible to display validation error message with ui-input::set-validity without setting validation-rules on text component? Currently I'm validating input field with API and need to display errors that I get with response. At the moment I can do that only by setting validation-rules, if validation-rules is not set I can get only red border without my custom message.

**Comment by JosephusPaye** [comment]
See #124.

**Comment by JosephusPaye** [comment]
Now possible in v1.0, simply set the `invalid` prop to `true` and set `error` with your error message and it will be shown.

The `validationRules` prop has been removed as validation now happens outside the components.
