### ISSUE TITLE
UiCollapsible display issue on Firefox Mac OS Snow Leopard

### ISSUE THREAD

**Issue by JosephusPaye** [JosephusPaye/Keen-UI#133]
![screen shot 2016-08-23 at 12 37 01](https://cloud.githubusercontent.com/assets/5924865/17878558/fb82c816-692e-11e6-9dbc-c32da01c79ab.png)

Also, tabbing does not work for UiMenu.

Arrow keys don't change selection in UiRadioGroup.

**Comment by Narsul** [comment]
the same happens not only in Snow Leopard, but in other versions of macOS too

**Comment by fajaryanw** [comment]
same issue in Ubuntu 16.04 LTS too

**Comment by JosephusPaye** [comment]
@Narsul, @fajaryanw,

[v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) has been released with fixes. Could you check if it fixes this issue?

**Comment by EmilMoe** [comment]
Snow Leopard:

![image](https://user-images.githubusercontent.com/555083/38704274-1106f114-3ea6-11e8-8a08-5c82de1c8b41.png)

**Comment by JosephusPaye** [comment]
Thanks @EmilMoe!

**Comment by JosephusPaye** [comment]
Closing as this seems fixed. Create a new issue if this is still happening.
