### ISSUE TITLE
Clean select value

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#136]
Is it possible to clean select value? I mean when user types backspace or something like that?

**Comment by JosephusPaye** [comment]
Currently this is not possible, but you may be able to achieve something similar to by setting a listener for backspace keydown and then triggering the reset event.

**Comment by JosephusPaye** [comment]
Best way to do this (in v1.0) is to listen for `keydown.backspace.prevent` and call `reset()` on the UiSelect component.
