### ISSUE TITLE
UiMenu dropdown position issue

### ISSUE THREAD

**Issue by seemsindie** [JosephusPaye/Keen-UI#137]
Hello guys,

First i want to say thanks to this great framework, i really enjoy it more than any other material framework.
But i have an issue with dropdown, i can't get it positioned right. I tried every option from your docs, and i have no additional styles so i don't really dont know where the issue is.

I have a toolbar at the top, and there is a menu on the far right and it should open bottom left, but it's always opening at the top, no matter what.

Here are the screenshots:

top left
![image](https://cloud.githubusercontent.com/assets/1268576/17999462/a925adc0-6b79-11e6-9b7b-f811c3c96000.png)

left top
![image](https://cloud.githubusercontent.com/assets/1268576/17999479/bc763cb4-6b79-11e6-9969-5d1fa419e88b.png)

left middle
![image](https://cloud.githubusercontent.com/assets/1268576/17999497/d4c43dfc-6b79-11e6-9ca6-265e273d0a92.png)

left bottom
![image](https://cloud.githubusercontent.com/assets/1268576/17999524/eb086228-6b79-11e6-93f1-6ab35fccac8f.png)

bottom left
![image](https://cloud.githubusercontent.com/assets/1268576/17999545/fd1a1f9c-6b79-11e6-8b11-47a7d3d2b285.png)

bottom center
![image](https://cloud.githubusercontent.com/assets/1268576/17999564/0abae320-6b7a-11e6-98e5-73babbe4b7dc.png)

bottom right
![image](https://cloud.githubusercontent.com/assets/1268576/17999580/1bb5b902-6b7a-11e6-928e-03bc5ca36df3.png)

right bottom
![image](https://cloud.githubusercontent.com/assets/1268576/17999595/2c28b33e-6b7a-11e6-802a-36293c794cdb.png)

right middle
![image](https://cloud.githubusercontent.com/assets/1268576/17999612/39ab84dc-6b7a-11e6-827f-bcf54702cd80.png)

right top
![image](https://cloud.githubusercontent.com/assets/1268576/17999621/451503a2-6b7a-11e6-90f0-bd977325c90b.png)

top right
![image](https://cloud.githubusercontent.com/assets/1268576/17999634/51bb4f94-6b7a-11e6-963d-92c0cc74c8f8.png)

top center
![image](https://cloud.githubusercontent.com/assets/1268576/17999645/5e048aae-6b7a-11e6-85c0-dcaa4b0c15bc.png)

Any idea how i can have my menu as i want? :)

Thanks

**Comment by JosephusPaye** [comment]
Hi @seemsindie,

What's on the rest of your page? Sometimes if there is no content, the body isn't  tall enough to show the full menu.

If that's the case, it should be fixed if you add:

```css
body {
    min-height: 300px; /* or any value you need */
}
```

**Comment by seemsindie** [comment]
@JosephusPaye Yes that was an issue, thanks man.
