### ISSUE TITLE
UiSelect depends on Material icons

### ISSUE THREAD

**Issue by sunabozu** [JosephusPaye/Keen-UI#138]
Hi.

I've noticed that the UISelect component doesn't render properly without including the Material icons (see the screenshot). And I think it's an overhead for a basic scenario. I don't use those icons anywhere but for rendering that tiny triangle in UISelect. So it would be nice if it could render the arrow in some other way.

![screen shot 2016-08-28 at 20 19 43](https://cloud.githubusercontent.com/assets/135717/18035337/f4694e42-6d5c-11e6-85c2-bea3700d28c8.png)

**Comment by JosephusPaye** [comment]
Yeah, I agree that you should't have to pull in the Material Icons if you're using a single component. I'll see what can be done about this in v1.0.

**Comment by JosephusPaye** [comment]
Fixed in v1.0, all internal component icons including UiSelect are now inlined SVG.

**Comment by Raiondesu** [comment]
Toolbar still has it.
