### ISSUE TITLE
Font Problem

### ISSUE THREAD

**Issue by ahmedkassem** [JosephusPaye/Keen-UI#139]
I am using Keen-ui with quasar framework which already has Roboto font included
Keen-ui elements are shown with a strange effect like in the attached image

![keen](https://cloud.githubusercontent.com/assets/7607004/18035882/d22fdeca-6d5e-11e6-8a19-d1445bab8efa.jpg)

**Comment by JosephusPaye** [comment]
This is from the CSS that Quasar adds to buttons (a black text-shadow).

See here: https://github.com/rstoenescu/quasar-framework/blob/dev/src/css-components/button/button.mat.styl#L58
