### ISSUE TITLE
UiTextbox height changes when disabled

### ISSUE THREAD

**Issue by jonagoldman** [JosephusPaye/Keen-UI#14]
The ``div`` with a class of ``ui-textbox-feedback`` is removed for disabled elements, but it has ``min-height:20px`` so it pushes everything 20px each time the disabled state changes. Maybe it needs to stay there but change the visibility?

**Comment by JosephusPaye** [comment]
This will be fixed in the next release, thanks.

**Comment by JosephusPaye** [comment]
This has been fixed in [v0.8.8](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.8). Now the feedback is kept in place even when disabled.
