### ISSUE TITLE
Improvement in UiSelect Multiple

### ISSUE THREAD

**Issue by stefanosandes** [JosephusPaye/Keen-UI#140]
Hi

In a select with many selected items , the normal behavior is to group the selected items up. I think it would be interesting to have an option to hide the items that exceed the width of the component, allowing a more consistent design in some cases.

Thanks!

**Comment by vizo** [comment]
You can easily do that with css ...

.ui-select-value {
    overflow: hidden;
    white-space: nowrap;
    width: 1px;
    text-overflow: ellipsis;
}

**Comment by stefanosandes** [comment]
Hi @vizo, thanks! I had solved with css, but I belive it's intersting to be part of configuration.

thanks.

**Comment by JosephusPaye** [comment]
This is fixed in v1.0. Now the selected items simply overflow unto the next line correctly.
