### ISSUE TITLE
Pre Select UiSelect

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#141]
Sorry for all the inquiries but I just don't understand how this is supposed to be used.

I have 2 UiSelects one is multi the other is not. I want both to be preselected, but the objects that I pass in as selected are not equal to those in the list (they are for good reasons loaded from 2 different places in the app and therefor have different attributes, but text and value are consistent).

~~~~javascript
                <ui-select
                        name="roles"
                        v-ref:roles
                        label="Roles"
                        :options="roles"
                        :keys="{text: 'en', value: 'id'}"
                        @closed=""
                        validation-rules="required"
                        multiple>
                </ui-select>

                <ui-select
                        name="title"
                        v-ref:title
                        label="Title"
                        :options="titles"
                        :keys="{text: 'en', value: 'id'}"
                        @closed=""
                        validation-rules="required">
                </ui-select>
~~~~

Right now I pass it as value, as this is the only way I could make it work a little, but not satisfying (the $refs part is due to be changed):

~~~~javascript
                    this.$refs.title.value     = this.user.title;
                    this.$refs.roles.value     = this.user.roles;
~~~~

I would like that the UiSelect checks for `key.value` (here `id`) for a match and preselect that and preselects all intersect `value` (or `id`) between `this.$refs.roles` and `this.user.roles`

**Comment by JosephusPaye** [comment]
Could you post a sample of your `roles` array?

**Comment by EmilMoe** [comment]
Of course. The value and text part are leftovers I haven't had time to refector out, but I mainly use your new @keys

~~~~
[
{
id: 2,
en: "VIP",
da: "VIP",
value: "2",
text: "VIP"
},
~~~~

**Comment by JosephusPaye** [comment]
See if this example fits your use case: http://codepen.io/JosephusPaye/pen/VKYQOW?editors=1000

**Comment by EmilMoe** [comment]
Yes, thanks, that works if I have an array with the ID's, but if I change so that it's through computed, then it doesn't work anymore.

http://codepen.io/emilmoe/pen/QKwmvZ?editors=1010

I took out your computed at it seems not to do anything?

**Comment by JosephusPaye** [comment]
Yeah, the computed is the same as just passing the `user.roles` array.

The reason yours doesn't work is because you have a syntax error on line 6:

Should be `computed: {` instead of `computed() {`

**Comment by EmilMoe** [comment]
My missing point was this:

~~~~javascript
this.$broadcast('ui-select::set-selected', this.tag.courses, 'courses');
~~~~

because it's loaded externally
