### ISSUE TITLE
Global configurations

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#142]
For the next version global configurations would be very nice. For example to override `:keys` by default:

``` javascript
Vue.keenui.options.keys = {value: 'id', text: 'label', image: 'image'};
```

**Comment by JosephusPaye** [comment]
Makes sense. Will see how it can be added in v1.0.

**Comment by JosephusPaye** [comment]
[Global config](https://github.com/JosephusPaye/Keen-UI/blob/next/Customization.md#global-config) has been added to v1.0, to be released tomorrow.

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).
