### ISSUE TITLE
UiSelect @selected event parameter for 'multiple' does not tell whether item is selected or deselected

### ISSUE THREAD

**Issue by tianhai82** [JosephusPaye/Keen-UI#145]
`<ui-select name="countries" label="Countries" @selected="selectedCountry" show-search multiple placeholder="Select some countries" :options="countries"></ui-select>`

```
methods:{
    selectedCountry: function(item){
        // event dispatch every time an item is selected or deselected.
        // there is no way to differentiate whether it is a select or deselect event
    }
}
```

**Comment by JosephusPaye** [comment]
Hey @tianhai82,

Thanks for the report. This will be added in v1.0 as a second argument to the `@selected` event handler.

**Comment by JosephusPaye** [comment]
Added in v1.0, the `@select` handler will now receive an object as the second argument:

```js
handler(item, meta) {
   console.log(meta.selected); // true if item was selected, false if item was deselected
}
```
