### ISSUE TITLE
UIButton with separated menu

### ISSUE THREAD

**Issue by jonagoldman** [JosephusPaye/Keen-UI#147]
In some situations, makes sense to have a button with a separated menu, where you can either click the default action or click the arrow icon to open the menu for more actions.
I used two different buttons, one regular and one that only opens the menu, but it doesn't look too good and some custom css is needed.

Do you thing a thing like that can be included in the library?

**Comment by JosephusPaye** [comment]
Hi @jonagoldman,

No immediate plans for that. You could achieve the effect though using two UiButtons and some custom CSS: http://codepen.io/JosephusPaye/pen/JRRPKy?editors=1000

**Comment by jonagoldman** [comment]
Thanks.
