### ISSUE TITLE
UiRippleInk Missing Trigger when more than 4 Elements in Chrome 52

### ISSUE THREAD

**Issue by enesemini** [JosephusPaye/Keen-UI#149]
I have a list of items, which I added the UiRippleInk to. However, as soon as there are more than 4 elements I get the following error in Chrome 52 but NOT in Firefox (others not tested):

<img width="972" alt="bildschirmfoto 2016-09-16 um 17 09 12" src="https://cloud.githubusercontent.com/assets/7120660/18590758/52917576-7c30-11e6-953d-692dad33d450.png">

This issue has already occurred twice, in two separate lists.

I'm sure I'm following the documentation.

Is this a known issue, and what could be causing this?

It's really a bummer, since the UiRippleInk is so awesome and I want to use it!
Thanks for this awesome Repo!

Greetings

**Comment by LucasIcarus** [comment]
do u have vue devtool in chrome? follow the warning find the prop `trigger` 

or u can customize the rippleInk component structure... 

https://github.com/LucasIcarus/Keen-UI/blob/next/src/UiRippleInk.vue

merge the ripple logic and transition style into vue itself... notice that the link above is based on vue2.0 and the usage of transition need some adjustment.

**Comment by enesemini** [comment]
I forgot to mention, that only one out of five (for example) UiRippleInk doesn't work.

Indeed, with the devtool I see, that there are five UiRippleInk Components, but one of them is missing the trigger, which is strange, as every iteration of these five is exactly the same as the others.

I don't think customizing the rippleink structure is necessary here. 

> merge the ripple logic and transition style into vue itself

I don't quite understand, why or even how I should do that. Could you explain what you mean't, if you don't mind?

**Comment by enesemini** [comment]
Also, as already mentioned in the first post, the UiRippleInk Component works as expected in Firefox, but not in Chrome.

I would think of that as a bug.

**Comment by LucasIcarus** [comment]
@enesemini missing one of five seems bug of vue or browser to me... 

The customize component will erase the required prop `trigger`, so I think it's kind of solution here.

**Comment by enesemini** [comment]
Ok, I wrapped the UiRippleInk thingies within a custom component myself, and now everything seems fine now…

Still, I think this behavior is not expected and this is a bug, but I will close this issue now, as I found a workaround.

**Comment by JosephusPaye** [comment]
@enesemini, Sometimes the problem is when the `trigger` passed to UiRippleInk isn't available (is `null` or `undefined`) when the component is instantiated. 

This can happen with dynamic directives like `v-if` and `v-for` etc. This might have been the case here, and the best way around that is creating a custom component.

**Comment by enesemini** [comment]
@JosephusPaye Ok, thank you for letting me know.

Creating a custom component is reasonable anyway. I was just creating some markup, and I saw the issue… Later I refactored and created components and everything was fine!

Thanks!
