### ISSUE TITLE
UiTabs active-tab-indicator not resizing, on window resize

### ISSUE THREAD

**Issue by enesemini** [JosephusPaye/Keen-UI#150]
The active indicator of the UiTabs does not resize, when the window, or the container resizes.

I use the UiTabs with four tabs, and the `fullwidth` attribute.

This is what it looks like, after resize:

When the window becomes smaller:
<img width="905" alt="bildschirmfoto 2016-09-16 um 17 18 35" src="https://cloud.githubusercontent.com/assets/7120660/18591135/b00a7cf6-7c31-11e6-8f1b-6c414ba9affc.png">
When the window becomes larger:
<img width="858" alt="bildschirmfoto 2016-09-16 um 17 18 56" src="https://cloud.githubusercontent.com/assets/7120660/18591139/b4ae530e-7c31-11e6-8fb4-297fc9da30fb.png">

When I click on another tab, after resizing, then the indicator has the correct size again.

This does occur on Chrome 52, as well as on Firefox 48 (others not tested).

Thanks and have a nice day.

**Comment by JosephusPaye** [comment]
Yeah, this is a known bug, and will be fixed in v1.0. Thanks for the report, though.

**Comment by JosephusPaye** [comment]
Fixed in v1.0. There is also a new `refreshIndicator()` method you can call to refresh the active tab indicator.
