### ISSUE TITLE
UiSwitch, cursor: pointer

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#151]
I think the UiSwitch should have hover cursor as pointer to help the user know that it's clickable.

**Comment by JosephusPaye** [comment]
Good idea. 

The reason I didn't do that is because for the default browser components (like `<input type="radio">` and `<input type="checkbox">`, you don't get a pointer cursor on the button, only on the label text (at least in Chrome).

**Comment by JosephusPaye** [comment]
All input components in v1.0 now show a pointer cursor.
