### ISSUE TITLE
Issues setting UiSelect width

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#155]
I am have a bit issues from within a component to set the width of an UiSelect. I want it to be only 50-100px instead of a minimum of 250px

**Comment by JosephusPaye** [comment]
Hi @EmilMoe,

UiSelect doesn't have a `min-width` and should be responsive to use whatever space is available in the parent. Here's an example on a very narrow screen (width less than 210px):

<img src="https://cloud.githubusercontent.com/assets/5924865/19409591/d503d1b2-9322-11e6-8027-ad2bde9a5d90.png" width="210px">

Only the dropdown has a `min-width` of 120px, and you can change that with CSS:

```css
.ui-select-dropdown {
     min-width: 120px;
}
```

**Comment by EmilMoe** [comment]
I must have messed up something. My bad. We have been under pressure with a deadline lately, sorry for dumb questions :-)
