### ISSUE TITLE
UiCheckbox breaking changes

### ISSUE THREAD

**Issue by lesion** [JosephusPaye/Keen-UI#156]
Hi,
I don't see the reason for this change on UiCheckbox: aa13404a95840828234099a6dd09aa998f551fcb

I was using UiCheckbox with a multi-dimensional array like this:

```js
   ui-checkbox(:model.sync="value[col][row]")
```
how this is supposed to work now ? 
I've ended up with this hack but don't know if it's the right way to do this (hope not!)

```js
      ui-checkbox(:model.sync="value[col][row]", :value="value[col][row]")
```

ps. could you consider to use [semver](http://semver.org/) for your next release version (I mean `increment MAJOR version when you make incompatible API changes`)?  

good job !

**Comment by citycide** [comment]
I'm only going to chime in with a semver note since I haven't actually used `ui-checkbox` yet. Technically while <1.0, breaking changes can happen in almost any release since <1.0 is inherently under heavy development.

[Reference link @ semver.org](http://semver.org/#spec-item-4)

**Comment by JosephusPaye** [comment]
Yeah, pretty much what @citycide said. The API so far has been unstable as I try to find the right balance between simplicity, performance and flexibility.

v1.0 (coming up soon-ish) will be fully compatible with SemVer.

The reason for the UiCheckbox change was to more closely match the behaviour of the native checkbox input and the way `v-model` works with checkboxes. See https://github.com/JosephusPaye/Keen-UI/issues/59 and https://github.com/JosephusPaye/Keen-UI/issues/30.

Also, `model` should be a drop in replacement for `value`, I don't know why it's not working for you. Could you post a Codepen demonstrating the issue? 

Here's a template with Keen UI and Vue already included: http://codepen.io/pen?template=NrKmPQ

**Comment by lesion** [comment]
This was a strange bug with [fastclick](https://github.com/ftlabs/fastclick/issues/60) (using keen-ui  on ios/cordova).
I thought it was something related to this change but I was really wrong !

Sorry :pray:
