### ISSUE TITLE
UiButton with menu fails on mobile&/emulated touch events

### ISSUE THREAD

**Issue by Rob-pw** [JosephusPaye/Keen-UI#162]
#161 

Bug; UiButton 'With Menu':
Enable mobile emulation and touch events in Firefox or Chrome.

In Chrome, throws error but does not open:
docs.bundle.js:formatted:5929 Uncaught TypeError: Cannot read property 'querySelector' of undefined
On formatted line: if (r["default"].has(o, "ui-ripple-ink") || (o = o.querySelector(".ui-ripple-ink"))) {

In Firefox, menu opens, after a delay ripple activates, menu closes prematurely.

**Comment by JosephusPaye** [comment]
See #146.
