### ISSUE TITLE
Passing dynamic data to a modal

### ISSUE THREAD

**Issue by Spiritized** [JosephusPaye/Keen-UI#164]
Firstly, i I'd like to thank author of this UI kit, it's looks amazing, really beautiful and smooth!

But i didn't understood, how can i pass some custom props to my modals. 
My situation is:
I have a bunch of modal opening buttons
`<button  @click ="show.modal1 = true" id="{{ timeslot._id }}">
       Check appointment on: {{ timeslot.begin_time }}
    </button>
`
I want to open the same modal, by clicking on any of them , but with different data inside **body** slot.
So, by clicking on these buttons, i want to fetch data from model or DB(depending on _timeslot._id_) and push it to a modal template.
Basically, i want to pass object like :
`{name: 'Patient Name', phone:'+77898746'}`

I've tried to change a source of _UI-Modal_ a bit, to pass a string at least. So i've added my custom prop to _UI-Modal_ props.
`props: {....,
  backdropDismissible: {
                        type: Boolean,
                        default: true
                    },
                    patientName: {
                        type: String,
                        default:"Patient Name"
                    }
                }`
After this i pass hardcoded prop as:
`<ui-modal :show.sync="show.modal1" header="Appointment details" patient="new patient name">
        <div slot="default"> {{ patient }} </div>
    </ui-modal>`
this snippet didn't render nothing, but i see my prop in devtools

![screenshot from 2016-10-08 01 09 44](https://cloud.githubusercontent.com/assets/11809022/19206773/f551ae24-8cf3-11e6-80c7-fe99b2915931.png)

I want to have something like:

`<button  @click ="openModalWithRelevantPatient" id="{{ timeslot._id }}">
       Check appointment on: {{ timeslot.begin_time }}
    </button>
`
with _openModalWithRelevantPatient_ method in my parent component, which gets data from a timeslot(i keep array of them in a model) and pass it to an opening modal

Hope i've described my issue clearly.

**Comment by evanb2** [comment]
You can pass whatever you want to the body of the modal:
`<ui-modal>`
`<div>{{ patient }}</div>`
`</ui-modal>`

**Comment by JosephusPaye** [comment]
Closing as @evanb2's solution is the right fix.
