### ISSUE TITLE
Readonly Attribute for Textbox

### ISSUE THREAD

**Issue by CarlEdmondson** [JosephusPaye/Keen-UI#167]
It would be useful if the textbox component had a readonly prop that would bind to the input's native readonly attribute.

The motivation for this for me is that I'm using flatpickr combined with textbox to create a datepicker component. The desired implementation would be to have the textbox as readonly. The user can click on the textbox and select a date from the flatpickr datepicker, which would update the textbox value.

**Comment by JosephusPaye** [comment]
Good idea @CarlEdmondson, this will be added in v1.0.

**Comment by JosephusPaye** [comment]
Added in v1.0.

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).
