### ISSUE TITLE
Form does not send the value of the select.

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#168]
Hello there. The UiSelect doesn't works in my case, please take a look.

```
<form action="" method="post">
    {% csrf_token %}
    <ui-select show-search id="id_image" name="image" :options="selectData" placeholder="Select a image"></ui-select>
    <input type="submit" name="apply" value="Apply this image">
</form>
```

I checked the value via vue-dev-tools everything is correct. 

Default select works fine. 

So I submit form but it doesn't work. What am I doing wrong?

**Comment by JosephusPaye** [comment]
Hey @lavezzi1,

UiSelect does not render a native form `<select>`, so it's data is not part of form data submitted. To submit the data from UiSelect you need to intercept the `<form>` submission and use AJAX to send the values.

**Comment by lavezzi1** [comment]
@JosephusPaye Okay thanks. Can you recommend component that has search and works like select and will works in form without AJAX please.

**Comment by JosephusPaye** [comment]
In v1.0, UiSelect now has a hidden input element with the select value which will be submitted. Note that this hidden input is only added when the `name` prop is set.
