### ISSUE TITLE
How to disable button until INPUTs is not valid?

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#169]
Hey @JosephusPaye I have a form with inputs and button(submit). I want to disable the submit button if one or all inputs are invalid. And remove disabled attr when everything is valid. How to do that? Thanks!

**Comment by Narsul** [comment]
I think you should create computed boolean value (e.g. `isValid`):
``` js
{
    ...
    computed : {
        isValid () {
            return ... /* your validation code here */
        }
    }
    ...
}
```
 and then bind it to button:
``` html
<ui-button :disabled="!isValid">Submit</ui-button>
```
