### ISSUE TITLE
ReCaptcha inside modal not working on IE9-11

### ISSUE THREAD

**Issue by nivv** [JosephusPaye/Keen-UI#170]
Hi!

It seems that the modal component suffers from the same bug in IE9-11, which is that the recaptcha component from google isn't working.

It seems to be a focus issue which affects Bootstrap modals as well.

http://stackoverflow.com/questions/27886618/problems-with-new-google-recaptcha-in-ie-when-inside-modal-or-dialog

I'm sure this is a bug of IE itself and not Keen Ui, but I just wanted to see if there is a workaround. Seems to be this `restrictFocus()`-function.

https://github.com/JosephusPaye/Keen-UI/blob/master/src/UiModal.vue#L163

**Comment by JosephusPaye** [comment]
@nivv, Any idea on how to fix this is welcome. Closing this issue for now.
