### ISSUE TITLE
v-if/v-show doesn't work for UiTabs

### ISSUE THREAD

**Issue by karlpatrickespiritu** [JosephusPaye/Keen-UI#171]
Seems that two-way data binding for `UiTabs` using `v-if` or `v-for` doesn't work.

``` html
<ui-tabs fullwidth type="icon-and-text">
    <div v-if="hasReceiverOption">
        <ui-tab icon="people" header="Add Receiver">
            Step 2
        </ui-tab>
    </div>
</ui>
```

Or

``` html
<ui-tabs fullwidth type="icon-and-text">
    <div v-show="hasReceiverOption">
        <ui-tab icon="people" header="Add Receiver">
            Step 2
        </ui-tab>
    </div>
</ui>
```

**Comment by JosephusPaye** [comment]
Hi @karlpatrickespiritu,

They way the tabs are setup to work, they are not compatible with `v-show/v-if`. 

The next version of Keen UI will support a `show` property for tabs, but for now you should consider using the `disabled` prop to disable specific tabs.

**Comment by karlpatrickespiritu** [comment]
I see. Is there any workaround to achieve this @JosephusPaye? Hmm. But I'll try if I get something to work. Thanks. Great work btw.

**Comment by JosephusPaye** [comment]
Version 1.0 now includes a `show` prop on `UiTab` for showing/hiding the tab.

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).
