### ISSUE TITLE
it is impossible to add custom validators to validatorjs because it's compiled into keen-ui sources

### ISSUE THREAD

**Issue by Narsul** [JosephusPaye/Keen-UI#172]
I was trying to add custom validator to use with `ui-textbox` but it's impossible cause in builded version of a keen-ui package `validatorjs` is compiled into keen-ui. So it's impossible to add custom validators to exactly that instance of `validatorjs`.

You mention `validatorjs` as a dependedency you shouldn't compile it into `keen-ui` sources

**Comment by JosephusPaye** [comment]
Similar to #143, see [my comment](https://github.com/JosephusPaye/Keen-UI/issues/143#issuecomment-273665412) there.
