### ISSUE TITLE
Modal in modal freezes IE

### ISSUE THREAD

**Issue by Gyuyeol** [JosephusPaye/Keen-UI#173]
Modal in modal (multiple depth) freezes  IE.

In Chrome, below message are shown in console

> keen-ui.js:8000 Uncaught RangeError: Maximum call stack size exceeded.(…)

I think that Chrome javascript engine has limited call stack size to protect from abnormal situation.

Is there a way to use multi depth UiModal without problem ?

**Comment by agc93** [comment]
I've also just run into this issue.

Chrome console indicates the problem is in the `restrictFocus()` function:

![screenshot 78](https://cloud.githubusercontent.com/assets/1369269/20050973/3a0bf3c6-a518-11e6-9fe4-c8465f00eea7.png)

**Comment by JosephusPaye** [comment]
@Gyuyeol, Having modals in modals is not supported. Any ideas to fix the `Uncaught RangeError` are welcome.
