### ISSUE TITLE
Passing additional parameters to menu-option-selected

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#175]
Hi there!

Imagine I have a table with users. I want to put `ui-icon-button` in each row with some kind of actions set. The problem is that I can set up `@menu-option-selected="optionSelected"` and get what menu item have been selected, however I also need to pass user.id in this method. Something like 
`@menu-option-selected="optionSelected(selectedMenuItem, user)"` when I'm looping through users array.

How can I achieve that?

Thanks in advance

**Comment by JosephusPaye** [comment]
You can try the following (doesn't seem to be documented by Vue, but it's in JS and it works):

```vue
@menu-option-selected="optionSelected(arguments, user)"
```

```js
optionSelected: function(args, user) {
    var selectedMenuItem = args[0];
}
```

`args` will be an array with the arguments passed to the handler, so `args[0]` will give you the selected option.
