### ISSUE TITLE
Is it possible to disable option in ui-select component?

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#178]
Hello Joseph. 

Need to disable some options in ui-select component. Whats the best way to do it?

**Comment by JosephusPaye** [comment]
Hi @lavezzi1,

This is currently not supported, but with the new [Scoped slots](https://vuejs.org/v2/guide/components.html#Scoped-Slots) supported for UiSelect options in Keen UI v1.0, you can pass your own custom template which allows you to disable specific options.

**Comment by liammcsheffrey** [comment]
Hi @JosephusPaye, could you give an example of how to achieve this via a scoped slot?
