### ISSUE TITLE
Add a delay option to tooltip

### ISSUE THREAD

**Issue by zxc23** [JosephusPaye/Keen-UI#181]
I would find it useful to have a delay available to the ui-tooltip component, ideally customisable by a prop where you pass in a length of time in ms to hover over the item before the tooltip is displayed.

**Comment by JosephusPaye** [comment]
Added a new `openDelay` prop in v1.0.

**Comment by lowerends** [comment]
@JosephusPaye Can we see see the code for the openDelay functionality somewhere. I can't seem to find it in this repository. Thanks!

**Comment by JosephusPaye** [comment]
@lowerends,

Not pushed yet. But it's in UiTooltip where we create the Tooltip instance in the `initialize()` method:

```js
this.tooltip = new Tooltip({
    target: this.$parent.$refs[this.trigger],
    content: this.$refs.tooltip,
    classes: 'ui-tooltip--theme-default',
    position: this.position,
    openOn: this.openOn,
    openDelay: this.openDelay
});
```

Where `this.openDelay` is the prop which specifies the tooltip delay in ms.

**Comment by lowerends** [comment]
Works like a charm, excellent! Thanks @JosephusPaye
