### ISSUE TITLE
Can you please add a release for the Vue 2.0 branch?

### ISSUE THREAD

**Issue by Evertt** [JosephusPaye/Keen-UI#182]
I'm not able to properly npm install the Vue 2.0 branch at the moment without a release?

Other than that I just want to say that I find it really beautiful what you've made here.

**Comment by JosephusPaye** [comment]
v1.0 with Vue 2 support will be released tomorrow.

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).
