### ISSUE TITLE
Documentation and demo's

### ISSUE THREAD

**Issue by artnova-david** [JosephusPaye/Keen-UI#183]
Are the Documentation and demo's in sync with the 'next' branche?
Thanks

**Comment by JosephusPaye** [comment]
No, but v1.0 is done and will be released tomorrow.

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).
