### ISSUE TITLE
Checkbox-group behavior on the 1.0.0 version

### ISSUE THREAD

**Issue by kbouh320** [JosephusPaye/Keen-UI#185]
Hello,

I saw on the new version of keen-ui that to link checkboxes together and make them share their v-model it's now necessary to declare the different options in the "options" prop. My concern is What if I want to wrap my checkboxes options in different DIV nodes ? (e.g.: for responsive layout purpose)

PS : Great work with this library, very useful

Kevin

**Comment by JosephusPaye** [comment]
Hi @kbouh320,

At the moment there is no way to change the contents of UiCheckboxGroup other than through the `options` prop. The reason for this is that we need direct access to the props and events of the child checkboxes.

This would not be possible if a slot was used (to allow for your use case).
