### ISSUE TITLE
How to put the option values on arguments for menu-option-selected function?

### ISSUE THREAD

**Issue by brickgale** [JosephusPaye/Keen-UI#187]
I'm kinda new at vue.js, was wondering if you can pass directly the menu option from the UiIconButton menu. Like on angular1 you can pass, $index on the current element on a ngRepeat. Since i can directly use menu array, was wondering if i can get the element index.

**Comment by JosephusPaye** [comment]
The first argument passed to the `menu-option-selected` handler function is the menu option. To get the index, you can call `indexOf(option)` on your array of menu options.

See here for an example: https://codepen.io/JosephusPaye/pen/jyZOzP
