### ISSUE TITLE
Cursors on labels perhaps inconsistent

### ISSUE THREAD

**Issue by zxc23** [JosephusPaye/Keen-UI#189]
The cursor on the UI Select component label is text, but the equivalent label on the UI Text component uses the default cursor. I just figured I would point it out as it seemed a little inconsistent to me, but do correct me if I'm mistaken. The UI Datepicker also uses a text cursor, and UI Autocomplete the default.

**Comment by JosephusPaye** [comment]
They should all have the default cursor, except when it's a floating label that's still inline, at which point it's the text cursor (for UiAutocomplete and UiTextbox) or the pointer cursor (for UiDatepicker and UiSelect).

Thanks for the heads-up, it has been fixed.
