### ISSUE TITLE
Docs: Customization

### ISSUE THREAD

**Issue by J12934** [JosephusPaye/Keen-UI#190]
The Customization Link in the Docs seems to link to the wrong folder in the Repo. So trying to visit the page throws a 404.

It currently links to:
`https://github.com/JosephusPaye/Keen-UI/blob/master/docs/Customization.md#customization`
it should probably link to:
`https://github.com/JosephusPaye/Keen-UI/blob/master/Customization.md#customization`

**Comment by JosephusPaye** [comment]
Thanks for the report this has been fixed. https://github.com/JosephusPaye/Keen-UI/commit/aa9eec04b528e86e04ef52b1ae01e974e519aae2
