### ISSUE TITLE
Right click context menu

### ISSUE THREAD

**Issue by rc201612** [JosephusPaye/Keen-UI#193]
Hi, 

The context menu detailed here: https://josephuspaye.github.io/Keen-UI/#/ui-menu - is it possible to show this on Right-Click?

Thanks,

**Comment by JosephusPaye** [comment]
Showing the menu on right click is currently not support. This is because Tether, the library used for dropdown positioning, doesn't support it: https://github.com/HubSpot/tether/issues/41
