### ISSUE TITLE
scroll behaviour on iPhone 7 safari feels not natural

### ISSUE THREAD

**Issue by dohomi** [JosephusPaye/Keen-UI#195]
Hi,
one feedback while testing the demo page on the iPhone 7 with safari: the scroll behaviour feels to be "stuck" on scroll, other than on other websites. Is it possible that the `CSS` 
```
-webkit-overflow-scrolling: touch
```
on scrollable `UiComponents` are missing? Just an idea to give a more natural experience for the user.

**Comment by JosephusPaye** [comment]
Thanks for the suggestion @dohomi, I will try to get an iPhone and see if it works. I have a Pixel and it works fine with Chrome and Firefox.

**Comment by JosephusPaye** [comment]
More info here: https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling
