### ISSUE TITLE
UIDatePicker

### ISSUE THREAD

**Issue by ptitkiller** [JosephusPaye/Keen-UI#202]
> Invalid prop: type check failed for prop "value". Expected Date, got String. 

I get datetime from Iso8601 format, but still with sever must use the new Date () to convert string to date. It's hard to be inconvenient, hope you will update soon.
I'm like KeenUi, thank you very much.

**Comment by JosephusPaye** [comment]
Hello @ptitkiller,
 
Since the date is submitted in ISO 8601 format (the default for HTML `input[type=date]`), I think it makes sense to also accept that as a string.

Will be added to next release, thanks.
