### ISSUE TITLE
Fix Button Padding

### ISSUE THREAD

**Issue by MishUshakov** [JosephusPaye/Keen-UI#203]
![Screen](https://cloud.githubusercontent.com/assets/10400064/22565858/fc5bef5c-e989-11e6-8aa0-5d9c2a47c806.png)

**Comment by EmilMoe** [comment]
Maybe you should add some description

**Comment by JosephusPaye** [comment]
@MishUshakov,

A bit more detail please, including what browser you are using.

**Comment by MishUshakov** [comment]
@JosephusPaye hey, i use latest version of Safari

**Comment by EmilMoe** [comment]
You can fix that with CSS https://www.w3schools.com/css/default.asp

**Comment by JosephusPaye** [comment]
Unfortunately, I don't have access to Safari to reproduce this.

It seems like it's an issue with Flexbox and `justify-content: center` on `.ui-button`.

**Comment by MishUshakov** [comment]
Seems fixed on the new Safari, but the ripple position is not very satisfying
