### ISSUE TITLE
UiTabs overflows when lots of tabs

### ISSUE THREAD

**Issue by badpunman** [JosephusPaye/Keen-UI#206]
Hi, nice looking library first of all. 

Tested out UITabs and found that it does not wrap or create scrolling context when tab entries go over the element width.

Any solution to this?

**Comment by JosephusPaye** [comment]
Hi @badpunman,

Wrapping (or scrolling) of overflowing tab elements is currently not supported. While there are currently no plans for this, it may be revisited in the future, and contributions are welcome.
