### ISSUE TITLE
Tabbing over RadioGroups with keyboard before selecting value 

### ISSUE THREAD

**Issue by badpunman** [JosephusPaye/Keen-UI#207]
This seems to be a slight inconsistency in usability:

When user has not selected value in radiogroup yet and tabs to one, it doesn't focus the default value, but either the first or last option available.

After the user has explicitly done a selection, it focuses on the selection properly when tabbing.

**Comment by JosephusPaye** [comment]
Hi @badpunman,
 
This is a side-effect of not setting the `checked` attribute on the radio element, which was fixed in https://github.com/JosephusPaye/Keen-UI/commit/727c1d81d1a609985726e3a13998befe38dc282c and will be in the next release.
