### ISSUE TITLE
UiConfirm focus "freezed" on modal buttons

### ISSUE THREAD

**Issue by ibbatta** [JosephusPaye/Keen-UI#208]
If I click on the UiConfirm button, when the modal dialog shows, the "cancel" or "submit" buttons look like focussed at half (Chrome version 56.0.2924.87 [64-bit] Macintosh)

Look the gif attached
 
![feb-03-2017 14-27-31](https://cloud.githubusercontent.com/assets/4375285/22593030/f3bc96d8-ea1c-11e6-94ed-ed647ced1fc6.gif)

**Comment by JosephusPaye** [comment]
Hi @ibbatta,
 
Thanks for the report, see https://github.com/JosephusPaye/Keen-UI/issues/205 which is about the same issue.

**Comment by ibbatta** [comment]
Sorry, my fault :)
*duplicate*
