### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by vikaskyadav** [JosephusPaye/Keen-UI#209]
Hi @JosephusPaye . It would be awesome if you provide navbar and sidebars too.

**Comment by donnygunawan93** [comment]
+999,999,999 Q(^_^)Q

**Comment by 20zinnm** [comment]
I just noticed Keen doesn't have this. I need something similar to http://materializecss.com/side-nav.html in order for me to use Keen.

**Comment by JosephusPaye** [comment]
While this will be nice to have (I would like it too!), I think it's out of scope for Keen UI, and there are dedicated CSS frameworks that are better options.

However, Keen UI does have a navbar, it's [UiToolbar](https://josephuspaye.github.io/Keen-UI/#/ui-toolbar).
