### ISSUE TITLE
UiTooltip

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#21]
I have a component that opens another component in UiModal (the modal is placed in the first component).

In the second component I have UiIconButton with tooltip, but these tooltip don't show up.

The tooltips works fine in the first component, so I think something is going wrong in the inheritance proces.

**Comment by JosephusPaye** [comment]
It may be a `z-index` issue. Could you perhaps make a simple demo?

**Comment by EmilMoe** [comment]
I can try later when I have the time, but otherwise the issue occur to me when

<ui-icon-button @click=openModal()"></ui-icon-button>

<ui-modal>
  <my-component></my-component>
</ui-modal>

MyComponent:
<ui-icon-button tooltip="abc"></ui-icon-button>

The tooltip is not showing up.

**Comment by JosephusPaye** [comment]
This has been fixed in [v0.8.8](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.8).
