### ISSUE TITLE
Need example codes.

### ISSUE THREAD

**Issue by vikaskyadav** [JosephusPaye/Keen-UI#210]
Please provide some simple example codes( not the source code as provided) for better understanding for beginners.

**Comment by JosephusPaye** [comment]
This is something I've been meaning to do, but haven't got around to. Contributions are welcome, as said on: https://github.com/JosephusPaye/Keen-UI/issues/44

**Comment by waratah** [comment]
Need an example on how to use UI autocomplete to handle API calls:

Addresses is my completion list and it is initially an empty array.   Handle input is called and a new list is loaded from an API call which then displays.  Code snippet is in typescript but it is enough to get an idea.

Future enhancement would be to make debounce a parameter on the autocomplete to save some of this code. _.debounce is in lodash.

  handleInput() {
      this.getAddressByText(this);
  }

  getAddressByText: Function = _.debounce((x) => this.fetchAddress(x), 500);

fetchAddress(c: AddressComponent): void {
    let list = AddressService.FindAddress(c.search);
    c.addresses =  list;
}
