### ISSUE TITLE
Can UiTooltip default to using parent as trigger?

### ISSUE THREAD

**Issue by zxc23** [JosephusPaye/Keen-UI#211]
I'm having a lot of difficulty getting the UiTooltip component to work inside v-for due to the use of refs. I'm not trying to do anything fancy, and the tooltip is just meant to trigger on hovering over the immediate parent div. I would find it immensely useful if trigger were an optional prop, and when not provided, it could just trigger on hovering over the parent.

**Comment by JosephusPaye** [comment]
@zxc23,
 
This would be a useful addition and I'll consider it for the next release. Thanks.

However, as a workaround, you can make a simple wrapper component and use `v-for`. That's how it's done in the docs: https://github.com/JosephusPaye/Keen-UI/blob/master/docs-src/pages/UiTooltip.vue#L15-L23

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
