### ISSUE TITLE
Compatibility with vee-validate

### ISSUE THREAD

**Issue by Dortamur** [JosephusPaye/Keen-UI#212]
I'm trying to migrate an app from manual/plain fields to Keen UI, so I can have a consistent feel, and use some of the extended widgets (like the Date Picker). I currently use vee-validate for field validation, which has been working well. However, when I try and use vee-validate as-is with a UiTextbox element, it isn't working.

Normally, my Input field would be something like:

```html
<input v-validate="rules" name="name" :value="value" />
```

The v-validate hooks it into the validation library, and data-rules defines which validation rules to apply.

Trying this with ui-textbox:
```html
<ui-textbox v-validate="rules" name="name" :value="value" />
```
... none of the normal validation rules seem to be triggering, and a custom validator I wrote is getting a value of _undefined_, instead of the expected value.

Something that may or may not be related - I notice that the "input" event from ui-textbox sends the field value, whereas the plain input tag sends an event, where you use event.target.value to get the value. Perhaps if ui-textbox sent an equivalent event, it would be compatible with the vee-validation tools.

Thanks

**Comment by Dortamur** [comment]
I've upgraded my vee-validate, and it now appears to be working with Ui Textbox  validation.

The different behaviour for the "input" event may be something worth considering, but otherwise, my issue seems to be resolved.

**Comment by JosephusPaye** [comment]
Hi @Dortamur,

What you are suggesting (to emit the Event object on input instead of the new value) will break compatibility with `v-model`. 

See https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events. It requires passing the new value as the first argument to the `input` event.
