### ISSUE TITLE
Multiple snackbar like toast?

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#213]
Its very cool feature, like this http://astaroverov.github.io/#!/open-source/vue-toast

**Comment by JosephusPaye** [comment]
Hi @rorc,
 
Having multiple snackbars visible at a time is [not recommended in the Material Design specs](https://material.io/guidelines/components/snackbars-toasts.html) and is not supported by Keen UI.

**Comment by rorc** [comment]
Hi) Sigh... But its very useful functionality =(
