### ISSUE TITLE
The text on the button is not centered

### ISSUE THREAD

**Issue by Akiyamka** [JosephusPaye/Keen-UI#215]
The problem is corrected by changing the font size with fewer decimal: font-size: 0.875 rem -> 0.9 rem
![image](https://cloud.githubusercontent.com/assets/6587585/22649072/7d646482-ec8a-11e6-8f96-152ad8b9640a.png)

**Comment by JosephusPaye** [comment]
Hi @Akiyamka,

The rem sizes are calculated programmatically, by converting `px` values to `rem` using this [`rem-calc()`](https://github.com/JosephusPaye/Keen-UI/blob/master/src/styles/util.scss#L10) function in Sass. This is why some of the values may be up to 3 or 4 decimal places.

The way the decimal values are rendered are [different across browsers](http://cruft.io/posts/percentage-calculations-in-ie/#browser-table), and manually adjusting the values to fix one browser may break another browser.
