### ISSUE TITLE
UIDatePicker - Set weekday start

### ISSUE THREAD

**Issue by nivv** [JosephusPaye/Keen-UI#217]
Would love an option to set a weekday start. Over here weeks start with mondays.

**Comment by JosephusPaye** [comment]
Hi @nivv,

Good suggestion, will see how this can be added.

**Comment by JosephusPaye** [comment]
Added in https://github.com/JosephusPaye/Keen-UI/commit/9a4d4481e11dc2b5869940ce1680427a65758552.

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
