### ISSUE TITLE
Make UiTabs header more reactive.

### ISSUE THREAD

**Issue by konstantin-popov** [JosephusPaye/Keen-UI#219]
Adding a tab to `UiTabs` works well, but when you remove a tab it remains visible in the header.
May be it's worth adding an `unregisterTab` method (as an addition to `registerTab`) and call it when a tab is destroyed?

**Comment by JosephusPaye** [comment]
Hello @konstantin-popov,

This is currently not supported and it's why we have the `show` prop on UiTab. Even though it doesn't remove the tab from the DOM, it creates the same effect by hiding the tab.
