### ISSUE TITLE
Is there a component for sidenav?

### ISSUE THREAD

**Issue by masterpowers** [JosephusPaye/Keen-UI#22]
I see there is a toolbar component... but is there a way i can use other preset component to acts as sidenav?

**Comment by athikrishnan** [comment]
To my knowledge, there isn't one. But the keen-ui documentation has a sidebar. You can check out the source files which is in src-docs folder of this repo. 

Related files are index.html, main.js and App.vue.

Reply if you need further assistance regarding the customization.

**Comment by masterpowers** [comment]
Ill check it out today and give a reply

**Comment by midascodebreaker** [comment]
manage to implement it thanks

**Comment by JosephusPaye** [comment]
Closing this now. If you still need help, you can reopen.
