### ISSUE TITLE
UiSelect multipleDelimiter as new line

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#222]
I tried to use `:multipleDelimiter='"\n"'` and `:multipleDelimiter="'\n'"` and `:multipleDelimiter="'<br>'"`, but unsuccessfully 😕

**Comment by JosephusPaye** [comment]
Hi @rorc,

Using a new line as UiSelect's `multipleDelimiter` is not supported, as the display text is rendered as plain text (so no `<br>`) and HTML doesn't support the `\n` for line breaks.

**Comment by rorc** [comment]
Hi @JosephusPaye. What about add this feature?
