### ISSUE TITLE
UiSelect makes nasty jump when active

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#224]
### Description
When clicking on UiSelect, all under elements jumping down by 1 pixel (because border-bottom sets 2 px)
http://joxi.ru/L21jx64TbZKeAX

### Steps to reproduce
1. Open https://josephuspaye.github.io/Keen-UI/#/ui-alert
2. Click on UiSelect (choosing version) in the left top sidebar

**Comment by JosephusPaye** [comment]
This is expected behavior, and fixing it is low prority at the moment. See https://github.com/JosephusPaye/Keen-UI/issues/214 for a similar issue.
