### ISSUE TITLE
the date&time picker is important

### ISSUE THREAD

**Issue by qetee** [JosephusPaye/Keen-UI#23]
keen-ui is so beautiful and useful; i have found the thing like it for a long time;  

I do not find a datetime component in keen-ui; and do you have a plan to support it???

and the rich text editor like Draft.js  is important too, i think

**Comment by JosephusPaye** [comment]
At the moment I'm tied up with work on another project and as such haven't been able to work on Keen. However, I'm hoping to complete the Select and Range Slider components soon. 

A date picker is also planned, and I'm open to a rich text editor component as well, though it will probably be a Vue wrapper around something like [Trix](https://github.com/basecamp/trix) or [Scribe](https://github.com/guardian/scribe) or [Squire](https://github.com/neilj/Squire).

**Comment by EmilMoe** [comment]
I have almost finished a Timepicker and I'm going to work on a Datepicker afterwards. I like the UI of Material and so too of Keen UI. I believe you, @qetee, can use these components.

Feel free to sign up to the mail, then I will let you know once the Timepicker is ready http://eepurl.com/b1e6tn 

I will make the Calendar after the Timepicker is done, so mail list will be provided at that time.

**Comment by lowerends** [comment]
@EmilMoe Thanks, looking forward to playing around with it!

Are you also planning on including a date range functionality in the datepicker, so that a range can be selected?

**Comment by EmilMoe** [comment]
Yes that would make sense to add yes. And a feature I will add, which I find odd no other datepicker has, is the option to have a label date and another "data" date. Data date would for example always be MM/DD/YYYY no matter the localization while the label could be anything.

I have already added a range option in my Timepicker, but I need to modify it a bit as for my own project I didn't want it to allow anyone to select after today.

I have currently been busy building a role/permission package for Laravel, but once that's shipped I will go back to these!

**Comment by lowerends** [comment]
I didn't dare to ask that actually, since indeed almost no other datepicker has that, but being able to define a data format (to send to the server) and a display format (to show to the user) would be extremely useful!

**Comment by EmilMoe** [comment]
I agree :-) I would like to put you on a mail list so I remember to tell you when I have updates, because I can hardly remember where I have been telling about it. But my problem is the number of mail lists grows fast. I might combine some related lists at a point. But for now you can sign up to it here and I will announce once there are something to download:

http://eepurl.com/b1fvA9

**Comment by mariaczi** [comment]
@JosephusPaye I do not want to open another one as you mentioned SELECT here - will it include MULTIPLE select?

It's great package, so we hope you will have time to develop it further! Good luck

**Comment by JosephusPaye** [comment]
@mariaczi A [Select](http://josephuspaye.github.io/Keen-UI/#/ui-select-docs) component just landed in [v0.8.8](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.8). It supports multiple selection and more.

**Comment by qetee** [comment]
Excellent buddy！ And could I add some components to keen-ui? such as citypicker, pagination...

**Comment by JosephusPaye** [comment]
@qetee I want to keep Keen UI small and focussed only on components that are useful in most projects. As such, I don't think components like a citypicker or pagination are a right fit.

However, thanks for the offer to contribute. If you still want to, you can help by adding code snippets to the docs. See this issue: https://github.com/JosephusPaye/Keen-UI/issues/44

**Comment by EmilMoe** [comment]
City picker sounds like a combination of ui-select and an API

**Comment by EmilMoe** [comment]
@JosephusPaye take a look at this https://chmln.github.io/flatpickr/

**Comment by JosephusPaye** [comment]
@EmilMoe That looks good, and I like the small file size, I might use it for the datepicker component.

**Comment by IvoPereira** [comment]
A datepicker would be very much appreciated.

Have been any advances on this? Thanks for this great work!

**Comment by EmilMoe** [comment]
@JosephusPaye 

I have begun working on a wrapper for Flatpickr and your UiTextbox. I must say it's very easy to work with. You probably have a better understanding for deep integration with your KeenUI, but let me share with you my initial work, use it in any way you want so you hopefully can make UiDatepicker faster :-)

https://gist.github.com/EmilMoe/c956f720fc9e1d2ac6fcd3169137de47

**Comment by mariaczi** [comment]
+1 for that as it is something really missing in this package when being really important component...
Using any other components making it not nice as styling is not going in line with the same material approach...

**Comment by JosephusPaye** [comment]
A datepicker is now available in v1.0. No plans for a timepicker, I would suggest using two/three UiSelects (for hour, min, and possibly AM/PM).

**Comment by webit-moses** [comment]
Can the datepicker support inputting a date range as well?

**Comment by JosephusPaye** [comment]
@webit-moses No. For that, you can use 2 date pickers.
