### ISSUE TITLE
Any reason why there are no grid in Keen UI?

### ISSUE THREAD

**Issue by nucamoz** [JosephusPaye/Keen-UI#232]
And why everybody advising to use any grid as a simple adding a css file to html? 
Then why Keen-UI exist in the first place?
I really doesn't understand the point.
If you advising to use any external css grid, then why all this mess with .vue components if there's no difference???

**Comment by JosephusPaye** [comment]
Hi @nucamoz,

The focus of Keen UI is not on being a CSS framework, but rather a set of lightweight ***interactive*** components which you can use in any project (here _interactive_ meaning components that use Javascript). And not every interactive component is included, but essential ones that are used in most projects.

There are no plans to add a grid system or styles for typography, tables, etc to Keen UI, as there are many better options to choose from for those, and they are not hard to integrate with Keen UI in a project.

**Comment by nucamoz** [comment]
Yes I get it now. Thank you for the answer and awesome Keen UI!
