### ISSUE TITLE
UiSelect resets query string when selecting on found items

### ISSUE THREAD

**Issue by projct1** [JosephusPaye/Keen-UI#234]

**Comment by JosephusPaye** [comment]
Hi @projct1,

I just tested this and it doesn't reset the query string when a found item is selected.

Example: 

![keen-ui- 234](https://user-images.githubusercontent.com/5924865/51797552-e02d2700-2259-11e9-9fe2-174f53b81c27.gif)

Closing for now.

If this is still an issue, please create a demo reproducing the problem and re-open this issue.
