### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by nucamoz** [JosephusPaye/Keen-UI#238]
I am trying to use UiCollapsible in my nuxt.js setup. It's using .vue files.

I've installed keen-ui with npm.
Then `import UiCollapsible from 'keen-ui'` and add

```
export default {
  head () {
    return {
      title: ` Главная ️`
    }
  },
  components: {
        UiCollapsible
  }
}
```

Then add the `<ui-collapsible>` tag in template. But error shows up. What's wrong?

**Comment by nucamoz** [comment]
Looks like it some kind of conflict with nuxt.js.

**Comment by JosephusPaye** [comment]
Hi @nucamoz,

Unfortunately, Keen UI depends on some browser globals like `document`, so it doesn't support server-side rendering for now. This mostly has to do with 3rd-party dependencies, like [Tether](https://github.com/HubSpot/tether).

**Comment by kodekrendel** [comment]
@JosephusPaye hi. Any changes on SSR? Are you planning this feature? Nuxt is really good.
