### ISSUE TITLE
UiTabs cannot set initial active tab

### ISSUE THREAD

**Issue by mcmillenb** [JosephusPaye/Keen-UI#240]
I'm unable to figure out how to set the active tab when a component using `<ui-tabs>` is initially loaded. 

I've tried affecting the `selected` property of the child `ui-tab` components, but this doesn't seem to have any effect:
```
<template>
  <ui-tabs ref="tabs">
    <ui-tab
      v-for="tab in tabs"
      :title="tab.title"
      :id="tab.id"
      :selected="selectedTab == tab.id">
    </ui-tab>
  </ui-tabs>
</template>

<script>
export default {
  props: ['selectedTab'],
  data() {
    return {
      tabs: [{
        title: 'Apple', id: 'apple',
      }, {
        title: 'Banana', id: 'banana',
      }, {
        title: 'Pear', id: 'pear',
      }],
    }
  }
}
</script>
```

I've also tried using the `setActiveTab` method to programmatically select the tab in the `mounted` handler: 

```
mounted() {
  console.log(this.selectedTab) // prints out 'apple'
  this.$refs.tabs.setActiveTab(this.selectedTab);
}
```

But, this gives me an error:

> Cannot read property 'length' of undefined at VueComponent.findTabById

**Comment by JosephusPaye** [comment]
Hi @mcmillenb,

Not sure what's going on here. I tried a similar setup and it works for me, see here: http://codepen.io/JosephusPaye/pen/ggNaaw.

Could you make a simple reproduction of this issue (like an online demo or repo) for testing? Thanks.

**Comment by mcmillenb** [comment]
Sorry for the delayed response. I was binding the active tab to the current route using vue-router and that was causing unrelated issues. This can be closed.
