### ISSUE TITLE
Clicking one UiButton with dropdown and then another doesn't change focus

### ISSUE THREAD

**Issue by mcmillenb** [JosephusPaye/Keen-UI#241]
I have two `<ui-button>` components:

```
<ui-button
  icon="help"
  has-dropdown
  dropdown-position="bottom right"
  type="secondary"
>
  Button A
  <ui-menu
    slot="dropdown"
    contain-focus
    has-icons
    has-secondary-text
    :options="menuOptions"
  ></ui-menu>
</ui-button>
<ui-button
  icon="person"
  has-dropdown
  dropdown-position="top right"
  type="secondary"
>
  Button B
  <ui-menu
    slot="dropdown"
    contain-focus
    has-icons
    has-secondary-text
    :options="menuOptions"
  ></ui-menu>
</ui-button>
```

If I click on one of the buttons, revealing the dropdown, and then click the other button, the first button appears to still maintain focus. If I then tab to change focus, the focus goes through the whole page before getting to the dropdown menu items.

Browser: Chrome 56 on Mac OS X 10

**Comment by JosephusPaye** [comment]
Hi @mcmillenb,

Could you make a quick online demo showing this? I tried running the code above and it works as intended. 

Here's a Codepen template with Vue and Keen UI 1.0: http://codepen.io/pen?template=oBpKEr.

**Comment by mcmillenb** [comment]
@JosephusPaye I'm having trouble replicating it on codepen. I think it might only be happening for buttons with both dropdown menus and tooltips. However I'm not able to get the ui-tooltip component to work with the codepen template you sent. Here's my attempt: http://codepen.io/brianmcmillen/pen/JEQeZP

**Comment by JosephusPaye** [comment]
Hi @mcmillenb,

If you still have this problem, see: https://codepen.io/JosephusPaye/pen/YEQRME.

I upgraded to Keen UI v1.0.1 (from v1.0.0) and moved the tooltip from inside the button to outside. Also fixed unclosed `<ui-menu>` tags.

**Comment by mcmillenb** [comment]
@JosephusPaye ah, no closing `</ui-menu>` tags. I see now why I wasn't seeing the tooltips at all! 

But in your codepen I'm still seeing that if you click the first button and then click the second button directly after, the tooltip for the first button appears, as if the first button has focus. Pressing tab at that point moves focus to the second button.
