### ISSUE TITLE
UiMenu with contain-focus doesn't contain focus when moving focus backwards

### ISSUE THREAD

**Issue by mcmillenb** [JosephusPaye/Keen-UI#242]
UiMenu components with the `contain-focus` property do not contain focus when pressing Shift + Tab to move focus to the previous focusable element.

Browser: Chrome 56 on Mac OS X 10

**Comment by JosephusPaye** [comment]
Hi @mcmillenb,

This is a known issue that will be fixed in the next version. Thanks.

**Comment by JosephusPaye** [comment]
Fixed in https://github.com/JosephusPaye/Keen-UI/commit/f84cd8a6386e852fc7128aba99031b5020bb4e6a.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
