### ISSUE TITLE
UiTextbox does not bind to dynamic property

### ISSUE THREAD

**Issue by anvaka** [JosephusPaye/Keen-UI#249]
I noticed that when I set `v-model` property of UiTextbox in response to asynchronous event - the UI stops showing correct value on focus blur:

![text_disappears](https://cloud.githubusercontent.com/assets/225407/23056416/223c499e-f4a0-11e6-9e27-dd0d16594001.gif)

* The model is correctly updated, even when UI does not show it
* It can be reproduced in Chrome/Firefox
* The same code works as expected for plain input field

Here is JSFiddle that reproduces it: https://jsfiddle.net/t18ekuee/2/ 

In case JSFiddle is not accessible, here is the same code

### markup
``` vue
<script src="https://npmcdn.com/vue/dist/vue.js"></script>
<script src="https://rawgit.com/JosephusPaye/Keen-UI/master/dist/keen-ui.js"></script>

<div id="app">
  <div v-if='showForm'>
      <ui-textbox v-model='inputs.firstName' label='first name'></ui-textbox>
      <!-- uncomment this to see, that regular input works -->
      <!-- input type="text" v-model='inputs.firstName' -->
      <a @click.prevent='logFields' href='#'>Show fields</a>
  </div>
</div>
```

### js

``` js
new Vue({
  el: '#app',
  data: {
    showForm: false,
    inputs: {} // <- note, there is no `firstName`
  },
  created() {
    setTimeout(() => {
      // Dynamic field name `firstName`:
      this.inputs.firstName = '';
      this.showForm = true;
    }, 1000);
  },
  components: {
    UiTextbox: KeenUI.UiTextbox
  },
  methods: {
    logFields() {
      alert(this.inputs.firstName);
    }
  }
})
```

**Comment by JosephusPaye** [comment]
Hi @anvaka,

I tried digging around a little but I wasn't able to find what's causing this. It's probably something related to the way `v-model` works with custom components. Will look into it more when I've got the time.

In the meantime, a good workaround is to declare all the reactive data properties upfront if you can, as recommended by the [Vue docs](https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties).

**Comment by anvaka** [comment]
Thanks!

+@yyx990803 - Evan, maybe you know what might be causing v-model to behave differently for custom components? It almost looks like it fails to notice newly added properties.

**Comment by JosephusPaye** [comment]
@anvaka, You can also use [`.$set`](https://vuejs.org/v2/api/#Vue-set):

So, instead of:

```js
 this.inputs.firstName = '';
```

Use:
```js
this.$set(this.inputs, 'firstName', '');
```

I'm now thinking it's probably just a reactivity issue, and perhaps not related to `v-model`.
