### ISSUE TITLE
UiSnackbar appear not in bottom on the viewport

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#251]
If page height more then screen height, snackbar shows wrong http://joxi.ru/xAeeQg6Ud7opAy
And snackbar not fixed...
If i overwrite rule `.ui-snackbar-container { position:fixed }`, then all is ok.

**Comment by JosephusPaye** [comment]
Hi @rorc,

The position of UiSnackbarContainer is actually up to you, as you may want to have it in a custom position on the screen. Similar to UiFab, you have to add the necessary CSS for positioning yourself. By default it appears inline.
