### ISSUE TITLE
Password floating label not minimized if input is auto-filled by the browser.

### ISSUE THREAD

**Issue by Cristy94** [JosephusPaye/Keen-UI#257]
On Chrome, if the password input is auto-filled by the browser (from a "remembered" password) the label is not minimized unless you focus the form or press any key on the keyboard. 

![password](http://i.imgur.com/xvhaKES.png)

Chrome Version 56.0.2924.87

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
