### ISSUE TITLE
How to include CSS file into app CSS?

### ISSUE THREAD

**Issue by mariaczi** [JosephusPaye/Keen-UI#26]
Hi,
I am using webpack for my project.
I can't just include css from node_modules.
How can I include keen-ui.css into my project CSS?

**Comment by athikrishnan** [comment]
i am not a user of webpack, but i think the best way to go about it is to copy (i am using gulp) the css file to your public/asset folder.

**Comment by JosephusPaye** [comment]
Yeah, what @athikrishnan said. Also, if you're using a prepressor like Stylus, you can import the CSS file like so:

```stylus
@import '~keen-ui/dist/keen-ui.css';
```

**Comment by mariaczi** [comment]
Thanks.

**Comment by nicooprat** [comment]
I got it working by using `import 'keen-ui/dist/keen-ui.css'` with Webpack (using the [official template](https://github.com/vuejs-templates/webpack)) in `main.js`:

````js
import Vue from 'vue'
import Keen from 'keen-ui'
import 'keen-ui/dist/keen-ui.css'

Vue.use(Keen)
````

However, styles aren't applied because they don't match. CSS is using class names, HTML is using custom tags:

````csss
.ui-alert {
  font-family: Roboto, -apple-system, BlinkMacSystemFont, "Segoe UI", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif;
  ...
}
````

````html
<ui-alert type="warning">
  Ay caramba! Alerts can also contain HTML. <a href="https://google.com" target="_blank">Click here</a> for Google.com.
</ui-alert>
````

What am I missing?

**Comment by nicooprat** [comment]
Answering to myself, this works (notice the `:` before the attribute): 

````html
<ui-alert :type="warning">
  Ay caramba! Alerts can also contain HTML. <a href="https://google.com" target="_blank">Click here</a> for Google.com.
</ui-alert>
````

The output HTML becomes:

````html
<div class="ui-alert" _v-10f2d0f9="">
    <div class="ui-alert-body ui-alert-toggle-transition info" role="alert">
        ....
    </div>
</div>
````

I guess it's the expected behavior!

**Comment by nicooprat** [comment]
Solved by following https://github.com/JosephusPaye/Keen-UI/issues/29
