### ISSUE TITLE
不能在使用 `position: absolute` 定位的元素内正常使用 `UiPopover` 组件

### ISSUE THREAD

**Issue by vuesify** [JosephusPaye/Keen-UI#260]
在某个容器上使用 `position: absolute` 定位后，不能在其内部正常使用 `UiPopover` 组件，下面是一个简单的演示示例：[http://jsfiddle.net/vuesify/qx5y6znz/8/embedded/#Result](http://jsfiddle.net/vuesify/qx5y6znz/8/embedded/#Result)

在组件 `UiPopover` 内部初始化 `tether-drop` 时设置 `constrainToScrollParent: false` 似乎可以解决这个问题，但是又出现新的问题，就是打开的`UiPopover`被滚动到被滚动到可视区域外时，点击网页任何地方，触发`UiPopover`组件的元素会被滚动到可视区域内。

**Comment by JosephusPaye** [comment]
This seems to be a problem with Tether: https://github.com/HubSpot/tether/issues/210.

As a workaround, make sure `height` or `min-height` is set on `<body>` (and `<html>`).

```css
html,
body {
    height: 100vh;
}
```

See your updated Fiddle: http://jsfiddle.net/qx5y6znz/9/
