### ISSUE TITLE
Support for optgroup in UISelect

### ISSUE THREAD

**Issue by jameswragg** [JosephusPaye/Keen-UI#265]
I'm working with long lists that are grouped & wondered if there's any plan for supporting `<optgroup>` in UISelect?

Ideally I'd like to be able to list the groups at a top level & expand the headings. This combined with the search would be very powerful.

**Comment by JosephusPaye** [comment]
Hi @jameswragg,

There are no plans for option groups in UiSelect at the moment. May be revisited in the next major update, and contributions that don't break the current API are welcome.
