### ISSUE TITLE
UiSnackbar, can it be used without a container?

### ISSUE THREAD

**Issue by rlightner** [JosephusPaye/Keen-UI#266]
I have page that scrolls. Can't figure out how to get the UiSnackbar to just show at the bottom of the browser window vs the bottom of the page which is below the fold.

**Comment by JosephusPaye** [comment]
HI @rlightner,

UiSnackbar is meant to be used with UiSnackbarContainer, which handles things like positioning to ensure snackbars are visible even when scrolling.

If you want to use UiSnackbar without a container, you can use CSS `position: absolute` on the snackbar or a wrapper div to keep it at the bottom of the browser window.

**Comment by rlightner** [comment]
I placed the container at the bottom but it didn't seem to keep it at the bottom of the window. I placed it at the top and the UiSnackbar just sits at the top pushing the content down.

**Comment by JosephusPaye** [comment]
Do you have a parent div of the container with `position: relative`? Cause that would prevent the container from being absolute to the browser window, instead being absolute to the nearest relative parent.
