### ISSUE TITLE
Using config for individual components

### ISSUE THREAD

**Issue by klepje** [JosephusPaye/Keen-UI#267]
Hi,

I've a question regarding using the config for individual components.
I've tried to set it up in different ways, but I can't get the config to work. I want to disable the ripple effect, which is in the config as `disableRipple`. Is it possible to use the config with individual components?

What I tried to do:
1. Using standalone individual components:
Tried to use the standalone individual components by importing it in an component with: `import UiButton from 'keen-ui/lib/UiButton'`. In my main.js file I set the config with these lines:
```javascript
window.KeenUiConfig = {
  disableRipple: true
}
```

2. Tried it with importing the components in an component:
`import { UiButton } from 'keen-ui'` also with the same config as above.

Both ways doesn't have the expected result, the ripple is still visible on the component. I can set the `disableRipple` prop to, the example, the button.. but I think that's not really a good solution.

Can you guys help me? :) Thanks!

**Comment by JosephusPaye** [comment]
Hi @klepje,
 
When using the global config, you have to use `require()` instead of `import`. Example:

```js
window.KeenUiConfig = {
  disableRipple: true
};

const UiButton = require('keen-ui').UiButton;
```

The reason for this is because `import` statements are hoisted to the top, and are executed before the rest of the code, so the component will be imported before your config is set.
