### ISSUE TITLE
Template errors with Vue 2.2.1 

### ISSUE THREAD

**Issue by timnovis** [JosephusPaye/Keen-UI#268]
I cloned this project, installed dependencies and ran the dev server - but got a lot of closing tag template errors. This seems to be related to Vue 2.2.x, see release notes here - https://github.com/vuejs/vue/releases/tag/v2.2.0

**Comment by JosephusPaye** [comment]
Hi @timnovis,
 
This will be checked and fixed in the next release, thanks.

**Comment by JosephusPaye** [comment]
Fixed in https://github.com/JosephusPaye/Keen-UI/commit/bb4c3a8fa3ffda37f08d014927e69927875f12f4

**Comment by JonasDoebertin** [comment]
@JosephusPaye Any chance you could tag a release with this changes included? 😳

**Comment by rorc** [comment]
@JosephusPaye How i can install this update?

**Comment by rorc** [comment]
I tied use `npm i git://github.com/JosephusPaye/Keen-UI.git#next`, but unsuccessfully 🙁

**Comment by JosephusPaye** [comment]
`v1.0.1` has been released with this and other similar fixes.

https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.1
