### ISSUE TITLE
Modal shift

### ISSUE THREAD

**Issue by dolcy** [JosephusPaye/Keen-UI#269]
Great stuff; it's a pleasure working with this framework. Even with the prevent-shift, which doesn't seem to do anything, I get a jittery modal box. I found that the following works well:

```
html {
     height: 100vh;
}

// Ok across all browsers
body {    
    width: 100%;
    padding-right: 0px !important;
    margin-right: 0px !important;
}

// Change from KeenUI default overflow: hidden;
.ui-modal--is-open {
    overflow: auto;
}
```

Hope this helps someone.

**Comment by JosephusPaye** [comment]
Hi @dolcy,
 
Thanks for the info. It's a bit tricky working with the scrollbars across various browsers, and the current system works for me in another project.
