### ISSUE TITLE
To make it working with vue-validator

### ISSUE THREAD

**Issue by mariaczi** [JosephusPaye/Keen-UI#27]
Hi,
@JosephusPaye 
Is it possible to make it working with vue-validator?
It is more convenient than lib used by you - much less code necessary etc.
I think you would just have to accept v-validate and v-model and just replicate it (currently impossible).
What you think? A lot of people using vue-validator.
I found your package today and already like it so much!

**Comment by JosephusPaye** [comment]
At the moment there are no plans for adding vue-validator, as that would require a significant change to how the components work currently. 

What is it you are trying to validate? Maybe someone here can help you out.

**Comment by mariaczi** [comment]
I need quite often to have something shown/not shown based on full form validation which is easy with vue-validator (v-if="$validator1.valid") but looks complicated with your way of working with validation.
Maybe I am missing something and there can be still quite straight forward solution.

**Comment by JosephusPaye** [comment]
@nivv By default validations are performed in realtime as the user types. For delayed validation, the `debounce` prop could be used, but there seems to be [a bug](https://github.com/JosephusPaye/Keen-UI/issues/42) with it.

For now you can use the `validate-on-blur` prop. Set it to `true` to only perform validations when the user blurs (i.e. moves away from) the field.

**Comment by JosephusPaye** [comment]
The `debounce` bug was fixed in https://github.com/JosephusPaye/Keen-UI/commit/dfec5e2fd2e830f5a7e2960f277ee4fdd20c03a2

**Comment by thearabbit** [comment]
+1
