### ISSUE TITLE
UISelect is not returning the pure value

### ISSUE THREAD

**Issue by peXed** [JosephusPaye/Keen-UI#270]
Hello!

I'm not sure if I do something wrong or if the component is broken. If I set the options for the ui-select to a Array with options like:

`[
{label: 'Mr.', value: 1 },
{label: 'Mrs.', value: 2 },
{label: 'Company.', value: 3 },
]`

The v-model gets set to an object and not to a simple number.

Is there a way to change this behaviour?

Thanks.

**Comment by JosephusPaye** [comment]
Hi @peXed,

See my comment on a similar issue here: https://github.com/JosephusPaye/Keen-UI/issues/107#issuecomment-238015030. Perhaps I'll revisit this in a future release. Meanwhile, contributions are welcome.
