### ISSUE TITLE
Floating label for UiSelect with the multiple attribute is a little off position

### ISSUE THREAD

**Issue by mcmillenb** [JosephusPaye/Keen-UI#272]
http://codepen.io/brianmcmillen/pen/KWgoWX

The starting position for a floating label for a UiSelect component with the `multiple` attribute is a little lower than if the component doesn't have the `multiple` attribute.

**Comment by JosephusPaye** [comment]
Fixed in https://github.com/JosephusPaye/Keen-UI/commit/81668428e7a9988f49fa9a991001f695dcfbaa18.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
