### ISSUE TITLE
Trigger focus on ui-textbox?

### ISSUE THREAD

**Issue by Cristy94** [JosephusPaye/Keen-UI#273]
I have a `ui-textbox` inside a `ui-confirm` modal. I want the text input to be focused when the modal is shown, but using the `autofocus` directive doesn't work.

I also tried adding a `ref` to the `ui-textbox` elemnt and call `this.$refs.myInput.focus()` but it didn't do anything.

How can I manually focus the input, or make sure the input is focused when it is shown inside the modal?

**Comment by JosephusPaye** [comment]
Hi @Cristy94,

This is something I've needed recently as well, and will be part of the next release as a `focus()` method on UiTextbox. For now, you can use this:

```js
this.$refs.myInput.$refs.input.focus();
```

**Comment by Cristy94** [comment]
That worked, but I had to wrap it in a `setTimeout` and used `100ms` delay. I tried with `$nextTick` but the input wasn't yet created (being inside a ui-confirm modal and shown based on a `v-if`).

**Comment by JosephusPaye** [comment]
Added in https://github.com/JosephusPaye/Keen-UI/commit/1027992a0bc1e21351cf5163ff5a49c8f1899f99.

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).

**Comment by wbern** [comment]
The autofocus attribute doesn't work for me when the elements are in a modal.

I fixed it with this work-around. It was important to focus the modal element first.

```
            this.$refs['myModal'].open()
            setTimeout(() => {
                this.$refs['myModal'].$el.focus();
                this.$refs['myModal'].$el.querySelector('input').focus()
            }, 10)
```

**Comment by kilobyte2007** [comment]
@wbern for autofocusing on elements inside modals, this I created a directive in my project which call the focus() method on keen-ui textbox component (note that my modals are hidden with v-if):
```
Vue.directive('autofocus', {
  inserted (el, binding, vnode) {
    setTimeout(() => {
      vnode.componentInstance && vnode.componentInstance.focus()
    })
  }
})
```

...then use it like this:
```
<ui-textbox v-autofocus/>
```
