### ISSUE TITLE
[Question] How would you feel about KeenUI being added to CDNJS?

### ISSUE THREAD

**Issue by bbuck** [JosephusPaye/Keen-UI#283]
I use CDNJS a lot, for both work and play. I wanted to experiment with your library as I'm learning Vue right now but I was disappointed to find out it's not in CDNJS right now. I wanted to make a PR to their project adding your project but I figured I'd reach out to you first to see if you would rather do it, or if you're not interested having it accessible there.

It does meet their fairly lax popularity requirements (100 stars and/or 500 downloads a month on npmjs.com so It's good to go. If you want to do the PR to their project yourself, they do prioritize PRs from the libraries authors, but I'm okay doing it if you would like.

https://github.com/cdnjs/cdnjs
https://github.com/cdnjs/cdnjs/blob/master/.github/CONTRIBUTING.md

**Comment by JosephusPaye** [comment]
Hi @bbuck, 

Feel free to submit it, thanks!
