### ISSUE TITLE
How to know if a certain Component is designated to specific event like opened/open?

### ISSUE THREAD

**Issue by brickgale** [JosephusPaye/Keen-UI#290]
I've noticed on v0.8.9 it is usually dispatched as 'opened' while on v1.0 it is emitted as 'open'. How do we actually know what component is it? since it doesn't pass any other arguments.

**Comment by JosephusPaye** [comment]
Hi @brickgale,
 
Not sure if I understand the question, but generally, you would attach the `open` event directly to the specific component where you want to listen for open, so you will already know the component.

**Comment by brickgale** [comment]
I have these cases that I am listening an event 'opened', the workaround I did was to get the attached class on 'document.body' since every 'opened' for example, openning a modal there is a class 'ui-modal-open'. I have since other vue libraries that uses a prefix for a certain event so that it won't overlap to any event. But, I think this is only applicable on v0.8.9 or Vue1.0.* since event handling on Vue2 is different...
