### ISSUE TITLE
UiSelect dont trigger change event on hidden input

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#291]

**Comment by JosephusPaye** [comment]
Hi @rorc,

It's not meant to do so. The hidden input is only included​for submitting the value. Everything else, including the `change` event happens on the main UiSelect.

**Comment by rorc** [comment]
@JosephusPaye But... If hidden input value changing (if i select some items ot item on select), it must also trigger `change` event, due to hidden input value was changed...
