### ISSUE TITLE
How to make a responsive looking UiPopover on smaller screens?

### ISSUE THREAD

**Issue by brickgale** [JosephusPaye/Keen-UI#292]
I'm trying to change the responsiveness of the UiPopver to put the width 100% on smaller screens and not depending on the horizontal positioning(transformX) value since it literally sticks it on the specific location of the popover trigger element. I'm fine with its vertical positioning(transformY) but would like to eliminate the horizontal positioning to put the popover viewable on 100% width. (Testing it on different browser screens, it returns to it original horizontal positioning)
![popover](https://cloud.githubusercontent.com/assets/6366161/24342861/0a68e7b8-12f6-11e7-8a91-ebd76fafa87c.png)

**Comment by brickgale** [comment]
I think this is connected with the 'tether-drop' dependency.

**Comment by JosephusPaye** [comment]
Hi @brickgale,

It's a `tether` issue and I'm trying to find a workaround for the next version. See: https://github.com/HubSpot/drop/issues/16

**Comment by JosephusPaye** [comment]
Should be fixed with the switch to Tippy.js/Popper.
