### ISSUE TITLE
Dynamic v-model

### ISSUE THREAD

**Issue by Christilut** [JosephusPaye/Keen-UI#293]
Hey, I'm trying to make UI based on dynamic properties but KeenUI doesn't seem to like them.

I created a very minimal repo here https://github.com/Christilut/keenui-dynamic-textbox

```js
  data () {
    return {
      newContent: {}
    }
  },
  created () {
    this.newContent['textbox'] = 'test'
  }
```
with
```html
    <ui-textbox v-model="newContent['textbox']" placeholder="Textbox"></ui-textbox>
```

Resulting in the component value never updating and thus deselecting the text field, it reverts back to its initial value

**Comment by JosephusPaye** [comment]
Hello @Christilut,
 
This is a Vue reactivity issue, see https://github.com/JosephusPaye/Keen-UI/issues/249.

To get around it, use [`.$set`](https://vuejs.org/v2/api/#Vue-set), as recommended by the [Vue docs](https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties):

```js
this.$set(this.newContent, 'textbox', 'test');
```
