### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by rowanwins** [JosephusPaye/Keen-UI#295]
Gday 

So I've been bringing in standalone components but I'm running into an error when I try to build my webpack project due to uglify.

The error I get is 
````
ERROR in static/js/vendor.84054551217cf20f3966.js from UglifyJs
Unexpected token: punc ()) [./~/keen-ui/src/helpers/modality.js:5,0][static/js/vendor.84054551217cf20f3966.js:66306,47]
````

If I comment out `import 'keen-ui/src/bootstrap';` the error goes away

The error occurs running `npm run build` using the [webpack template](https://github.com/vuejs-templates/webpack).

Let me know if I can provide any further details

Cheers
Rowan

**Comment by JosephusPaye** [comment]
Hi @rowanwins,

It seems like the file isn't being transpiled to ES5 before it's passed to UglifyJS for minification. And I don't think UglifyJS understands ES6 arrow functions, which is where the error seems to be from (https://github.com/JosephusPaye/Keen-UI/blob/master/src/helpers/modality.js#L5):

```
document.addEventListener('DOMContentLoaded', () => {
```

Perhaps the webpack template is set to not compile files files from `node_modules`? Not sure how it's setup.

**Comment by cqcwillard** [comment]
@JosephusPaye, that is definitely the issue.

The webpack templates have this configuration for babel:
`{
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
},`

Commenting out the exclude resolves the problem for me.

**Comment by JosephusPaye** [comment]
@cqcwillard,
 
In that case you can exclude all modules except `keen-ui`:

```js
exclude: /node_modules(?!(\/|\\)keen-ui)/
```

This will exclude all files in `node_modules` from Babel compilation except Keen UI files.
