### ISSUE TITLE
UiFab with small size looks misaligned on iPhone

### ISSUE THREAD

**Issue by anvaka** [JosephusPaye/Keen-UI#296]
I tested this in iOS simulator and on the real device.

```
    <ui-fab
        class='fab-add'
        color='primary'
        icon='add'
        size='small'
    ></ui-fab>
```

Will look fine in the browser and browser in simulator mode:

![image](https://cloud.githubusercontent.com/assets/225407/24517879/cd7c7a5e-1534-11e7-88e7-a7ba2254b02b.png)

However when tested on real iOS simulator the icon looks misaligned:

![image](https://cloud.githubusercontent.com/assets/225407/24517904/df804762-1534-11e7-8dd4-e13d8086dfe3.png)

Changing size to `normal` fixes the problem, however it gives larger button too.

I noticed that if I change `font-size: 1.5rem` to `font-size: 1rem;` on `ui-icon` inside small UiFab, then it looks perfectly aligned:

![image](https://cloud.githubusercontent.com/assets/225407/24517969/1f07200e-1535-11e7-93f5-1123a2f654ea.png)

**Comment by JosephusPaye** [comment]
This will be fixed in the next release, thanks.

**Comment by JosephusPaye** [comment]
Hmmm, seems like an iOS Safari bug.

If you need this, just apply the fix that @anvaka suggested using CSS:

```css
.ui-fab--size-small .ui-icon {
	font-size: 1rem;
}
```
