### ISSUE TITLE
List of checkboxes connected to one list

### ISSUE THREAD

**Issue by mariaczi** [JosephusPaye/Keen-UI#30]
Hi,

I can't go with rendering list of days with checkboxes (as long as there is no select, it's way around for multiple select).

` <ui-checkbox v-for="day in days" class="col s12" :value.sync="selectedDays" v-bind:id="day.id" v-bind:label="day.name"> `

I was trying few other ways but no success.

I need to fill array with selected values.

**Comment by JosephusPaye** [comment]
Try the new [Select](http://josephuspaye.github.io/Keen-UI/#/ui-select-docs) component in [v0.8.8](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.8).

**Comment by JosephusPaye** [comment]
Implemented in https://github.com/JosephusPaye/Keen-UI/commit/aa13404a95840828234099a6dd09aa998f551fcb. 

UiCheckbox now matches the behavior shown here: http://vuejs.org/guide/forms.html#Checkbox

**Comment by JosephusPaye** [comment]
Now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9), see the [UiCheckbox docs](https://josephuspaye.github.io/Keen-UI/#/ui-checkbox-docs).

**Comment by JosephusPaye** [comment]
In v1.0, use the new UiCheckboxGroup component instead.
