### ISSUE TITLE
What is the point of the "checked" prop for the checkbox and radio button?

### ISSUE THREAD

**Issue by sirxemic** [JosephusPaye/Keen-UI#300]
Pretty much what it says on the tin. Since the components already have a `value` prop to basically set the "checked" state with, why would you use an extra prop?

Maybe I'm missing something, but it's a bit confusing at the very least.

**Comment by JosephusPaye** [comment]
Hi @sirxemic, 

The `checked` prop applies the checked HTML attribute, which is used when submitting the form the server. It's also useful for keyboard accessibility, as seen in this issue: https://github.com/JosephusPaye/Keen-UI/issues/207

See here for details: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox, important part being: 

> Note: If a checkbox is unchecked and then the form is submitted, there is no value=unchecked data submitted; the value is not submitted to the server at all.
