### ISSUE TITLE
UiToolbar brand link

### ISSUE THREAD

**Issue by Christilut** [JosephusPaye/Keen-UI#302]
I want to add a link to '/' on the brand in UiToolbar which is pretty standard but according to documentation I'm supposed to add my HTML to the `brand` slot. This is a fine solution however it seems that contents of the named slot `brand` end up inside the `ui-toolbar__body` div. And the normal brand text is in the `ui-toolbar__left`.

I'd like my new brand slot contents in the `ui-toolbar__left` div because that's where the brand normally is. Or am I doing something wrong?

Sidenote: perhaps a `brandTo` prop on UiToolbar? I'm definitely against bloating the components and using a named slot is a good solution but a brand being a clickable link to home is super common and standard UX.

**Comment by JosephusPaye** [comment]
Hi @Christilut,

It seems like the brand slot actually goes in the `ui-toolbar__left`. See this https://codepen.io/JosephusPaye/pen/eRXjwW.

**Comment by JosephusPaye** [comment]
Closing for now. Reopen if this is still an issue.
