### ISSUE TITLE
autosize option for UiTextbox should calculate on render

### ISSUE THREAD

**Issue by MadeMyDay** [JosephusPaye/Keen-UI#303]
Hi,

first of all thank you so much for your project! 

I try to use the autosize option on a Textbox which works well for inputting text (i.e. autosizing works). But if the form with that box gets rerendered the initial row option is used instead of a dynamic refreshSize() on mounted. My investigation shows that the textbox doesn't seem to be ready on "mounted". But if I use a timeout it works:

```
mounted() {
        if (this.multiLine && this.autosize) {
            window.setTimeout(()=>{
                autosize(this.$refs.textarea);
                this.autosizeInitialized = true;
            },200)
        }
    },
```

Another question: How I am supposed to access the methods in KeenUI? Via $refs or $children? 

Thanks again!
Marc

**Comment by JosephusPaye** [comment]
Hello,

This is weird behaviour I can't seem to reproduce. Is it possible for you to make a demo showing the issue? 

Here's a Codepen template setup with Vue and Keen UI: https://codepen.io/pen?template=oBpKEr.

**Comment by MadeMyDay** [comment]
Hi,

the issue seems to come from computed values. If the initial model contains more than the defined rows there is no problem. If the the initial value is set with a computed value the amount of text has no influence. 

https://codepen.io/MadeMyDay/pen/NveLKL?editors=1111

A direct refresh wouldn't help since the documentation states:

> $refs are only populated after the component has been rendered, and it is not reactive. It is only meant as an escape hatch for direct child manipulation - you should avoid using $refs in templates or computed properties.

So the question is: How can I make the textbox reactive if for example the data comes from an ajax request or an indexedDB?

**Comment by JosephusPaye** [comment]
Hi @MadeMyDay,

If this is still relevant, you can wrap the call to `refreshSize()` in a `nextTick()` to wait for Vue to update before calculating the new size:

```js
this.text3 = this.text2;
this.$nextTick(() => {
	this.$refs.textbox3.refreshSize();
});
```

Here's an updated demo showing that: https://codepen.io/JosephusPaye/pen/jdqwqZ?editors=1011
