### ISSUE TITLE
How to handle CSS names collision

### ISSUE THREAD

**Issue by double-thinker** [JosephusPaye/Keen-UI#307]
Hi.

I'm using Keen components inside other web application that I can't modify. The problem is that app uses ui-icon and other CSS classes and conflicts with KeenUI styles.

I made a workaround with extract-text-plugin and adding to all selectors another parent class. For example. ` .myScope .ui-con { ... } ` instead of a global `.ui-icon` selector

Is there any other solution without modifying the source code of Keen or maybe is planned a more elegant solution like CSS Modules, scoped styles or adding a parameter for prefixing all classes by default?

Thanks

**Comment by JosephusPaye** [comment]
Hello @double-thinker,

There is not much that can be done about this. The `ui-` namespace was chosen to avoid this very problem.

Using scoped styles will make it harder to override Keen UI styles from outside the library, making it hard to customize.

Perhaps I'll revisit this in the future.
