### ISSUE TITLE
UiSelect bugs with events when set "name" attribute

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#310]
1. Native event "change" do not trigger if i chose some item in dropdown menu (`@select` event)
2. `@select` event dont set value on hidden input.

I have to set value on hidden input manually and duplicate call `changeFilterBars`:
```html
<ui-select
    name="bar_id"
    :options="{{ $options }}"
    v-model="filterBarList"
    @change="changeFilterBars"
    @select="changeFilterBars"
    ref="filterBar"
    :has-search="true">
</ui-select>
```
```javascript
changeFilterBars(data) {
    $('input:first', this.$refs.filterBar.$el).val(data.id).change();
}
```
Ideally its must work without `@change="changeFilterBars"` and `@select="changeFilterBars"`

**Comment by JosephusPaye** [comment]
Hi @rorc, 

1. When the value of an input element is changed programmatically (from JS), the `onChange` is not fired. This is the default HTML behavior. This is why we emit the `change` and `select` events on the component (not on the hidden input).

2. I just checked and the new value is set on the hidden input on `@select`.  There may be some problems with your usage, see here for a working example: https://codepen.io/JosephusPaye/pen/NgJOpy?editors=0100

Closing this now.
