### ISSUE TITLE
UiIconButton cannot render icon slot

### ISSUE THREAD

**Issue by zdpeitang** [JosephusPaye/Keen-UI#314]
I'm using UiIconButton with FontAwesome (because of some reason unable to include material icon font), in UiButton the icons can render the custom icon slot, but in UiIconButton not.

sample html:
```html
<ui-icon-button size="small">
  <ui-icon icon-set="fa fa-fw" icon="fa-question" slot="icon" removeText></ui-icon>
</ui-icon-button>
```

**Comment by matheusgrieger** [comment]
Had the same problem. Reading the source I've found that the documentation is actually innacurate with the code, since it actually is using the default slot.

So you can either ommit the `slot` attribute, or use `slot="default"`, and it will work.

**Comment by JosephusPaye** [comment]
Yeah, the docs are wrong. Fixed here: https://github.com/JosephusPaye/Keen-UI/commit/35c1b1c1a2f23237e5644e119d4d080fb24bef01.
