### ISSUE TITLE
Opening UiConfirm from inside UiMenu

### ISSUE THREAD

**Issue by Christilut** [JosephusPaye/Keen-UI#315]
I have a UiIconButton that opens a UiMenu with a few options. When clicking the Delete option, it opens a UiConfirm.
The problem is that the UiMenu stays open and overlaps the UiConfirm.

I can't seem to find a way to manually close the UiMenu and I think it should automatically close anyway when it opens a modal.

I can make a fiddle if its needed. Just let me know.

**Comment by JosephusPaye** [comment]
@Christilut, please create a fiddle.

**Comment by Christilut** [comment]
https://jsfiddle.net/7xad950m/4/

**Comment by JosephusPaye** [comment]
You can call `.closeDropdown()` on the UiIconButton before opening the modal: https://jsfiddle.net/7xad950m/6/

**Comment by Christilut** [comment]
Ah thanks. I had tried that but not on the `ui-button` but on the `ui-menu`, which didn't work.

**Comment by lavezzi1** [comment]
@Christilut How to open modal on click specific item in UiMenu? Lets say I have 5 item in menu, and want to open modal on click second option?

**Comment by Christilut** [comment]
@select='menuSelected' on the ui-menu which goes to the `menuSelected`
method. The first argument will be the selected item and you can do a
switch case there.

**Comment by lavezzi1** [comment]
@Christilut whats the first argument?

**Comment by Christilut** [comment]
```

const menuOptions = [
    {
        id: 'edit',
        label: 'Edit',
        icon: 'edit',
        secondaryText: 'Ctrl+E'
    },
    {
        id: 'duplicate',
        label: 'Duplicate',
        icon: 'content_copy',
        secondaryText: 'Ctrl+D'
    },
    {
        id: 'share',
        label: 'Share',
        icon: 'share',
        secondaryText: 'Ctrl+Shift+S',
        disabled: true
    },
    {
        type: 'divider'
    },
    {
        id: 'delete',
        label: 'Delete',
        icon: 'delete',
        secondaryText: 'Del'
    }
];
```

The object corresponding to the option you clicked

**Comment by lavezzi1** [comment]
@Christilut So how can I access to specific object? Can you show an example please!
