### ISSUE TITLE
Form Validate?

### ISSUE THREAD

**Issue by thearabbit** [JosephusPaye/Keen-UI#316]
I base on `Meteor + Vue`.
I would like to try `Keen UI`, have own form validate or not???
Please help me.

**Comment by Christilut** [comment]
No, but try using Vuelidate or Vee-validate. Both are quite good but slightly different approach.

**Comment by thearabbit** [comment]
thanks for you reply.
could you example how to integrate with [Vee-Validte](https://github.com/logaretm/vee-validate)?
Bc I am a newbie with `Vue`.

**Comment by Christilut** [comment]
Just follow the Vee-validate example and instead of `input`, use `ui-input`. That should work the same.

Start with building a working validation without KeenUI, then add KeenUI

**Comment by thearabbit** [comment]
Thanks I will try.
