### ISSUE TITLE
Unexpected token: name (KeenUiConfig)

### ISSUE THREAD

**Issue by matheusgrieger** [JosephusPaye/Keen-UI#319]
Hello, I'm getting this error every time I try to build for production (development environment works).

I'm currently using Vue's Webpack template, with minor adjustments such as config folder changed location. Everything works, except for this error, which I have no idea what is going on.

Do you need any code to see what I'm doing? If so, please tell me and I'll paste here. The full error is shown below:

```
ERROR in static/js/vendor.be1996015b469dd732b1.js from UglifyJs
Unexpected token: name (KeenUiConfig) [./~/keen-ui/src/config.js:56,0][static/js/vendor.be1996015b469dd732b1.js:8221,6]
```

Thank you!

**Comment by patrin** [comment]
Same issue.
@matheusgrieger did you work this problem out?

**Comment by matheusgrieger** [comment]
@patrin no, wasn't able to. Removing it creates other errors.

**Comment by lucassmacedo** [comment]
Same problem...

**Comment by lucassmacedo** [comment]
@matheusgrieger @patrin have a solution?

**Comment by JosephusPaye** [comment]
See this issue: https://github.com/JosephusPaye/Keen-UI/issues/295

**Comment by deini** [comment]
I had to add this using vue-cli webpack template:

in `webpack.base.conf.js`
```
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/keen-ui/src')],
      },
```

Which IMO we shouldn't have to do this, but /shrug

**Comment by JosephusPaye** [comment]
Closing now, as this is not a Keen UI issue and there are solutions. @deini's workaround ([the comment above](https://github.com/JosephusPaye/Keen-UI/issues/319#issuecomment-311551779)) is good.
