### ISSUE TITLE
v-model deep properties not working

### ISSUE THREAD

**Issue by Christilut** [JosephusPaye/Keen-UI#321]
See https://jsfiddle.net/xwhjrt16/
Try to type text in the textbox, it will reset to empty.

This also affects UiDatepicker.
Regular `input` elements work fine.

This is actually fairly important that it works because any dynamically built UI will need to use a property on an object as model. The only workaround I see for this is to manually listen for the change event and update properties accordingly, but using v-model is greatly preferred.

**Comment by KrishnaPG** [comment]
Looks like there is some syntax mistake in the code. Tried to update it and looks like it is working fine - please check: https://jsfiddle.net/KrishnaPG/xwhjrt16/1/ if this is what you are after

**Comment by Christilut** [comment]
You're right, there was a mistake in the fiddle. My normal usecase for this is a bit more complex and I thought I had recreated it :) I'll make another fiddle (hopefully) tomorrow and double check it this time.

**Comment by Christilut** [comment]
Ah I think I fixed it.

Problem was using `this.content[lang] = {}` instead of `this.$set{this.content, lang, {}`. Twice :|

See https://jsfiddle.net/s0061xha/2/

Reason I thought it was KeenUi is that `ui-textbox` resets back to empty string (previous value) if model couldnt be updated where as `input` keeps the text even though nothing was updated.

Thanks!

**Comment by zolotykh** [comment]
Hi. I also have same issue.
I have `cfg` object with key-values.

```js
data(){
            return {
                loading: false,
                cfg: {},
            };
        },
mounted(){
this.$req('get').done(res => {
                    this.cfg = Object.assign({}, this.cfg, res.cfg);
                });
}
```

```html
<ui-textbox :invalid="!cfg.title" label="Title"
                    :value.sync="cfg.title"></ui-textbox>
```

What it does:
1. It doesn't apply value to `value` attribute
2. It clears `value` attribute after blur event

So, what I'm doing wrong?

`vue@2.3.4` & `keen-ui@1.0.0`
