### ISSUE TITLE
Can't customize primary and accent colors

### ISSUE THREAD

**Issue by EAdonyaeva** [JosephusPaye/Keen-UI#323]
Hi! I try to customize accent and primary colors in my project according instruction - https://github.com/JosephusPaye/Keen-UI/blob/master/Customization.md
But colors haven't changed. I created new empty vue cli webpack simple project and try to change colors on it - https://github.com/EAdonyaeva/keen-project
But I've no luck. What am I doing wrong?

**Comment by sorincom** [comment]
Hi, had the same problem and solved it by removing the import of compiled css, besides following the customization instructions:

import 'keen-ui/dist/keen-ui.css'

**Comment by JosephusPaye** [comment]
@EAdonyaeva Re-open if this is still an issue.
