### ISSUE TITLE
how to use css when using vue modules?

### ISSUE THREAD

**Issue by KrishnaPG** [JosephusPaye/Keen-UI#324]
Thanks for the components - they are helpful.

Trying to use them inside a vue-loader based webpack sample application. Following the documentation, doing something as below inside a custom `.vue` template file:
````
<template>
	<UiSelect v-model="datasource[datapath]" :options='fieldSchema.options'></UiSelect>
</template>
<script>
	import { UiTextbox , UiSelect } from 'keen-ui';
	export default {
		components: {
			UiTextbox, UiSelect
		},
		props: { ...
		},
       }
</script>
````
Keen components are getting loaded, but they do not look good. Their styling is way off.

I was expecting that the styling is part of these components and when importing the keen components using the `import` statement they come with their own style packed inside them - is that correct? or should we manually include additional style files ?

**Comment by JosephusPaye** [comment]
The styles have been extracted into a separate file, and you can import them 2 ways:

1. From your `<script>` block:

```js
import 'keen-ui/dist/keen-ui.css';
```

2. From your `<style>` block (if using Sass):

```scss
@import '~keen-ui/dist/keen-ui.css';
```

If you want to import the components and get their styles as well, import from the `src/` folder:

```js
import UiButton from 'keen-ui/src/UiButton.vue';
```

This will import the button component with the styles in-lined.

**Comment by KrishnaPG** [comment]
Thanks @JosephusPaye
