### ISSUE TITLE
Developing stopped? 😦

### ISSUE THREAD

**Issue by rorc** [JosephusPaye/Keen-UI#326]
Last commit was 3 months ago 😟

**Comment by JosephusPaye** [comment]
No, development has not stopped. Version 1.1 is in development.

**Comment by Christilut** [comment]
@JosephusPaye maybe an idea to put up a kanban board (under Projects) so its transparent what the status of 1.1 is. Even if you're working hard, we don't really see that and that scares new adopters.

Transparency might prevent things like [this](https://github.com/vuematerial/vue-material/issues/598) from happening

**Comment by xlhl77** [comment]
+1
