### ISSUE TITLE
Tab indicator doesn't work inside modal

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#328]
If you put tabs to modal, initially tab indicator (line) doesn't show up. It shows only if you resize window. @JosephusPaye

**Comment by nelsonpecora** [comment]
I'm seeing the same thing (in a non-keen-ui modal I made). It looks like something's erroniously calculating the `right` value of `.ui-tabs__active-tab-indicator`

![screen shot 2017-09-28 at 5 37 21 pm](https://user-images.githubusercontent.com/447522/30991630-cecca2ac-a473-11e7-8045-0bdc1d82eab4.png)

**Comment by JosephusPaye** [comment]
This is fixed in the new version, which doesn't depend on the window size to correctly display the selected tab indicator.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
