### ISSUE TITLE
UiButton loading glitch

### ISSUE THREAD

**Issue by brickgale** [JosephusPaye/Keen-UI#329]
I'm not sure why but the loading part doesn't stop, after it changed immediately after processing the api. 
<a href="https://gyazo.com/4e55886bf8792e564f8c0e1c5f58340f"><img src="https://i.gyazo.com/4e55886bf8792e564f8c0e1c5f58340f.gif" alt="https://gyazo.com/4e55886bf8792e564f8c0e1c5f58340f" width="322"/></a>

**Comment by JosephusPaye** [comment]
Hi @brickgale,

Can't see the gif as it's now a 404.

Closing for now. Reopen if this is still a problem.
