### ISSUE TITLE
data-tables

### ISSUE THREAD

**Issue by xiaolongyuan** [JosephusPaye/Keen-UI#33]
https://www.google.com/design/spec/components/data-tables.html

**Comment by JosephusPaye** [comment]
Unfortunately, at the moment I have no plans for adding data tables to Keen UI.

**Comment by EmilMoe** [comment]
It's already been made by **ratiw**:

https://laracasts.com/discuss/channels/vue/vuejs-table-component

**Comment by JosephusPaye** [comment]
Closed for now.

**Comment by thearabbit** [comment]
+1
