### ISSUE TITLE
v1.0.0 UiSelect API error 

### ISSUE THREAD

**Issue by g8up** [JosephusPaye/Keen-UI#331]
https://josephuspaye.github.io/Keen-UI/#/ui-select
```
For an array of objects, the label is shown to the user and is used for filtering, and the value is submitted to the server. You can redefine these keys to fit your data using the keys prop.
```
API - options: config in keys:  `label` should be `text`

**Comment by JosephusPaye** [comment]
Hi @g8up,

It seems like the `label` is actually correct and not `text`. See below:

https://github.com/JosephusPaye/Keen-UI/blob/1ce10722d27bc6f82e229fe87bafdda76764a0d7/src/UiSelect.vue#L309-L311

Perhaps the issue is something else?
