### ISSUE TITLE
UiConfirm button animation issue

### ISSUE THREAD

**Issue by thdoan** [JosephusPaye/Keen-UI#333]
Steps to reproduce:

1. Go to https://josephuspaye.github.io/Keen-UI/#/ui-confirm
2. Click on BASIC CONFIRM

I'm seeing this in Chrome 58.0.3029.110 (64-bit) on Windows 10 Pro:

![keen_ui](https://cloud.githubusercontent.com/assets/4110567/26285717/9fdba29c-3e87-11e7-830b-2d0f5e1c807b.gif)

It seems like the buttons stop animating prematurely.

**Comment by JosephusPaye** [comment]
See https://github.com/JosephusPaye/Keen-UI/issues/205.
