### ISSUE TITLE
Error using KeenUI on laravel

### ISSUE THREAD

**Issue by YnievesDotNet** [JosephusPaye/Keen-UI#334]
Hello everyall

I try using in Laravel, with Vue and Keen-UI, and I passed initially the login form, but, when I entry the login data, and change the focus to password field, the email box is reseted, and I can send the for, because all fields are empty.

```
<ui-textbox type="email" name="email" required label="Email"></ui-textbox>
<ui-textbox type="password" name="password" required label="Password"></ui-textbox>
```

Thanks
YnievesDotNet

**Comment by brickgale** [comment]
you should really use the model binding for ui-textbox. like `<ui-textbox type="password" :value.sync="password"` which you will have `password` inside your data.
