### ISSUE TITLE
ui-select is not accepting raw html as label

### ISSUE THREAD

**Issue by rohanil** [JosephusPaye/Keen-UI#337]
I am using `ui-select` component from library. I am trying to use `v-html` attribute but it is somehow not working as expected. I have following code inside template:

      <template>
      <ui-select
                label="Color"
                placeholder="Color"
                :options="SelectColors"
                v-model="color"
                v-html="red"
            ></ui-select>
     </template>
    
     <script>
    import { UiSelect } from 'keen-ui'
    export default {
       data () {
          red: '<div class="foo red"></div>',
          SelectColours: [
        {
          label: this.red,
          value: 'red'
        }]
       },
       components: { UiSelect }
    }
    
    <style>
    .foo {
      float: left;
      width: 20px;
      height: 20px;
      margin: 5px;
      border: 1px solid rgba(0, 0, 0, .2);
    }
    
    .red {
      background: red;
    }
    </style>

I am expecting it to show select option with only red color box but it does not show anything. Any idea why it is not working as I expect?

**Comment by thorning** [comment]
I just started using this library, so I might be wrong, but I don't think this is possible. It would be really nice if we could use a slot for the display value, similar to the option slot.

My solution was to set `opacity 0` for `.ui-select__display`, and then make an absolute positioned element with `pointer-events: none` which shows the current selection.

**Comment by rohanil** [comment]
I could achieve it using own custom template inside ui-select element.
