### ISSUE TITLE
How to clear ui select value in remote search case?

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#338]
In the example of remote search for ui-select, after we selected a value, how can we clear the input?

**Comment by JosephusPaye** [comment]
Added a new method `clearQuery` to clear the current query. https://github.com/JosephusPaye/Keen-UI/commit/38c637a95619d21073e55ffee694202eac801588

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
