### ISSUE TITLE
Uncaught TypeError:  Cannot read property 'contains' of undefined

### ISSUE THREAD

**Issue by pavinthan** [JosephusPaye/Keen-UI#341]
Cannot read property 'contains' of undefined
    at a.restrictFocus (keen-ui.min.js:14)
    at HTMLDocument.n (vue.min.js:6)

restrictFocus: function(t) {
                    this.$refs.container.contains(t.target) || (t.stopPropagation(),
                    this.$refs.container.focus())
                },

**Comment by JosephusPaye** [comment]
Possible duplicate of https://github.com/JosephusPaye/Keen-UI/issues/318.
