### ISSUE TITLE
Side menu is over header menu

### ISSUE THREAD

**Issue by prsolucoes** [JosephusPaye/Keen-UI#343]
Hi,

Im testing on mac latest version / chrome latest version.

The home of demo show problems on side menu, it is over the header menu.

Image:
<img width="626" alt="screenshot 2017-07-08 02 57 55" src="https://user-images.githubusercontent.com/395096/27983023-65ee4004-6389-11e7-97d3-af01b8997bf0.png">

**Comment by prsolucoes** [comment]
Inspecting it, i see that the padding can solve to mac, but i dont know if it works on others.

Set the padding for menu header:
<img width="297" alt="screenshot 2017-07-08 03 03 57" src="https://user-images.githubusercontent.com/395096/27983061-4127dd92-638a-11e7-9f7d-dc84f24c8b38.png">

**Comment by JosephusPaye** [comment]
Hi @prsolucoes,

Thanks for the heads up, this is fixed on `next`. Will be deployed soon.
