### ISSUE TITLE
refreshHeight and IE

### ISSUE THREAD

**Issue by Ozymandy** [JosephusPaye/Keen-UI#344]
When I call refreshHeight from UICollapsible in IE it doesn't work. Only in Chrome and Firefox

**Comment by JosephusPaye** [comment]
Could you make an online demo that runs in Chrome/Firefox but shows the issue in IE? Here's a Codepen template already setup with Keen UI and Vue: https://codepen.io/pen?template=oBpKEr

**Comment by JosephusPaye** [comment]
With https://github.com/JosephusPaye/Keen-UI/commit/435677b1bb8f3fef5c78cf048d05f42b6286823a `refreshHeight()` is no longer needed and has been removed.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
