### ISSUE TITLE
Styling CSS via Sass customization

### ISSUE THREAD

**Issue by jameswragg** [JosephusPaye/Keen-UI#346]
The Keen-UI components are great, thanks for all your hard work in building this collection!

My issue - do you have clearer docs, or direction on integrating my scss, the Keen-UI component scss while changing the Keen-UI brand colours? I'm trying to follow the [Sass customization](https://github.com/JosephusPaye/Keen-UI/blob/master/Customization.md) guide to change the branding colour variables to suit my project but it's not clear.

I'm trying to apply this to my Vue project created via the vue-cli webpack template. I have attempted updating the [`webpack.config.js`, `sass-loader`, `node-sass`] configurations to pass in the variables as mentioned in the guide with no luck.

The only way I've been able to get styling to work correctly is to include the pre-build `keen-ui.css` in my project.

This is my `main.js`

```import 'keen-ui/dist/keen-ui.css';

import Vue from 'vue';
import KeenUI from 'keen-ui';
import App from './App';

Vue.use(KeenUI);

/* eslint-disable no-new */
new Vue({
  name: 'Widget',
  el: '#app',
  template: '<App/>',
  components: { App },
});
```

Then in my component I use the `ui-popover` and `ui-menu` components:

```
<template>
  <div class="compose">
        <a class="chat-compose__questions-button" ref="dropdownTrigger" tabindex="0">Menu</a>
        <ui-popover trigger="dropdownTrigger" ref="dropdown">
          <ui-menu contain-focus :options="menuOptions" @close="$refs.dropdown.close()" @select="askCannedQuestion"></ui-menu>
        </ui-popover>
  </div>
</template>

<script>
</script>

<style lang="scss">
.compose {
  background-color: $brand-secondary;
}
</style>

```

I would like to have the Keen-UI Scss built at runtime/build with my project Scss.

Thanks,
James

**Comment by JosephusPaye** [comment]
Hi @jameswragg,

If you still have this issue, I've re-written the Sass customization guide to be clearer, see: 

https://github.com/JosephusPaye/Keen-UI/blob/next/Customization.md

Closing this issue now, leave a comment if you have a problem.
