### ISSUE TITLE
Dynamically removing UiTab from UiTabs

### ISSUE THREAD

**Issue by MildlyObscure** [JosephusPaye/Keen-UI#349]
<ui-tabs 
      type="icon-and-text"
      ref="workspaceTabs"
      @tab-change="tabChange">
      <template v-for="element in elementDetails">         
        <ui-tab 
          :id="element.uid"
          class="elementTab"
          :title = "element.element.name || '(New)'"
          :icon = "element.element.icon"
          <component 
            v-bind:is="element.element.componentName" 
            :element="element.element"
            ref="component"
            @close="closeTab"
            ></component>
        </ui-tab>
      </template>
      <ui-tab 
        title = "Welcome!"
        icon = "help_outline">
        <h2>Pretend this is helpful!</h2>
      </ui-tab>
    </ui-tabs>

1. When a new element is added to elementDetails, a new tab is (almost) properly added to the UiTabs. However, when an element is *removed* from ElementDetails (using splice), the tab is removed, but the tab header is not. It would seem that both should be removed - unless I'm doing it wrong, in which case neither should be removed (and I would appreciate a tip on how to do it right).

2. There seems to be some inconsistency in that adding new elements to elementDetails *sometimes* results in the new tabs appearing *after* the "Welcome!" tab. However, I'm not sure this ever happens except after a hot reload. I'm only mentioning it here in case it is somehow related to the main issue. If I can confirm that this actually happens, I'll submit a new issue.

Thanks! Overall I'm liking the look of keen-ui (with a few quibbles, most of which I can fix with custom CSS) and its ease of use.

**Comment by salamaashoush** [comment]
i have the same issue, any solution please

**Comment by NovikovRoman** [comment]
in the closeTab method at the end ```this.$forceUpdate();```
helped?

**Comment by JosephusPaye** [comment]
Hi @MildlyObscure,
 
UiTab and UiTabs were re-written in https://github.com/JosephusPaye/Keen-UI/commit/1718aec948d44f411db51f93a5a9960db1c8a0d7 to work with `v-for`, this is shown in the new docs.
