### ISSUE TITLE
Sidenav touch on mobile not working

### ISSUE THREAD

**Issue by breadlesscode** [JosephusPaye/Keen-UI#35]
Hi,

at first: great project! ! ! 

On my Android 6 mobile phone, with chrome browser, I cant change the page via sidenav.

**Comment by JosephusPaye** [comment]
It works on my Nexus 4 with latest Chrome. It also works fine using the Chrome Devtools mobile emulator.

Since I don't have access to the device you are referring to, it's hard to know what's happening to write a fix.
