### ISSUE TITLE
How to use method reset() in auto-complete component 

### ISSUE THREAD

**Issue by reo4** [JosephusPaye/Keen-UI#351]
i want to reset the input field but give undefined method

methods:{
			memberSelected(selected){
				if (! _.some(this.members, ['_id' , selected._id]) ) {
					this.members.push(selected)
					this.query = ""
				}
				else{
					reset()
				}
			},
		}

**Comment by GranJDev** [comment]
You need a ref on the component to be able to call the reset method.


```
<template>
<ui-auto-complete ref="autocompleteComponent"></ui-auto-complete>
</template>
<script>
...
resetComponent() {
     this.$refs.autocompleteComponent.reset()
}
</script>
```

**Comment by reo4** [comment]
thanks

**Comment by JosephusPaye** [comment]
Closing now, since it seems to be resolved.
