### ISSUE TITLE
Validation UiTextbox like version 0.8

### ISSUE THREAD

**Issue by yeknava** [JosephusPaye/Keen-UI#358]
Im porting my app from vue 1 to vue 2 and so keen-ui 0.8 to 1. but what i really miss from version 0.8 is validation messages. it supports different languages and it triggers automatically.
but now i need to listen on 'blur' or 'touch' event on every textbox, specify rules separately, and generate error for each rule and combine them to show.

ex. case: i have a textbox that is required and should be 10 character at least. when you have multiple rules you should listen on input and check which error or errors should trigger.

why things get so harder and is there any way to bring that back ?

**Comment by EmilMoe** [comment]
@yeknava I have used veeValidation http://vee-validate.logaretm.com, that has worked really well for me.
