### ISSUE TITLE
How to attach a dropdown menu to UiToolbar's navicon?

### ISSUE THREAD

**Issue by Handsome2734** [JosephusPaye/Keen-UI#36]
Newbie on vuejs here, may need some help.

Expected:
click the navicon, a dropdown menu show's on the bottom right of it.

**Comment by enriquezafra** [comment]
`<ui-icon-button
                type = "clear"
                color = "black"
                icon = "person_outline"
                has-dropdown-menu
                :menu-options = "[ {id:'1', text: 'Settings'} ]"
                dropdown-position = "bottom right"
                open-dropdown-on = "hover"
                >`

**Comment by JosephusPaye** [comment]
Currently it's not possible to add a menu to UiToolbar's default navicon. However, you can use the brand slot to add a UiIconButton which contains a dropdown.

Example:

```html
<ui-toolbar show-brand hide-nav-icon :show-brand-divider="false">
    <div slot="brand">
        <ui-icon-button type="clear" color="black" icon="menu" has-dropdown-menu :menu-options="menu" dropdown-position="bottom left"></ui-icon-button>
    </div>
</ui-toolbar>
```

See a [demo here](http://codepen.io/JosephusPaye/pen/NrKwEV)

**Comment by Handsome2734** [comment]
@JosephusPaye Kinda tricky but it really works! Thanks!

**Comment by JosephusPaye** [comment]
Glad it helped. Closing this issue for now.

**Comment by mariaczi** [comment]
@JosephusPaye so basically the default menu icon in toolbar is useless ? Are you going to do something with that?
