### ISSUE TITLE
demo-site UiConfirm issue

### ISSUE THREAD

**Issue by z1haze** [JosephusPaye/Keen-UI#362]
On your demo site, when opening the uiconfirm dialogs, the button click animation for the  cancel/ok buttons is stuck mid animation by default. I havent used this lib yet so I cant confirm its an issue in the library, but while looking at the lib I noticed this. Great looking set of UI components though!

**Comment by JosephusPaye** [comment]
Hi @z1haze,

See https://github.com/JosephusPaye/Keen-UI/issues/205.
