### ISSUE TITLE
KeenUI 0.8.9 UiPopover wrong location with v-for

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#364]
With this snippet below the UiPopover is always attached far up on the page. Is there a way to fix that? I suspect the `v-for` to be the problem here?

~~~~
            <tbody v-for="(index, group) in groups">
                    <tr>
                        <td>
                            <strong
                                    v-el:popover
                                    style="cursor: pointer;">
                                Title
                            </strong>
                            <ui-popover
                                    :trigger="$els.popover">
                                Content
                            </ui-popover>
~~~~

**Comment by JosephusPaye** [comment]
It's probably something related to `v-for`. Could you post a demo?

Here's a Codepen template setup with Vue and Keen UI: https://codepen.io/JosephusPaye/pen/NrKmPQ.

**Comment by EmilMoe** [comment]
Sorry I found another solution :-) Let's put the energy on the newest version instead.
