### ISSUE TITLE
Have no idea how to change colors. Help!!!

### ISSUE THREAD

**Issue by ghost** [JosephusPaye/Keen-UI#366]
I had read the customization guide and I don't understand.

```
new webpack.LoaderOptionsPlugin({
            options: {
                sassLoader: {
                    data: '@import "src/styles/variables.scss";',
                    includePaths: 'src/styles'
                },
                context: path.resolve(__dirname) // your project root
            }
        })
```
What do you mean with `your project root?` is my `dist` directory?

What `data` property is? 

Do I need to create a file called `src/styles/variables.scss`? if so, where? and it has to be in that exact location? or do I need first overridden whatever color from `node_modules/keen-ui/src/styles/variables.scss`? I am not sure wheter I need to create these file or overridden the color directly?  

I am not using `scss` and I don't know how to use it, 

Do I need install `node-sass`? if so, what do I need to do with it?

Do I need any `loader`?

Can you explain it a bit more detail, I just need to change the `$brand-accent-color` but I have no clue what to do.

**Comment by JosephusPaye** [comment]
Hi @AAhrit,

There's a more straight-forward way to do it using [`sass-resources-loader`](https://github.com/shakacode/sass-resources-loader):

First, you need `webpack`, [`vue-loader`](https://github.com/vuejs/vue-loader) and `node-sass`, setup and configured. If you don't have a project already, you can start with [`vue-cli`](https://github.com/vuejs/vue-cli).

Next, create a `variables.scss` file (anywhere in your project `src` folder). In this file, add and change the variables from Keen UI that you want to override.

```scss
// variables.scss
$brand-accent-color: red;
```

Now follow the instructions here to load your `variables.scss` file: https://vue-loader.vuejs.org/en/configurations/pre-processors.html#loading-a-global-settings-file.

When loaded, this will override the variables in Keen UI. For this to work you need to import any Keen UI component you're using using this method:

```js
import UiButton from 'keen-ui/src/UiButton';
```

Note the import from `keen-ui/src/...`. This will import and build the components from source, allowing the variables to be overriden.

**Comment by JosephusPaye** [comment]
Closing for now. Create a new issue if you have further questions.
