### ISSUE TITLE
UISelect help slot not displaying without also setting the help prop

### ISSUE THREAD

**Issue by olsgreen** [JosephusPaye/Keen-UI#369]
Doesn't work, but should:

    <ui-select>
        <div slot="help">My help text</div>
    </ui-select>

Works at the moment:

    <ui-select help="abc">
        <div slot="help">My help text</div>
    </ui-select>

Fixed in accompanying pull.

**Comment by waratah** [comment]
https://github.com/JosephusPaye/Keen-UI/blob/next/CHANGELOG.md

It appears to be fixed in the next branch.
