### ISSUE TITLE
IE11 uiTextbox multiLine

### ISSUE THREAD

**Issue by LuisPinero** [JosephusPaye/Keen-UI#371]
# Problem
I detected a problem in IE11 using uiTextbox with multiLine property. IE11 show the following error:
`[Vue warn]: Error in nextTick: "Error: Argumento no válido."
Error: Argumento no válido.
   {
      [functions]: ,
      __proto__: { },
      description: "Argumento no válido.",
      message: "Argumento no válido.",
      name: "Error",
      number: -2147024809,
      stack: "Error: Argumento no válido.
   at setTextContent (eval code:5203:3)
   at patchVnode (eval code:5746:7)
   at updateChildren (eval code:5633:9)
   at patchVnode (eval code:5736:29)
   at updateChildren (eval code:5633:9)
   at patchVnode (eval code:5736:29)
   at updateChildren (eval code:5633:9)
   at patchVnode (eval code:5736:29)
   at updateChildren (eval code:5633:9)
   at patchVnode (eval code:5736:29)",
      Symbol()_n.4zqe0lroeml: undefined,
      Symbol()_o.4zqe0lroeml: undefined,
      Symbol()_p.4zqe0lroeml: undefined,
      Symbol(react.element)_m.4zqe0lroeml: undefined
   }
`
# Posible solution
Remove {{value}} from 
`             <textarea
...
                    v-else
                >{{ value }}</textarea>`

As it is said on [Vue Documentation](https://vuejs.org/v2/guide/forms.html#Multiline-text):

> Interpolation on textareas (<textarea>{{text}}</textarea>) won't work. Use v-model instead.

**Comment by eduardosada** [comment]
I have the same problem 😕

**Comment by liammcsheffrey** [comment]
+1 having IE11 issues on textareas
