### ISSUE TITLE
UISelect within a UIModal overflow issues

### ISSUE THREAD

**Issue by olsgreen** [JosephusPaye/Keen-UI#375]
As the title suggests, my issue is with select drop down items becoming obscured when the control is placed within a modal, an example below:

![us-select-small](https://user-images.githubusercontent.com/1324164/32849674-c22ac16c-ca27-11e7-9a98-cc214f9171c9.jpg)

The modal does allow the user to scroll the modal body to reveal the remaining options, but then they must scroll the list of items as well. It all adds up to become a bit of a usability nightmare.

One option may be to get the component to open the dropdown upwards in some cases, another option would be to move the drop down element outside of the modal body (somewhere, somehow) so that it wasn't affected by the bodys overflow property and tether it back to the component. 

Has anyone else come up against this issue? Thoughts / ideas?

**Comment by JosephusPaye** [comment]
Hi @olsgreen,

This is a problem I've faced too and I'm currently working on a solution for the next release that will support nested modals, dropdowns and dropdowns in modals. It'll allow you to choose for the dropdown to fall outside of the modal body, like so:

![image](https://user-images.githubusercontent.com/5924865/32861425-b68fc132-caa8-11e7-86d0-75646e0cd03a.png)

This is not ready yet, though and I'm not sure what can be done for now.

**Comment by olsgreen** [comment]
Great news! I'm thinking of extending the existing component to use tether or something like that.

Any ideas on a rough release date?

**Comment by fourpixels** [comment]
Any news? :)

**Comment by JosephusPaye** [comment]
No news on a release date yet, but if you're feeling adventurous, you can try out the `next` branch. It should be stable - I'm using it in another project and haven't any found critical issues so far.

Add this to your `package.json` and run `yarn upgrade keen-ui`:

```
"keen-ui": "JosephusPaye/Keen-UI.git#next"
```

If you do use `next`, make sure to check the [CHANGELOG](https://github.com/JosephusPaye/Keen-UI/blob/next/CHANGELOG.md) for breaking changes, and report any issues you find.

**Comment by fourpixels** [comment]
Unfortunately I need this for work, not for adventure :) It would be great if there are often and important releases rather than huge changes in rare occasions.

Thanks

**Comment by JosephusPaye** [comment]
I would like that too, and ideally we would have regular releases. But I just don't have the time to do so.

That said, `next` is relatively stable and is what I use in all my projects, including ones that are in production, used by customers daily.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
