### ISSUE TITLE
ui autocomplete - unable to stop second service call

### ISSUE THREAD

**Issue by waratah** [JosephusPaye/Keen-UI#376]
I am handling input and selection in code however the timing of the calls means I cannot stop a second call the service when I handle input...

```vue
<ui-autocomplete class="full" :class="{ 'is-loading': showProgress }" :label="label" name="address" :placeholder="label" iconPosition="right"
        floating-label :suggestions="addresses" :filter='filter' :keys="{ label: 'text', value: 'text' }" :min-chars="1" v-model="search"
        @select="selectCallback($event)" @input="handleInput" @focus='Touched' @touch="Touched">
```
       
I would like to be able to set a boolean flag in selectCallBack and then check it in handleInput and stop processing to load data from a service call.   Unfortunately I get handleInput followed be selectCallBack which means I cannot distinguish between a select change and a normal text entry.   This means I have to call the web service which slows my application.

Other solution is to NOT call input when a selection is called, this may be a bad idea.

See documentation ticket for more details on the code.   I hope explanation is enough.

**Comment by JosephusPaye** [comment]
Hi @waratah,

Thinking about this now, how did you end up handling it?

One way could be setting a timer on `@input` and only making the request if there's no `@select` before the timer expires.

```vue
<template>
	<div>
		<ui-autocomplete :suggestions="mySuggestions" v-model="search" @input="handleInput" @select="handleSelect">My Autocomplete</ui-autocomplete>
	</div>
</template>

<script>
export default {
	data() {
		return {
			suggestions: [],
			requestTimer: null
		};
	},

	methods: {
		handleInput(value) {
			if (this.requestTimer) {
				clearTimeout(this.requestTimer);
			}

			this.requestTimer = setTimeout(() => {
				this.makeRequest(value), 
			}, 50);
		},

		handleSelect(suggestion) {
			if (this.requestTimer) {
				clearTimeout(this.requestTimer);
			}

			// Do other things
		},

		makeRequest(value) {
			// Make the request and set suggestions here
		}
	}
}
```

**Comment by waratah** [comment]
Status is still awaiting inspiration.

Pretty much I accepted the extra call,  I would rather be smarter.    Back end returns the duplicate call faster so it is not that bad.

App has been live now for a few months with only minor bugs.   Good work on the framework,   lucky someone recommended it to me.

**Comment by JosephusPaye** [comment]
Closing for now. Please reopen if this is still an issue.
