### ISSUE TITLE
How to set focus on control?

### ISSUE THREAD

**Issue by saknarak** [JosephusPaye/Keen-UI#38]
How do I set focus on UiTextbox or UiButton or any focusable control?

**Comment by saknarak** [comment]
OK I found the solution

<ui-textbox id="myid">

ready() {
  let el = this.$el.querySelector('#myid');
  el.focus()
}

Add autofocus attribute into <input> would be great.

**Comment by JosephusPaye** [comment]
An `autofocus` prop will be added to UiTextbox and UiAutocomplete in the next release.

**Comment by JosephusPaye** [comment]
New `autofocus` prop now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9), for both [UiAutocomplete](https://josephuspaye.github.io/Keen-UI/#/ui-autocomplete-docs) and [UiTextbox](https://josephuspaye.github.io/Keen-UI/#/ui-textbox-docs).
