### ISSUE TITLE
Feature: UISidenav

### ISSUE THREAD

**Issue by natxocc** [JosephusPaye/Keen-UI#381]
Is it possible to include a component like you have in Docs?
It's very useful to have a Sidenav menu. I see that it is possible to try to use the same you have in docs, but a very "how to" would be very interesting.

Thanks!

**Comment by EmilMoe** [comment]
Sounds like a different project to me. You could also easily extract it from source code. There's no JS magic in the sidebar only HTML and CSS.

**Comment by JosephusPaye** [comment]
Hi @natxocc,

A sidebar nav is a bit out of scope for Keen UI: the focused is on creating components that require Javascript.

This is the reason why we don't have components like cards.
