### ISSUE TITLE
Event source of UITextboxes and others similar components

### ISSUE THREAD

**Issue by wdacgrs** [JosephusPaye/Keen-UI#384]
Currently, @input and others for UITextbox and etc. only pass the new value to the event handler.
In my use case, I would like to use a single event handler for multiple UITextboxes, but as there are no information passed into the event handler, I could not find out which UITextbox triggered the event.

**Comment by EmilMoe** [comment]
I don't really understand your question?

**Comment by JosephusPaye** [comment]
@EmilMoe,

I think what he means is having a single method for handling the `@input` event of multiple textboxes, but also being able to tell, in the handler, which one of the textboxes triggered the event. 

@wdacgrs,

If you still need to do this, see this Codepen: https://codepen.io/JosephusPaye/pen/yKNjWv?editors=1000
