### ISSUE TITLE
ui-textbox float-label doesn't work

### ISSUE THREAD

**Issue by MaximeScibetta** [JosephusPaye/Keen-UI#387]
I use this 
```
<ui-textbox
                floating-label
                label="Name"
                placeholder="Enter your name"

                v-model="textbox2"
        ></ui-textbox>
``` 
but my label is already on top like this
https://puu.sh/yUKAb/3fc3952613.png

**Comment by JosephusPaye** [comment]
Make sure your `textbox2` model string is empty (i.e. the length is 0), if not the label will appear on top, since there's something in the textbox.

See: https://codepen.io/JosephusPaye/pen/goXrRw
