### ISSUE TITLE
Bug. UiCollapsible refreshHeight() + IE 11

### ISSUE THREAD

**Issue by gabdsh** [JosephusPaye/Keen-UI#389]
Hi,
UiCollapsible refreshHeight() not work in IE, but work in chrome.

Example
https://codepen.io/anon/pen/BYpjLX

**Comment by JosephusPaye** [comment]
The collapsible has been written (https://github.com/JosephusPaye/Keen-UI/commit/435677b1bb8f3fef5c78cf048d05f42b6286823a) and `refreshHeight` is no longer needed, and has been removed.

The height should now be calculated automatically.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
