### ISSUE TITLE
Submit Button

### ISSUE THREAD

**Issue by pdellepiane** [JosephusPaye/Keen-UI#39]
How can I add a submit button?

**Comment by gdepourtales** [comment]
Hi, you can have a look at the source of the documentation of UIButton here : https://github.com/JosephusPaye/Keen-UI/blob/master/src-docs/components/UiButtonDocs.vue 

Keen-UI uses standard vue.js event handling. In the source of documentation, you should find many examples linked with actions such as :

```
<div class="group">
    <ui-button @click="stopSpinners">Stop spinners</ui-button>
</div>
```

Hope it helps

**Comment by JosephusPaye** [comment]
Yeah, what @gdepourtales said. Also see #43. Closing this issue for now, reopen if you still need help.
