### ISSUE TITLE
Ui-datepicker close programatically

### ISSUE THREAD

**Issue by angrykoala** [JosephusPaye/Keen-UI#399]
I'm trying to close a [datepicker](https://josephuspaye.github.io/Keen-UI/#/ui-datepicker) popup when the user press the Esc key. I cannot find any method or way to achieve this programatically.

**Comment by JosephusPaye** [comment]
Hi @angrykoala,

You can add a `ref` and then call `.closePicker()`:

```vue
<ui-datepicker ref="myPicker" placeholder="Select a date" v-model="date">Birthday</ui-datepicker>
```

```js
mounted() {
	// Open the date picker
	this.$refs.myPicker.openPicker();

	// Close the date picker
	this.$refs.myPicker.closePicker();

	// Close the date picker, and remove keyboard focus
	this.$refs.myPicker.closePicker({ autoBlur: true });
}
```

**Comment by angrykoala** [comment]
Thanks, as a note, this doesn't seem to be documented (or at least I couldn't find at https://josephuspaye.github.io/Keen-UI/#/ui-datepicker)
