### ISSUE TITLE
UiModal larger size

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#401]
I would like a even larger modal option. Right now I have this 

```
.ui-modal--size-big {
  .ui-modal__container {
    width: 70%;
  }
}
```

You can call it `extra-large` or `big` or something else, but the large one can be a bit small when you want to fit a form into it.

**Comment by JosephusPaye** [comment]
Hi @EmilMoe,

This is actually the preferred way to add new sizes. I do the same in my own projects.

For the benefit of others, whatever `size` prop you pass to the modal will be added as a class in the format `.ui-modal--size-{your-size}`.

Using CSS, you can then customize the modal size like @EmilMoe did above. A width of `100%` on `.ui-modal__container` will make it as wide as the browser viewport.

**Comment by EmilMoe** [comment]
It's a solution yes, but your component uses a different suffix though, but I guess it's alright.

**Comment by JosephusPaye** [comment]
Yeah, I keep all Keen UI-related CSS and overrides in a one file, where all the prefixes are `.ui-`.

This keeps it separate from the project-specific styles and makes it easier to modify and update when there are updates to Keen UI.
