### ISSUE TITLE
UiAlert

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#402]
Would love to see 2 more props to this:

* animation | boolean | default: true (ability to disable animation)
* color | string |  default: null (override type background color)

**Comment by EmilMoe** [comment]
Thanks. Good call. I think `boolean`s should always be false by default, then they are easier, and prettier, to apply

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
