### ISSUE TITLE
The raw HTML shows and disappear immediately.

### ISSUE THREAD

**Issue by yaquawa** [JosephusPaye/Keen-UI#403]
For example, I have the following code.

```
<ui-modal ref="modal_1" title="Hi">
    Hello World!
</ui-modal>
```

The raw HTML `Hello World!` will shows and disappear immediately.
How to resolve this problem?

**Comment by JosephusPaye** [comment]
Hi @yaquawa,

You can use [`v-cloak`](https://vuejs.org/v2/api/#v-cloak). This will hide the element until Vue is initialized.

Add this to your CSS:

```css
[v-cloak] {
  display: none;
}
```

Then update your template:

```vue
<ui-modal ref="modal_1" title="Hi" v-cloak>
	Hello world!
</ui-modal>
```
