### ISSUE TITLE
Clearing the selection in UiSelect

### ISSUE THREAD

**Issue by aashi0727** [JosephusPaye/Keen-UI#406]
How can I clear the selected value for single select option in UiSelect?

**Comment by JosephusPaye** [comment]
Added a new method to clear the selection:  https://github.com/JosephusPaye/Keen-UI/commit/921f78765e0175c1ed80aa62ffff2a3ed72520cd

**Comment by JosephusPaye** [comment]
Released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
