### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by DevKingDigital** [JosephusPaye/Keen-UI#41]
I can't seem to get the model value to bind for ui-textbox

`<ui-textbox name="name" icon="input" label="Name" help-text="Please enter a name" validation-rules="required" value="name"></ui-textbox>`

But when I type, Vuedev tools just shows the value as empty

**Comment by caex** [comment]
I guess it should be `:value.sync="name"` (Note the '**:**')
shortand for `v-bind:value.sync="name"`

**Comment by DevKingDigital** [comment]
Awesome, that appears to have fixed it.

@JosephusPaye you might need to update your documentation to make it a little more obvious
