### ISSUE TITLE
UIToolbar removeNavIcon not working

### ISSUE THREAD

**Issue by gustter** [JosephusPaye/Keen-UI#415]
Hi there.

I have set **removeNavIcon** to false but navicon still showing.

<ui-toolbar :removeNavIcon="false"></ui-toolbar>

Any idea?

Thanks!

**Comment by JosephusPaye** [comment]
Hi @gustter,

`remove-nav-icon` or `removeNavIcon` should be set to `true` to remove the icon. 

See an example here: https://codepen.io/JosephusPaye/pen/OoRoay.

See here for when to use `camelCase` vs `kebab-case` for props: https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case

**Comment by gustter** [comment]
Excellent. Thank you very much for the solution and the "educational" link :)
