### ISSUE TITLE
Call openDropdown on ui-icon-button has not effect

### ISSUE THREAD

**Issue by gustter** [JosephusPaye/Keen-UI#419]
Hi there.

We have an issue with _ui-icon-button_.

In the next code, when the next javascript run:

**this.$refs.dropdownUser.openDropdown();**

the menu does not appear.

       <div 
            class="mui-user-toolbar-name"
            @click="toOpen"
        >
            {{fullname}}
        </div>
        <ui-icon-button
            class="needsclick"
            color="custom"
            has-dropdown
            icon="keyboard_arrow_down"
            ref="dropdownUser"
            size="small"
            type="secondary"
            buttonType = "div"
            dropdown-close="alertar"
        >
            <ui-menu
                contain-focus
                has-icons
                slot="dropdown"
                :options="menu"
                @select="menuSelect"		
                @close="toClose"               
            ></ui-menu>

        </ui-icon-button>

Any idea?

Thanks.

**Comment by olsgreen** [comment]
I have the same problem, looks like anything the uses the UiPopover component is affected, it's an issue with the new implementation of tippy... @JosephusPaye

**Comment by JosephusPaye** [comment]
Closing for now, should be fixed as per https://github.com/JosephusPaye/Keen-UI/pull/422#issuecomment-452134061.

Reopen if this is still an issue.
