### ISSUE TITLE
Debounce

### ISSUE THREAD

**Issue by DevKingDigital** [JosephusPaye/Keen-UI#42]
The debounce attribute doesn't seem to do anything. See below:

`<ui-textbox name="name" :debounce="500" icon="input" :value.sync="name" label="Name"></ui-textbox>`

**Comment by JosephusPaye** [comment]
This seems to be a bug. Will be fixed in next release.

**Comment by victor-ponamariov** [comment]
Same here, doesn't work with autocomplete

**Comment by JosephusPaye** [comment]
Should be fixed in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9).
