### ISSUE TITLE
Incorrect modal size when a modal is placed within a modal

### ISSUE THREAD

**Issue by olsgreen** [JosephusPaye/Keen-UI#427]
As the title describes, the child modal inherits the parent's size due to non-specific CSS selectors:

    <ui-modal size="large">
        <ui-modal size="small">
            This modal will also display as a large modal.
        </ui-modal>
    </ui-modal>

**Comment by JosephusPaye** [comment]
Added in https://github.com/JosephusPaye/Keen-UI/commit/f6a86a759296c75e775b2a551075181a11db1884.

**Comment by JosephusPaye** [comment]
Fix released in [v1.1.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.0).
