### ISSUE TITLE
UiDatePicker: Fix component reactivation after being disabled.

### ISSUE THREAD

**Issue by olsgreen** [JosephusPaye/Keen-UI#435]
To reproduce:

1. Add an instance of the component bound via 'v-model' and with the 'disabled' attribute referenced to a data property.
2. Input a date via the picker.
2. Disable the component via the 'disabled' referenced property.
3. Change the date within the property being bound via 'v-model' to another value.

You should see an error in the console caused by the component regarding a missing reference:

`[UiPopover]: Trigger element not found.`

After this the calendar pop over will not activate.

Pull request en-route.

**Comment by JosephusPaye** [comment]
Released in [v1.1.2](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.1.2).
