### ISSUE TITLE
Ui-button cannot be clicked

### ISSUE THREAD

**Issue by orckid-lab** [JosephusPaye/Keen-UI#440]
I have a ui-modal with a ui-button inside. On keen-ui 1.1.2, the button cannot be clicked (the cursor style is set to default when the CSS is compiled).

Downgraded to keen-ui 1.0.0 and the button now can be clicked and also triggers the action.

Tried on various node versions (10.11, 10.15, 11.11)

**Comment by JosephusPaye** [comment]
HI @orckid-lab,

Can't seem to reproduce. Could you make a demo showing the bug? 

Here's a Codepen template setup with Vue and Keen UI: https://codepen.io/JosephusPaye/pen/xBddjL.

**Comment by orckid-lab** [comment]
Hi, I will do one more test by Monday (re-upgrade to 1.1.2) and see if the issue occurs again. Two changes were involved in this, changed dev dependencies of a custom module to peer dependencies, then downgraded keen-ui.

I'll create a repo with the issue if proved that it occurs based on using latest version (as we're using laravel-mix 4.0.0 to compile).

**Comment by orckid-lab** [comment]
I was unable to reproduce this with a stand alone example using laravel mix and latest keen-ui (minified JS) as on the said project. This is probably caused by another dependency.
