### ISSUE TITLE
How can we select an empty value?

### ISSUE THREAD

**Issue by madatan** [JosephusPaye/Keen-UI#446]
Once the user selects a value, he/she is not able to choose a blank option in order to clear the selected value. Is there a prop for ui-select to add a blank option to the ui-select by default?

**Comment by JosephusPaye** [comment]
Hi @madatan,

You can add a clear icon button next to the Select and use the `clearSelection` method

**Comment by madatan** [comment]
Hi Josephus,
Thanks for the recommendation, i implemented as per your suggestion. However, the possibility to choose an empty value would be great in the future.
Regards,Georgiana     On Saturday, May 11, 2019, 2:02:13 PM GMT+3, Josephus Paye II <notifications@github.com> wrote:  
 
 
Hi @madatan,

You can add a clear icon button next to the Select and use the clearSelection method
