### ISSUE TITLE
Width of floating label in UiTextbox not correct

### ISSUE THREAD

**Issue by sagg** [JosephusPaye/Keen-UI#447]
Hi,

the floating label is producing scrollbars cause it does not fit into it's own container.
I made a small example using a modal, there it's pretty easy to see.
https://codesandbox.io/s/vue-template-uimd7

Thanks. :)

**Comment by JosephusPaye** [comment]
Hi @sagg,

Yeah, it's easy to see. This happens because we're scaling the label up to sit in the textbox when there's no input. This makes the width grow past 100%.

We can fix this by updating `.ui-textbox__label` to hide any overflow:

```css
.ui-textbox__label {
	overflow: hidden;
}
```

**Comment by JosephusPaye** [comment]
Fixed in 3e998ff.
