### ISSUE TITLE
Unable to alter zIndex of UiDatePicker

### ISSUE THREAD

**Issue by scottnash** [JosephusPaye/Keen-UI#448]
There doesn't seem to be a way to override the default z-index of 9999 for the datepicker (apart form using an !important in the css).  zindex isn't one of the props on the uidatepicker component so doing something like this has no effect.  Is this an error or am I just missing something?
```
configure(UiDatepicker, {
  zIndex: 1000000000
});
```

**Comment by JosephusPaye** [comment]
You're right - there's currently no prop for setting the z-index. This is set by Tippy.js, the dropdown library used.

Tippy has a zIndex config option which we can expose as a prop: https://atomiks.github.io/tippyjs/all-options/

**Comment by JosephusPaye** [comment]
Fixed in [v1.2.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.2.0)
