### ISSUE TITLE
yearRange not working

### ISSUE THREAD

**Issue by mhunger** [JosephusPaye/Keen-UI#449]
Hi when i put a year range it is ignore. What am i doing wrong ? 

`<ui-datepicker
          name="birthdate"
          label="Geburtsdatum"
          placeholder="Bitte wählen Sie ihre Geburtsdatum"
          v-model="customer.birthdate"
          :year-range="[2018]"
          class="m-4"
        ></ui-datepicker>`

**Comment by JosephusPaye** [comment]
Thanks for the report.

Just checked and this is a bug: the `yearRange` is not being passed from UiDatepicker to the sub components.

**Comment by JosephusPaye** [comment]
Fixed in [v1.2.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.2.0)
