### ISSUE TITLE
Feature: Datepicker opening on year by default

### ISSUE THREAD

**Issue by entioentio** [JosephusPaye/Keen-UI#453]
I'll use datepicker to let user input birthdate. It seems not intuitive enough to click on the year.

I'd like to add some prop like `defaultViewMode` defaulting to `date` with possible value of `year`. When value was `year` it'd open datepicker on year-selection every time it opens.

Is it a valid use-case?

-----
oh, and BTW. I love this library. It's precisely what I sought for long. Doesn't enforce anything on you, doesn't change your workflow, supports code splitting nicely. Thank you for the balance you brought into my project :pray:

**Comment by JosephusPaye** [comment]
Hi @entioentio,

Thanks for the kind words 😊.

Showing the year picker first when you open the dropdown seems like a useful feature to have 👍.

Like you suggested, a prop like `defaultView` with values `'date' | 'year'` would work.

Will look at adding this. In the meantime, I'd be glad to review and merge a PR that adds it.

**Comment by JosephusPaye** [comment]
Fixed in #454.
