### ISSUE TITLE
Select opens above when viewport is shorter than dropdown

### ISSUE THREAD

**Issue by hyvyys** [JosephusPaye/Keen-UI#455]
First of all thanks for the great framework and congratulations!

### Expected behaviour

When viewport height is smaller than default max height of dropdown, the size of the dropdown should be decreased accordingly.

### Actual behavior

When viewport height is smaller than default height of the dropdown, it opens above instead, even if there is absolutely no space to do so.

### Screenshots

![obraz](https://user-images.githubusercontent.com/20814638/62319542-7ad32080-b49e-11e9-9c63-99b3789474f1.png)

![obraz](https://user-images.githubusercontent.com/20814638/62319415-33e52b00-b49e-11e9-9fc1-96bb926658e0.png)

### Notes

This is probably not an often issue, as people are not very likely to resize their browser windows vertically. But still.

**Comment by JosephusPaye** [comment]
Hi @hyvyys,

Not much we can do about this. It's the current behavior in Popper.js (the library we use to position dropdowns).

You can see the same behavior here: https://codepen.io/JosephusPaye/pen/EqwXMB/top/
