### ISSUE TITLE
ui-icon-button docs have typo

### ISSUE THREAD

**Issue by hyvyys** [JosephusPaye/Keen-UI#456]
The [docs ](https://josephuspaye.github.io/Keen-UI/#/ui-icon-button) say:

> You can set a custom or SVG icon using the `icon` slot.

but in the `Slots` tab there is no `icon` slot listed, the above should be:

> You can set a custom or SVG icon using the `default` slot.

**Comment by JosephusPaye** [comment]
Good catch 😄. PR welcome.

**Comment by JosephusPaye** [comment]
Fixed in #457.
