### ISSUE TITLE
UiRadio inner circle is offset

### ISSUE THREAD

**Issue by hyvyys** [JosephusPaye/Keen-UI#464]
Using default styles, the radio component is displayed malformed:
![obraz](https://user-images.githubusercontent.com/20814638/64237421-9ba6ef80-cefc-11e9-93ba-50758f8fc06c.png)

Codepen:
https://codepen.io/hyvyys/pen/NWKwRwW

**Comment by JosephusPaye** [comment]
This happens when the CSS box sizing is not `border-box`. Add this and it should be fixed.

```css
*,
*::before,
*::after {
    box-sizing: border-box;
}
```

I think this is [mentioned in the README](https://github.com/JosephusPaye/Keen-UI#css-reset).

**Comment by hyvyys** [comment]
Right, forgot about that. Though I did use it in a previous project and it did not cure all — for instance, inputs with border that widens on click still caused reflow, I think, on some occasions.

Is there a specific reason the library was set up to demand this piece of CSS? Would it not feel less hacky if the stylesheet of the specific components declared this on their own, without polluting global styles?

**Comment by JosephusPaye** [comment]
Yeah, inputs with borders will cause a reflow when the border width changes, regardless of `box-sizing`.

No specific reason, it was simply a convenient and [common](https://css-tricks.com/inheriting-box-sizing-probably-slightly-better-best-practice/) approach. Especially when using Keen UI with CSS frameworks (for layout, typography, etc) which automatically apply the reset. Almost all CSS frameworks do this.

The alternative is applying `border-box` to each Keen UI component, via a number of ways:

- Add it to every CSS selector, including `::before` and `::after` (this is a lot!)
- Add it to the root selector of each component, something like:

	```css
	.ui-alert,
	.ui-alert * {
		box-sizing: border;
	}
	```

	The nested universal selector here (`.ui-alert *`) [could be slow](https://www.paulirish.com/2012/box-sizing-border-box-ftw/) and will also affect slotted content that's nested in the alert.

- Match the `ui-` class prefix and apply `border-box` sizing to only those elements, as suggested here: https://stackoverflow.com/a/8588532/5800506.
	This could work, but I haven't tested.
