### ISSUE TITLE
Focus ring not working when importing components from source

### ISSUE THREAD

**Issue by hyvyys** [JosephusPaye/Keen-UI#481]
Is there a specific thing I need to do to enable focus rings on buttons? I only recently even discovered there was such a thing built into the library, as I hardly ever experienced it working.

**Comment by JosephusPaye** [comment]
It's only shown on keyboard focus.

Is that not working for you? If not what browser are you using? Also does it show the focus ring on UiIconButton?

**Comment by hyvyys** [comment]
Yes, it's not working for me with keyboard focus. Actually I found the culprit: it works when importing the transpiled version:

```js
import {UiButton} from "keen-ui";
```

but not when importing from source:

```js
import UiButton from "keen-ui/src/UiButton";
```

**Comment by JosephusPaye** [comment]
Ah yes, if you're importing from source you'll need the `bootstrap` file which sets up the focus check:

```js
import 'keen-ui/src/bootstrap';
```

Make sure to import it only once though (perhaps at the entry point of your app).
