### ISSUE TITLE
UiPopover: trigger open/close

### ISSUE THREAD

**Issue by jonagoldman** [JosephusPaye/Keen-UI#49]
Is there a way open or close a popover besides default element trigger?

**Comment by JosephusPaye** [comment]
There isn't any way to do that at the moment, though I think it's useful functionality that should be added.

I will look at adding it in v0.8.9, perhaps with open/close events.

**Comment by JosephusPaye** [comment]
Now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9), see the [UiPopover docs](https://josephuspaye.github.io/Keen-UI/#/ui-popover-docs).
