### ISSUE TITLE
How to dismiss a UiSnackbarContainer?

### ISSUE THREAD

**Issue by sysebert** [JosephusPaye/Keen-UI#493]
I'm looking for a way to dismiss a snackbar using the UiSnackbarContainer. Ideally it'd work the exact same way as hideOnClick does, but be able to do that via a method on the container.

I want to have an action that says "close" trigger the method in the onActionClick handler.

Any tips or tricks would be appreciated!

```js
this.$refs.snackbarContainer.createSnackbar({
  action: 'Close',
  actionColor: 'primary',
  duration: 8000,
  message: 'Some message',
  onActionClick: () => {
    // not sure what to put here to make it hide
  },
});
```

**Comment by JosephusPaye** [comment]
The `onActionClick` hook actually receives the snackbar as an argument ([reference](https://github.com/JosephusPaye/Keen-UI/blob/next/src/UiSnackbarContainer.vue#L145)).

So you can do:

```js
this.$refs.snackbarContainer.createSnackbar({
  message: 'Some message',
  action: 'Close',
  onActionClick: (snackbar) => {
    snackbar.show = false; // Hide the snackbar
  },
});
```

**Comment by sysebert** [comment]
I'm not sure where in the docs you mean, but this is the page I basically leave in my tabs: https://josephuspaye.github.io/Keen-UI/#/ui-snackbar :)
