### ISSUE TITLE
Dynamic suggestions

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#5]
Sorry for all the reports :-)

I want to dynamic load suggestions from my backend as the user types in the field. I'm not sure however if you have made this possible yet?
So now I just preload everything, but this isn't optimal when the database grow large of course.

Also it seems like that when I populate it with array of objects, it has a hard time auto completing my input?

**Comment by JosephusPaye** [comment]
Check out the new v0.8.6. I re-wrote the autocomplete to use only Vue and it is now completely reactive.

This should also fix #2 and #4. 

If you want to load suggestions from the backend, watch the autocomplete value prop and make your AJAX calls when it is changed. 

See this CodePen for an example: http://codepen.io/JosephusPaye/pen/eZKNGN?editors=0010

**Comment by EmilMoe** [comment]
Thanks. I'm currently working on another part of the project, but I will let you know as soon I have had time to look into this.

**Comment by EmilMoe** [comment]
Working
