### ISSUE TITLE
UIMenu: allow html / components inside options

### ISSUE THREAD

**Issue by jonagoldman** [JosephusPaye/Keen-UI#50]
I'm currently using UIPopover to show a dropdown menu where each option has a UISwitch toggle, resulting in a mutant, a functionality mix of UIMenu and UISelect (multiple with switches instead of checkboxes).
I think would be useful to allow for further customization on the UIMenu options.

**Comment by JosephusPaye** [comment]
Yeah, having custom HTML in menu options is something I needed recently too and it will be added in v0.8.9.

**Comment by JosephusPaye** [comment]
Implemented in: https://github.com/JosephusPaye/Keen-UI/commit/62083d58a5840305f0281521da76c89a104a4043 and https://github.com/JosephusPaye/Keen-UI/commit/233bddd0e0945dba19d37d9a93a82446418d2cf4

**Comment by JosephusPaye** [comment]
Now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9). You can now use a `partial` for the menu options just like with UiSelect, see the [UiMenu docs](https://josephuspaye.github.io/Keen-UI/#/ui-menu-docs).

**Comment by JosephusPaye** [comment]
In v1.0, you can use the new [Scoped Slots](https://vuejs.org/v2/guide/components.html#Scoped-Slots) for custom menu option templates.
