### ISSUE TITLE
ESLint CRLF Windows

### ISSUE THREAD

**Issue by Lewiscowles1986** [JosephusPaye/Keen-UI#502]
Kept receiving the following error when using Windows

> Expected linebreaks to be LF but found CRLF.  linebreak-style

This is even on the `next` branch without any changes.

I know windows is a sucky OS, but git converts the CRLF back to LF when committing anyway, and this is just after a git checkout with no edits so 🤷

**Comment by JosephusPaye** [comment]
I'm on Windows too, and use the following to ensure only LF is committed:

```
git config --global core.autocrlf input
```

So I can checkout and edit in CRLF but all commits are in LF. Though I've setup all my editors to use LF across the board.

**Comment by Lewiscowles1986** [comment]
While I understand we can ask Git users to change how git works out of the box, I think you'll always have some people unprepared. That would also take any accidental editor differences between projects and enforce them globally. For me it's not a workable solution.

**Comment by JosephusPaye** [comment]
I think it's possible to do this via a `.gitattributes` file that enforces it for the repo, without the need for a global config change.

**Comment by Lewiscowles1986** [comment]
Thanks @JosephusPaye 

I've added a `.gitattributes` file to the repo as part of the PR for this. I still believe the `eslint` changes are reasonable because the `autocrlf` behavior is only when checking out and committing. 

Perhaps as a follow-up `.editorconfig` should also be added in a separate PR to ensure not only line-feeds, but other formatting for the project is enforced by supporting IDE's?

**Comment by JosephusPaye** [comment]
Thanks for the PR update.

We've got LF specified in the current [`.editorconfig`](https://github.com/JosephusPaye/Keen-UI/blob/next/.editorconfig#L5) already.

**Comment by Lewiscowles1986** [comment]
Thanks for update. https://github.com/JosephusPaye/Keen-UI/commit/9dd56b436d2c6d179e7f5a080d8a9d783c0e51e3 looks to me that `.gitattributes` without `.eslintrc` edits saves the day.
