### ISSUE TITLE
Question - Overriding variables.scss

### ISSUE THREAD

**Issue by K-marad** [JosephusPaye/Keen-UI#504]
Hello.
I'm trying to override scss variables but I have no luck yet.

I've been following this : https://github.com/JosephusPaye/Keen-UI/blob/master/Customization.md#customization

I import KeenUI components like so :
```javascript
import Vue from 'vue'
import App from './App'
import router from './router'
import store from './store'

/* Notifications */
import VueAWN from "vue-awesome-notifications"
let options = {}
Vue.use(VueAWN, options)

/* KeenUI */
import KeenUI from 'keen-ui';
import 'keen-ui/dist/keen-ui.css';
// Here define components global options
Vue.use(KeenUI, {
    UiTooltip: { 
      position: 'top'
    },
    UiButton: {
      iconPosition: 'right'
    }
  }
)

/* Running Vue */
Vue.config.productionTip = false
new Vue({
  render: h => h(App),
  store,
  router,
  components: { App }
}).$mount('#app')
```

I place a UiButton on a page. If I don't specify "color" it is grey, if I specify color="primary" it turns blue, so fine.

I created a **variables.scss** file : src/assets/style/variables.scss, added those lines to it :
```
$brand-primary-color: red;
$brand-accent-color: green;
```
Edited **vue.config.js**

```javascript
module.exports = {
  css: {
    loaderOptions: {
      sass: {
        data: `@import "@/assets/style/variables.scss";`
      }
    }
  },
  devServer: {
    host: '0.0.0.0',
    port: 80,
    disableHostCheck: true,
    hot: true,
    watchOptions: { 
      aggregateTimeout: 300, 
      poll: true 
    },
    proxy: {
      '^/api': {
        target: 'http://sanic_server:8080',
        ws: true,
        changeOrigin: true
      }
    }
  }
}
```
Restarted the server manually.
But nothing changes. And I have no error message.
I double checked everything, paths are correct... I just don't get it.

Am I missing something, or doing something wrong? 

Thank you.

**Comment by JosephusPaye** [comment]
When you override the variables in SCSS, you need to import the components from source (instead of prebuilt) and you also should not import the compiled CSS file.

So instead of:

```js
import KeenUI from 'keen-ui';
import 'keen-ui/dist/keen-ui.css';
```

You'd have just:

```js
import KeenUI from 'keen-ui/src/index';
````

**Comment by K-marad** [comment]
Oh okay, I understand !
That works perfectly thank you :)

**Comment by JosephusPaye** [comment]
Glad to help.
