### ISSUE TITLE
how to add button or link in ui-collasible header

### ISSUE THREAD

**Issue by dheo0** [JosephusPaye/Keen-UI#505]
first of all, I'm sorry for my poor english

I want to know add button or A tag
in ui-collapsible header??

I can insert a button or link but it doesn't work...

**Comment by JosephusPaye** [comment]
Hi,

The ripple animation intercepts all clicks on the header. If you disable the ripple, you can add interactive elements to the header, like a link or button.

See this example: https://codepen.io/JosephusPaye/pen/GRoaqKG?editors=1000

**Comment by dheo0** [comment]
Thank you
