### ISSUE TITLE
Autocomplete events

### ISSUE THREAD

**Issue by rowanwins** [JosephusPaye/Keen-UI#51]
Gday,

I've managed to get the autocomplete component working quite nicely but I'm wondering if you had any guidance on the best way to work with selection events? I couldn't really find a good way to do anything when a user selected something, I'm probably missing something obvious? 

I did have a look at the source code and perhaps the Autocomplete component should dispatch events on the 'select' and 'highlight' methods that people can listen to? I did have an initial play with this and it seems to work well Does this sound like a worthwhile approach, if so I'm happy to put in a pull request.

Cheers

**Comment by JosephusPaye** [comment]
Hi,

Yep, I think a selected event is essential. Not sure about highlighted though, what use case do you have for it? It might be worth adding if the use case is common.

**Comment by rowanwins** [comment]
Gday @JosephusPaye 

Looking at the various autocomplete libraries such as awesomplete or typeaead out there the common events seem to be
- popup opened
- popup closed
- option highlighted
- option selected

In terms of the highlighted event I can imagine a scenario where you might want to change another part of your UI to show greater detail about the option you're highlighting.

And then in terms of what those events return I'd suggest passing the whole object back rather than just the value or text as that potentially gives people a bit more flexibility and is easy enough to achieve.

How does that sound?
Cheers
Rowan

**Comment by JosephusPaye** [comment]
Yeah that sounds reasonable. Will see if it can be added to v0.8.9.

**Comment by JosephusPaye** [comment]
Now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9). See the [UiAutocomplete docs](https://josephuspaye.github.io/Keen-UI/#/ui-autocomplete-docs).
