### ISSUE TITLE
Why Keen-UI generate empty iframe?

### ISSUE THREAD

**Issue by devinchen** [JosephusPaye/Keen-UI#52]
Why we have empty iframe tag? Is it necessary?

**Comment by JosephusPaye** [comment]
Keen UI does not generate any iframes as you will [see here](https://github.com/JosephusPaye/Keen-UI/search?utf8=%E2%9C%93&q=iframe) if you search the code. Can you provide more information?

**Comment by devinchen** [comment]
Here's the code in `keen-ui/dist/keen-ui.js`

![screen shot 2016-06-06 at 13 08 52](https://cloud.githubusercontent.com/assets/1542916/15812465/0419a5d2-2be8-11e6-9280-adfb52837f44.png)

**Comment by JosephusPaye** [comment]
That code is from [Poser](https://github.com/bevacqua/poser/blob/6651ca8a1e767cbd42e640fe14363cfb0d0d7f2e/src/browser.js#L5-L12), which is used by [Dominus](https://github.com/bevacqua/dominus) (the DOM library that Keen UI uses).
