### ISSUE TITLE
UiButton: missing popover position props

### ISSUE THREAD

**Issue by devinchen** [JosephusPaye/Keen-UI#53]
The doc says we can set position of popover. But UiButton doesn't pass that property to UiPopover according to this [line](https://github.com/JosephusPaye/Keen-UI/blob/master/src/UiButton.vue#L38)

**Comment by JosephusPaye** [comment]
Yeah, my mistake. Will be fixed in the upcoming v0.8.9.

Thanks

**Comment by JosephusPaye** [comment]
Fixed in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9).
