### ISSUE TITLE
UiSelect can no longer be used correctly in UiPopover

### ISSUE THREAD

**Issue by TheRedfoox** [JosephusPaye/Keen-UI#535]
Since release [1.3.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.3.0) it is no longer possible to use a UiSelect inside a UiPopover because it closes the UiPopover when an option is selected.

I don't know of any workaround or other use.

Thanks a lot !

**Comment by JosephusPaye** [comment]
Should be fixable by using the new props added in #536. Re-open if that's not the case.
