### ISSUE TITLE
UiProgressCircular supporting custom color

### ISSUE THREAD

**Issue by NemoAlex** [JosephusPaye/Keen-UI#54]
How about one can set color out of the box?
If the color prop is not `primary`, `accent`, `multi-color`, `black` or `white`, take it as a color string.

**Comment by JosephusPaye** [comment]
Hi @NemoAlex, 

By default the color is `primary`, although I think it would be useful to support a color string. I will see if it can be fitted into v0.8.9, the next release.

**Comment by NemoAlex** [comment]
Thank you very much!

**Comment by JosephusPaye** [comment]
You can do this currently using CSS:

```html
<ui-progress-circular color="custom-color-green" show></ui-progress-circular>
```

```css
.custom-color-green {
    stroke: green;
}
```

See demo here: http://codepen.io/JosephusPaye/pen/oLoBBq
