### ISSUE TITLE
Add autocomplete search type

### ISSUE THREAD

**Issue by rowanwins** [JosephusPaye/Keen-UI#56]
Gday @JosephusPaye 

Another idea for the autocomplete component. 

Currently the search is powered by fuzzy search which returns items which might not be an exact match. In my use case I'm only interested in exact matches. 

So would you be interested in adding a property that allows you to define the search type as either as fuzzy (used by default) or exact?

I've got the regex which powers an exact match search by looking at awesomplete and it seems to be working well so if you're interested I'll put in another pull request.

Cheers

**Comment by JosephusPaye** [comment]
Hey @rowanwins,

Thanks for the suggestion, it will be added in v0.8.9.

**Comment by rowanwins** [comment]
Hi @JosephusPaye 

I've been dabbling a bit more with this component to get some desired some functionality for my requirements and have a few other suggestions for params

- allow people to chose whether the first item is automatically selected or not

- rather than going from the last item back to the first by pressing down (or vice-versa), highlight back in the text box and don't highlight any item

Very simple things but provide a bit more flexibility. 

In the app I've been building I've pretty much been replicating the autocomplete functionality provided by https://www.google.com.au/maps so these proposed things fit in line with that functionality.

Cheers
R

**Comment by JosephusPaye** [comment]
Implemented in https://github.com/JosephusPaye/Keen-UI/commit/b6513198d1112b3dca6b4c0953021df2129e4ac9

**Comment by rowanwins** [comment]
Gday @JosephusPaye ,

Thanks for accepting those changes. So I take it that the regex match approach should be passed in as a custom filter?

**Comment by JosephusPaye** [comment]
@rowanwins,

Yes, you will pass in a filter function which takes the item and the search query. The function should return `true` if there is a match or `false` otherwise.
