### ISSUE TITLE
Add property to have labels shown inline instead of above the input

### ISSUE THREAD

**Issue by lowerends** [JosephusPaye/Keen-UI#57]
I think it would be useful to have a property on the relevant components that can have a label, to choose whether the label is shown above the input (as is currently the case) or to the left (and possibly the right) of the input field.

Thanks for your feedback!

**Comment by JosephusPaye** [comment]
This would no doubt be a useful option, but there no plans to add it at the moment. Would eventually like to add it, though.

**Comment by lowerends** [comment]
Good to know! I might give it a try later on and see how far I get.

**Comment by JosephusPaye** [comment]
Closing for now.
