### ISSUE TITLE
Checkbox value "on"

### ISSUE THREAD

**Issue by lowerends** [JosephusPaye/Keen-UI#59]
I noticed that the submitted value for a checked checkbox is ```"on"```, while the synced value of the model is ```true```. Is there a way to have the checkbox submit ```true``` instead?

**Comment by lowerends** [comment]
Also, is it possible to have the checkbox submit ```false``` if the checkbox is not checked? Currently, nothing is submitted if the checkbox is not checked.

**Comment by JosephusPaye** [comment]
Hey @lowerends,

What you describe is the default behavior for HTML checkboxes (`<input type="checkbox">`). They are only submitted if checked and the value submitted is the string `"on"`. This happens at the browser level with the default `<form>` tag. [See here](http://stackoverflow.com/questions/11424037/does-input-type-checkbox-only-post-data-if-its-checked) for more info.

To get the the behavior you want, you may need to intercept the form submission, and use AJAX to send the custom formatted data to the server.

**Comment by lowerends** [comment]
Hey @JosephusPaye,

I'm currently handling it on the server side, but I thought it would be nice to have this functionality baked into the checkbox component. I'll just continue to put the logic on the server side.

Thanks!

**Comment by te1** [comment]
You could use `<input type="checkbox" value="true">` to get `"true"` (which is still a string) instead of `"on"`.
Vue actually allows you to change the true and false value of a checkbox to something other than strings (http://vuejs.org/guide/forms.html#Value-Bindings).
Also setting the true value is useful if you bind multiple checkboxes to a single array (http://vuejs.org/guide/forms.html#Checkbox).

So it may actually be useful if Keen UI supported this as well.

**Comment by lowerends** [comment]
On a second thought, I'll reopen the issue as there seems to be more general interest in this functionality.

**Comment by EmilMoe** [comment]
I second the replace of on with true.

**Comment by JosephusPaye** [comment]
As implemented in https://github.com/JosephusPaye/Keen-UI/commit/aa13404a95840828234099a6dd09aa998f551fcb, you can set `value` to the string `"true"` or `"false"` and those will be submitted. This also allows for binding multiple checkboxes.

**Comment by xiaolongyuan** [comment]
+1

**Comment by JosephusPaye** [comment]
Now available in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9), see the [UiCheckbox docs](https://josephuspaye.github.io/Keen-UI/#/ui-checkbox-docs).

**Comment by JosephusPaye** [comment]
In v1.0, to change the submitted value, use the new `submittedValue` prop. To change the checked/unchecked values that are bound to `v-model`, use the `trueValue` and `falseValue` props.
