### ISSUE TITLE
Ability to hide feedback div

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#60]
I was wondering why .ui-textbox-feedback div should be displayed if I set errors? Before errors are displayed it causes unwanted margin. For example, here we can see margin after last name field. However, since other fields don't have any validation rules, they don't have margins. So it kind of inconvenient, in my opinion

![0936610066854926a1702debb778c588](https://cloud.githubusercontent.com/assets/6241595/16059916/e0a87662-328d-11e6-9c39-d212818f2e5f.png)

How to deal with that, maybe show errors only when we trigger them, like on blur?

**Comment by JosephusPaye** [comment]
Hey @victor-ponamariov,

I will see if an option can be added to collapse the space reserved for errors when there are no errors. This could make the v0.8.9 release, coming soon.

**Comment by JosephusPaye** [comment]
Fixed in v1.0. If there is no help or error, the feedback `div` is not shown.
