### ISSUE TITLE
Asynchronous validation

### ISSUE THREAD

**Issue by lowerends** [JosephusPaye/Keen-UI#61]
Is there a way to do asynchronous validation (using validatorjs) for these components? I noticed validatorjs allows for this, but I'm not sure the current implementation of the component validation allows for it as well.

**Comment by lowerends** [comment]
Actually, what this would come down to, is that the error state and error messages for a component could be set from for example a Vue method. 

The state can already be set by using the ```valid``` property. 

Is there a way to set the error messages for a component programmatically?

**Comment by JonasDoebertin** [comment]
Would be nice to have an option to set the error message programmatically 🎉

**Comment by JosephusPaye** [comment]
This would indeed be a useful option and I will look at adding it in v0.8.9.

**Comment by JosephusPaye** [comment]
Implemented in https://github.com/JosephusPaye/Keen-UI/commit/29b1fd7c5a3df2ac66d69722042914d6482ee7ca

**Comment by JosephusPaye** [comment]
In [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9) you can now set the validation state and error from outside the component using the new `ui-input::set-validity` event.
