### ISSUE TITLE
Icon of UiAlert

### ISSUE THREAD

**Issue by NemoAlex** [JosephusPaye/Keen-UI#62]
I found that when icon is not defined and type of UiAlert changes, the icon won't automatically follow the change.
So maybe we can add a watch in UiAlert to do that?

**Comment by NemoAlex** [comment]
Currently, I have to do this:
```
ui-alert(:type="alertType", :icon="{success: 'check_circle', error: 'error'}[alertType]")
```

**Comment by JosephusPaye** [comment]
Yeah, the current way we handle the props means the icon is not reactive. This will be fixed in the next version.

**Comment by JosephusPaye** [comment]
The `icon` is now reactive in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9).

**Comment by NemoAlex** [comment]
Good job! I'll check it out. Thanks.
