### ISSUE TITLE
Any css skin around that has normal form fields instead of the material design ones? 

### ISSUE THREAD

**Issue by gebrits** [JosephusPaye/Keen-UI#63]
Is there any Keen-UI skin/plugin that resets keen form fields to the 'standard' form fields instead of the material design ones? I like Material Design, but believe the form fields are an exceptionally bad idea ux wise.

**Comment by JosephusPaye** [comment]
@gebrits,

There is no way in Keen UI to change the style of the input elements, for that you will have to use custom CSS.
