### ISSUE TITLE
How to set specific active tab?

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#64]
Hello. How can I do this? Can you provide an example?

Tried:
`activeTab="2"`
`active-tab="2"`

Doesn't work.

Thanks.

**Comment by JosephusPaye** [comment]
Hey @lavezzi1,

First you need to set the `id` on the tab, then use pass that `id` as the active tab. 

Example:

```html
<ui-tabs active-tab="tab-2">
    <ui-tab header="Tab 1" id="tab-1">
        Tab 1
    </ui-tab>
    
    <ui-tab header="Tab 2" id="tab-2">
        Tab 2
    </ui-tab>
  
    <ui-tab header="Tab 3" id="tab-3">
        Tab 3
    </ui-tab>
</ui-tabs>
```

[See here for demo](http://codepen.io/pen?template=NrKmPQ).
