### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#65]
Thanks once again.

Would it be okay if you change so all components use the web pages default font size? I have to override every component with `font-size: 100%;`

**Comment by JosephusPaye** [comment]
Hi @EmilMoe,

Have you tried this across all components and there are no side effects? Can you make a demo if possible? If there are no issues with any of the components then we can make the change.

Thanks

**Comment by EmilMoe** [comment]
I have only tried it with buttons and select. I meant if you could simply not set a font size at all so they will inherit.

So far I have this SCSS related to your Ui components

~~~~
.ui-button {
    font-size: 100% !important;

    & + .ui-button {
        margin-left: $grid-margin;
    }

    &:disabled {
        cursor: not-allowed;
    }
}

.ui-select {
    &:not(active) {
        margin-bottom: 1px;
    }

    .ui-select-value {
        font-size: 100%;
    }

    .ui-select-display {
        font-size: 100%;
    }

    .ui-select-option-content {
        font-size: 100%;
    }
}

**Comment by breadlesscode** [comment]
```1em``` should be the better unit. Or not?

**Comment by EmilMoe** [comment]
> `1em` should be the better unit. Or not?

I think 100% = 1em = inherit, just different scales.

Optimal KeenUI doesn't bother about font sizes

**Comment by JosephusPaye** [comment]
I am open to this if it doesn't affect the other components. I used something similar in a Bootstrap 4 project recently it was quite nice being able to change the root font size and have everything else scale properly.

**Comment by EmilMoe** [comment]
I guess that's a matter of test, but since you say root element, I guess you know 1rem which refers to the root where 1em refers to the parent. If you set a font size, it should be probably be 1rem?

**Comment by JosephusPaye** [comment]
All components in v1.0 have been re-written to use REMs for sizing, and changing the root font size (on the `<html>` tag) will cause them to scale up/down correctly.
