### ISSUE TITLE
Validate Ui elements from parent component

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#68]
I know this is not directly related to Keen-UI but more Vue, but I haven't been able to find an answer in other places yet, so I hope someone here might know.

I have a wizard with X amount of steps, each step can have Y amount of UI components that must be selected (validation-rules="required"), before I allow the user to continue the wizard I want to make sure all components are valid. Components are inserted into the Wizard in a slot.

So my hurdle is that I somehow need to reference and call all Keen-UI components that are injected into the slot.

**Comment by JosephusPaye** [comment]
You can assess the components in the slot using the parent component's `$children` array: See https://github.com/vuejs/vue/issues/1726#issuecomment-154441244.

You can then check the `name` prop to see if the component is a Keen UI input component and check its validation state using `.valid`.

Closing for now. Reopen if necessary.
