### ISSUE TITLE
Timeline for datepicker and select and floating labels

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#7]
I really like this package you have made. I just need these components to make my project look more consistent, so do you have an idea what the time frame is for:

- Floating labels
- Select
- Datepicker

And can I help in any way?

**Comment by JosephusPaye** [comment]
Unfortunately, I can't give any concrete timeline for new components at the moment as I am busy with other projects.

However, floating labels and a number of other improvements will be available in the next version. I've already added them and just need to test and update the docs.

As for helping, you are already doing so by opening these issues. Please feel free to continue and I will respond whenever I can.

**Comment by EmilMoe** [comment]
I have made a timepicker myself :-)

I will upload it to Github when it's finalised, so no need to worry about this.
I will work on a Datepicker too.

You already made floating labels. Hope they will be uploaded soon.

**Comment by juppdes** [comment]
@EmilMoe Could you share the timepicker, datepicker and floating labels ?

**Comment by EmilMoe** [comment]
@juppdes I can share the timepicker, I haven't made any floating labels. The datepicker isn't working too good, I have unfortunately been so busy lately.

**Comment by JosephusPaye** [comment]
Floating labels and a date picker has been added in v1.0.

**Comment by brickgale** [comment]
@EmilMoe Is that for vue.js 1.0? Would really be nice if there are floating label and time/datepicker.

**Comment by EmilMoe** [comment]
@brickgale KeenUI 1.0 (Vue2) has floating labels :-) I haven't had any time to look into my timepicker, unfortunately. I can put it as public repo later, hopefully someone will help expand it!
