### ISSUE TITLE
UI Slider min max

### ISSUE THREAD

**Issue by didimitrie** [JosephusPaye/Keen-UI#70]
Hello - first off: this stuff is great! I'm having a lot of fun using keen-ui. Amazing job! 

One question, I see there's no way to set min and max values for the slider. Is this something planned? Otherwise I could try my hand at it.

My use case: am generating some sliders programatically, and I want to dynamically set min and max values for each one, based on their initial value: ie, `value = 3 => min = 0, max = 10;` or `value = 12 => min = 0, max = 100`, etc. This would be also something the user would have control over as well, later on. 

Anyway, cheers & amazing work!

**Comment by JosephusPaye** [comment]
Currently there is no explicit `min` and `max` values for the slider as it works as a percentage (e.g. out of 100). 

As an idea, you can use this to simulate min and max values. For example:

```js
let moderatedValue = ((sliderValue / 100) * (max - min)) + min;
```

So if your min is `30` and your max is `60`, a `sliderValue` of `0` will give you `30` (the min), a `sliderValue` of `100` will give you `60` (the max), and a `sliderValue` of `50` will give you `45` (which is halfway between the min and the max). Using a computed property, you can then show this `moderatedValue` next to the slider.

Just an idea, perhaps we will support true `min` and `max` limits in the future.

**Comment by didimitrie** [comment]
Hey Joseuphus, thanks for the answer. I've hacked an extra component that encapsulates my logic for now that's doing exactly what you said :+1: will hopefully in the near future embark on this.

**Comment by JosephusPaye** [comment]
Closing for now.
