### ISSUE TITLE
Missing required prop name in documentation

### ISSUE THREAD

**Issue by victor-ponamariov** [JosephusPaye/Keen-UI#72]
In the [description](https://josephuspaye.github.io/Keen-UI/#/ui-select-docs) of UiSelect there is no indication that "name" prop is required for this component, but it actually is: `Missing required prop: name (found in component: <ui-select>)`

Just a small notice :)

**Comment by JosephusPaye** [comment]
Will be fixed in next version, thanks.

**Comment by JosephusPaye** [comment]
Fixed in [v0.8.9](https://github.com/JosephusPaye/Keen-UI/releases/tag/v0.8.9).
