### ISSUE TITLE
How to use 'tooltip' properly?

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#78]
Hello. Please, let me know how to use it in the right way. 

I use it like this, but doesn't work. 
`                <div class="content">
                    <span class="content__tooltip" v-el:tool>?</span>
                    <tooltip :trigger="$els.tool" :content="first-tooltip" :position="right bottom"></tooltip>
                </div>`

error:

>  Invalid prop: type check failed for prop "trigger". Expected custom type, got Undefined. (found in component: <tooltip>)

Can you provide an example?

**Comment by JosephusPaye** [comment]
What this means is that `$els.tool` is not defined a the time it is passed to the component. Remember Vue renders to the DOM asynchronously and sometimes if there are other control directives like `v-if` and `v-for`, your `$els` references may not be ready at the time you want to use them.

See this working example for using UiTooltip: [http://codepen.io/JosephusPaye/pen/dXzNqx](http://codepen.io/JosephusPaye/pen/dXzNqx?editors=1100)

**Comment by lavezzi1** [comment]
Ok, I got it, thank you. 

Related question about tooltip. Why tooltip goes off the screen? (to the left)
![screen shot 2016-07-07 at 18 41 06](https://cloud.githubusercontent.com/assets/10686894/16650789/a2513c9a-4472-11e6-9cb4-91743fb92405.png)

**Comment by JosephusPaye** [comment]
That's an [issue with Drop](https://github.com/HubSpot/drop/issues/16), the library used for tooltips.

Closing this for now. Reopen if you still need help.

**Comment by AlexandreBonaventure** [comment]
I made a PR to add a workaround for automatic horizontal positioning
https://github.com/JosephusPaye/Keen-UI/pull/86

**Comment by lavezzi1** [comment]
@AlexandreBonaventure cool, thank you! I made changes in my project but tooltip sill working buggy. What I missed?

**Comment by AlexandreBonaventure** [comment]
Yes @lavezzi1 I've only setup the workaround in showDropdown mixin (so its only affecting UiMenu / UiPopover), because it's all I needed for my project, and I didn't know if the PR was going to be merged. But it wouldnt be complicated to code it for the UiTooltip, as well.

**Comment by lavezzi1** [comment]
@AlexandreBonaventure can you make changes for UiTooltip if it's not complicated please?
