### ISSUE TITLE
Static autocomplete suggestions array

### ISSUE THREAD

**Issue by rowanwins** [JosephusPaye/Keen-UI#80]
Gday @JosephusPaye 

Final suggestion from me on the autocomplete component :)

I've been using it in an app and we had an array about around 30,000 items which we were loading in as suggestions. The current autocomplete component requires them to be in the component data which adds all the reactive watchers etc. For an array of 30000 objects it turns out this is incredibly memory intensive (eg our app memory usage doubled).

So we actually worked around it a bit by supplying the component with a static search array that wasn't part of the component data. I then had an event which I could send to the autocomplete to update the static search array.

If you're interested in implementing I can submit a pull request

Cheers
Rowan

**Comment by JosephusPaye** [comment]
Hi @rowanwins,

I definitely would like to see how you did it. Even if I don't add it to UiAutocomplete, I think others would benefit from it.

Thanks

**Comment by rowanwins** [comment]
Basic gist of it was adding a boolean property to the autocomplete component called `'useStaticSearchArray'`. 

Then I registered a new event on the autocomplete called `'setStaticSearchArray'`
````
events:{ 
    'autocomplete-setSearchList'(newSearchList){
        staticSearchArray = newSearchList;
    }
````
Whenever you do want to set the update the static search array you can broadcast an event from the parent component down into the autocomplete component. 

And finally within the watch value of the autocomplete I did 
````
    watch: {
        value() {
              var suggestions = this.suggestions;
              if (this.useStaticSearchArray){
                  suggestions = staticSearchArray;
              }
              ......
````

Anyway happy to contribute the code if you'd like.

**Comment by JosephusPaye** [comment]
I think this is best used the way you implemented it, outside the component.
