### ISSUE TITLE
How do you set up your development environment?

### ISSUE THREAD

**Issue by crswll** [JosephusPaye/Keen-UI#81]
I'd like to attempt to help on this a bit (if you don't mind) but I'm having a hard time figuring out how to set up the development environment (well, not so much setting it up, but how to use it). I was wondering how you normally approach it?

**Comment by JosephusPaye** [comment]
Hi @crswll,

Thanks for the offer to help. To setup for development, these are the steps I follow:

1. Clone the repo (**note that if you want to contribute back, make a fork first and clone that fork**):

    ```bash
    git clone git@github.com:JosephusPaye/keen-ui.git
    ```

2. Move into the cloned folder and install the dependencies:

    ```bash
    cd keen-ui && npm install
    ```

3. Compile the docs and setup the watcher to recompile when you make changes:

    ```bash
    npm run clean:docs && npm run dev
    ```

    This will create 3 files in the `docs/` folder: `index.html`, `docs.bundle.css` and `docs.bundle.js`. Now you can directly open the `index.html` file in your browser, or use a simple HTTP server.

    I use [`live-server`](http://tapiov.net/live-server/), which creates a simple server and automatically reloads connected browsers when the files are changed.

    To use it, first install `npm install -g live-server` (in a different terminal window than where you ran the webpack watcher), then `cd` into the `docs/` folder where the `index.html` file is and run `live-reload`. This will setup the server with live reload and automatically open the page in your default browser.

4. Now make your changes. The component source files are located in `src/` and the documentation source is in `src-docs/components`. When you change any of these files and save, the docs should automatically rebuild and your browser should be refreshed (if both the watcher and `live-server` are running).

### Notes for contributing

If you want to contribute your changes back, make sure to follow the [contributing guidelines](https://github.com/JosephusPaye/Keen-UI/blob/master/CONTRIBUTING.md).

**Comment by crswll** [comment]
Perfect! I was like 90% understanding it. Starting the server in the `docs` directory is what I wasn't getting for the flow of things for some reason. This is working well. Thanks!
