### ISSUE TITLE
How can I put v-model to textbox? 

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#82]
I created a table and want to create a textbox search. How can I put v-model="search" to input inside of textbox? Thanks.

**Comment by JosephusPaye** [comment]
You can use the `value` prop, it maps directly to `v-model`.

**Comment by lavezzi1** [comment]
Looks like it doesnt works for me. I need to get something like this `<input name="query" v-model="searchQuery">`

When I put this 
`<textbox name="search" type="text" placeholder="Search value="searchQuery"></textbox>`

I get searchQuery in the input (value).

**Comment by JosephusPaye** [comment]
Are you using the components from this package? It only works for Keen UI components, example:

```html
<ui-textbox name="search" placeholder="Search" :value="searchQuery"></ui-textbox>
```

Also make sure you have the right binding, notice the **:** in front of value.

**Comment by lavezzi1** [comment]
Yes, I use your components. Yeah, I missed the ':'. But for now I get this error
> Prop "value" expects a two-way binding type. (found in component: <ui-textbox>)

**Comment by JosephusPaye** [comment]
Yeah, the value expects a two way sync:

```html
<ui-textbox name="search" placeholder="Search" :value.sync="searchQuery"></ui-textbox>
```

See the [Vue docs for binding](http://vuejs.org/api/#v-bind).

**Comment by lavezzi1** [comment]
Thanks!
