### ISSUE TITLE
How to show 'valid' only when user interact with input?  

### ISSUE THREAD

**Issue by lavezzi1** [JosephusPaye/Keen-UI#83]
Hi. I want to show valid input (green border). But if I put this in the template of textbox `'valid': valid` – it works, but it shows always.

**Comment by JosephusPaye** [comment]
You can check if the input is dirty (the prop `dirty` will be `true` when the user has interacted with the input). Also a class of `dirty` is added which you can use for styling the border green.

**Comment by lavezzi1** [comment]
Well, if I stylish dirty class it will be overwrite error class if it will be added. Still stuck.

**Comment by lavezzi1** [comment]
I just need to add class valid if it's not invalid. But by default, when page is loaded it shouldn't be added.

**Comment by JosephusPaye** [comment]
Use a combined selector for that, don't just override the whole class. 

Example using Stylus:

```stylus
.ui-textbox.active:not(.disabled):not(.invalid) {
    .ui-textbox-label-text,
    .ui-textbox-icon {
        color: green;
    }

    .ui-textbox-input,
    .ui-textbox-textarea {
        border-bottom-color: green;
    }
}
```

**Comment by lavezzi1** [comment]
Now it green only if I focus on input. Looks like I should try vue-validator instead.

**Comment by JosephusPaye** [comment]
Sure. 

Or you can remove the `.active` from the selector and it should be green even when the input is not active/focused.

**Comment by lavezzi1** [comment]
I want to make it works like here for example if you have an account please check it out https://cloud.digitalocean.com/images/snapshots

1. Page is loaded. Input has a default view (dont touch it yet).
2. User touch the input and go away (ok we got blur). 
3. User start typing and if it's valid, the class 'valid' should be added and make input green. 
4. If it's not valid, class invalid should be added. 

Can I implement it with ccerruent validator.js and your component? Help please.

**Comment by JosephusPaye** [comment]
See [this Codepen demo](http://codepen.io/JosephusPaye/pen/kXodgY).

**Comment by lavezzi1** [comment]
Thank you!

**Comment by lavezzi1** [comment]
Works great, but what if I don't to make green specific input, for example search input? Now every input makes green after it makes dirty.
