### ISSUE TITLE
Calling validate on a component

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#84]
I have created a wizard and for every step it checks for KeenUI that have validation rules. Right now I then set `valid = false` on them, but I want to trigger the validation message too. I tried `this.$children[i].$options.methods.validate()` but that doesn't help me.

Do you have any suggestion to trigger the error message?

**Comment by JosephusPaye** [comment]
This is currently not possible, but will be available in the next release. It has already been implemented here: https://github.com/JosephusPaye/Keen-UI/commit/29b1fd7c5a3df2ac66d69722042914d6482ee7ca

**Comment by JosephusPaye** [comment]
See #61

**Comment by EmilMoe** [comment]
Cool. Looking forward to that release

**Comment by JosephusPaye** [comment]
You can see what's coming and what has already been implemented here: https://github.com/JosephusPaye/Keen-UI/milestone/1
