### ISSUE TITLE
Suggestion: Masked input

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/Keen-UI#87]
Here's a library that helps with it, maybe it can be implemented.

https://nosir.github.io/cleave.js/

**Comment by JosephusPaye** [comment]
Cleave is cool, I was actually playing around with the other day. However I have no plans to add it at this time as I think it's non-essential functionality.

**Comment by EmilMoe** [comment]
For curiosity would you add a UiMaskInput or add it to several current Uis as attribute if you were to add it?

I think I can create an UiMaskedInput that just inherits your UiText with that extra attribute, then it's more an addon to your toolset.

**Comment by JosephusPaye** [comment]
I think a wrapper component as an addon will be the way to go, so the file size doesn't increase for people who don't need the extra functionality.

**Comment by EmilMoe** [comment]
Do you have a suggestion for a best practice to inherit a parent components props? Rewriting all of them and redefining their default values seems odd.

I was working on a few extensions, but not sure how to tackle this the best way.

**Comment by JosephusPaye** [comment]
If there is a mixin available, you could use that; otherwise, I think you have to rewrite all the props.

**Comment by JosephusPaye** [comment]
There are no plans to add this to UiTextbox for now.
