### ISSUE TITLE
Suggestion: Add "clear" type for UiButton

### ISSUE THREAD

**Issue by JonasDoebertin** [JosephusPaye/Keen-UI#89]
How about adding a `clear` option for a **UiButton**s `type`?

The `color` option would have to be extended to accept `black` and `white` too in this case. The button would then display and behave just like a UiIconButton does.

If I find the time, I may create a PR for that, but first I'd like to know what you, @JosephusPaye, think about it?

**Comment by JosephusPaye** [comment]
@JonasDoebertin,

Yeah, go for it. Just make sure it is as close as possible to the API and styling we have for clear UiIconButton.

**Comment by JosephusPaye** [comment]
Closing for now as there is no intent to add this at the moment. In v1.0, the new `type="secondary"` button comes close, but it doesn't support `black` and `white` for color.
