### ISSUE TITLE
UiIconButton open-popover-on

### ISSUE THREAD

**Issue by EmilMoe** [JosephusPaye/keen-ui#9]
Need some sort of way to allow it to open on hover. Could be added to the slot or probably better as open-popover-on for more consistency.

http://josephuspaye.github.io/keen-ui/#/ui-icon-button-docs

**Comment by JosephusPaye** [comment]
I didn't say this in the docs but the `openDropdownOn` prop also applies to popovers as well, not just menus.

**Comment by JosephusPaye** [comment]
Fixed: https://github.com/JosephusPaye/keen-ui/commit/e0fc946816efa5639e418203b399dfb0b1db35eb
