### ISSUE TITLE
Sync UiTextbox valid with store

### ISSUE THREAD

**Issue by IvoPereira** [JosephusPaye/Keen-UI#91]
Hello,

I am using Keen-UI and receiving a store from Veux. I am trying to mark a Textbox invalid if I am receiving a false boolean in the store, however I am having the following error when trying to directly access a state value into :valid.sync:

> vue.common.js?e881:1019 [Vue warn]: Cannot bind two-way prop with non-settable parent path: !loginErrors.length (found in component: <ui-textbox>)warn @ vue.common.js?e881:1019compileProps @ vue.common.js?e881:6063compileAndLinkProps @ vue.common.js?e881:7002Vue._initProps @ vue.common.js?e881:7882Vue._initState @ vue.common.js?e881:7860Vue._init @ vue.common.js?e881:2458Vue._init @ vuex.js?90cb:158Vue._init @ vue-router.js?e71f:1756UiTextbox @ VM98714:2build @ vue.common.js?e881:5837mountComponent @ vue.common.js?e881:5754(anonymous function) @ vue.common.js?e881:5716(anonymous function) @ vue.common.js?e881:5734cb @ vue.common.js?e881:367Vue._resolveComponent @ vue.common.js?e881:8869resolveComponent @ vue.common.js?e881:5736setComponent @ vue.common.js?e881:5715bind @ vue.common.js?e881:5675Directive._bind @ vue.common.js?e881:8325linkAndCapture @ vue.common.js?e881:6928compositeLinkFn @ vue.common.js?e881:6897Vue._compile @ vue.common.js?e881:8611Vue.$mount @ vue.common.js?e881:9446Vue._init @ vue.common.js?e881:2468Vue._init @ vuex.js?90cb:158Vue._init @ vue-router.js?e71f:1756VueComponent @ VM98721:2build @ vue.common.js?e881:5837activate @ vue-router.js?e71f:1176(anonymous function) @ vue-router.js?e71f:1480step @ vue-router.js?e71f:1503(anonymous function) @ vue-router.js?e71f:1506deactivate @ vue-router.js?e71f:1119step @ vue-router.js?e71f:1505runQueue @ vue-router.js?e71f:1500(anonymous function) @ vue-router.js?e71f:1464step @ vue-router.js?e71f:1503(anonymous function) @ vue-router.js?e71f:1506(anonymous function) @ vue-router.js?e71f:1098(anonymous function) @ vue-router.js?e71f:845Vue._resolveComponent @ vue.common.js?e881:8869resolveAsyncComponent @ vue-router.js?e71f:843canActivate @ vue-router.js?e71f:1090step @ vue-router.js?e71f:1505runQueue @ vue-router.js?e71f:1500(anonymous function) @ vue-router.js?e71f:1463step @ vue-router.js?e71f:1503(anonymous function) @ vue-router.js?e71f:1506canDeactivate @ vue-router.js?e71f:1073step @ vue-router.js?e71f:1505runQueue @ vue-router.js?e71f:1500start @ vue-router.js?e71f:1462startTransition @ vue-router.js?e71f:2578step @ vue-router.js?e71f:1503(anonymous function) @ vue-router.js?e71f:1506next @ vue-router.js?e71f:1580(anonymous function) @ main.js?3479:67callHook @ vue-router.js?e71f:1625(anonymous function) @ vue-router.js?e71f:2586step @ vue-router.js?e71f:1505(anonymous function) @ vue-router.js?e71f:1506next @ vue-router.js?e71f:1580(anonymous function) @ main.js?3479:62callHook @ vue-router.js?e71f:1625(anonymous function) @ vue-router.js?e71f:2586step @ vue-router.js?e71f:1505runQueue @ vue-router.js?e71f:1500_match @ vue-router.js?e71f:2584onChange @ vue-router.js?e71f:2168listener @ vue-router.js?e71f:979
> vue.common.js?e881:1019 [Vue warn]: Prop "valid" expects a two-way binding type. (found in component: <ui-textbox>)
> 

This is my current code:

```
<template>
      <ui-textbox class="col-md-12" :value.sync="username" name="username" id="username" type="text" label="Username" validation-rules="required" :valid.sync="!loginErrors.length"></ui-textbox>
      <ui-textbox class="col-md-12" :value.sync="password" name="password" id="password" type="password" label="Password" validation-rules="required" :valid.sync="!loginErrors.length"></ui-textbox>

      <div class="col-md-12">
        <ui-button class="col-md-5" icon="vpn_key" color="success" @click="logIn">Sign in</ui-button>
      </div>
</template>

<script>
import { authenticate } from '../../vuex/actions';

export default {
  data() {
    return {
      username: '',
      password: '',
    };
  },
  vuex: {
    getters: {
      authenticated: (state) => state.user.authenticated,
      loginErrors: (state) => state.user.errors.login,
    },
  },
  methods: {
    logIn() {
      const data = {
        username: this.username,
        password: this.password,
      };

      authenticate(this.$store, data);
    },
  },
};
</script>

```

However, it seems to work if I explicitly pass a boolean value to **:valid.sync**. Of course this way I am not able to change it dynamically depending on state information.

Am I missing something or am I not correctly using the prop?

Thanks

**Comment by JosephusPaye** [comment]
Hi @IvoPereira,

The problem is that the value passed to valid has to be a **variable**, e.g. one can that be set to `true` or `false` from within the component.  

What you are passing, `:valid.sync="!loginErrors.length"` is just the Boolean result of an expression, which is not a variable that can be set, therefore you get the error `Cannot bind two-way prop with non-settable parent path`.

You can use a computed property that has a getter and a setter to bind with a value from Vuex. See here http://vuex.vuejs.org/en/forms.html for more info.

**Comment by IvoPereira** [comment]
Hi @JosephusPaye,

Thanks for answering.

Wow, that seem to did it.

```
  computed: {
    isFormValid: {
      get() {
        return this.loginErrors.length;
      },
    },
```

However I am finding strange but with the behaviour of the component. Isn't it supposed to be marked "invalid" if the condition is false?

It does mark the input as invalid if it is empty (and the rule is required), however from a server-side perspective, I want to be able to notify the user that the data he has filled is wrong.

How can I achieve? Shouldn't I be using valid?

Thanks!

**Comment by IvoPereira** [comment]
Do you have any updates on this @JosephusPaye?

Thanks!

**Comment by JosephusPaye** [comment]
It should be marked as invalid when the expression value changes to `false`.

The way you are setting up the value is not really how it was intended. It is best used as a simple Boolean value that can be set. Example:

```js
data: {
    formIsValid: true
}
```
I think an option you could try in your case is to have it like above and setup a watcher that updates the local value when the store value changes:

```js
watch: {
    'loginErrors': function() {
         this.formIsValid = Boolean(this.loginErrors.length);
    }
}
```

**Comment by IvoPereira** [comment]
Ah, finally got it working!

Thanks a lot for the precious tips! Learning so many stuff new together sometimes just causes confusion :)

Thanks!

**Comment by JosephusPaye** [comment]
Glad to help.
