### ISSUE TITLE
Suggestion: WYSIWYG-Editor

### ISSUE THREAD

**Issue by breadlesscode** [JosephusPaye/Keen-UI#93]
WYSIWYG-Editor would be awsome. I use this at many projects. 

Maybe this as basic: https://github.com/basecamp/trix

**Comment by JosephusPaye** [comment]
Yeah, a text editor component is planned (probably based on Trix) but it's not a priority at the moment.

**Comment by JosephusPaye** [comment]
Closing as there is no intent to add this at the moment.
