### ISSUE TITLE
Preperation for Vue 2

### ISSUE THREAD

**Issue by rowanwins** [JosephusPaye/Keen-UI#95]
Gday @JosephusPaye 

Just wondering if you've got any plans in the pipeline for transitioning to Vue 2? 

And I also wondered if there was a way people could help you contribute to or maintain this library? Obviously ad-hoc pull requests are one avenue but perhaps there are other options? Anyway just a thought....

Cheers
Rowan

**Comment by JosephusPaye** [comment]
Hi @rowanwins,

Yes, there are plans for upgrading to Vue 2. But that will be after a stable 2.0 is released. There will be one more version of Keen UI on Vue 1.x: v0.8.9, which is mostly done and will be published soon.

As for contributing, currently pull requests are the only way. Feel free to suggest any other viable option. I wrote a brief guide on setting up for development here: https://github.com/JosephusPaye/Keen-UI/issues/81#issuecomment-230960994 and you can view contribution guidelines in [CONTRIBUTING.md](CONTRIBUTING.md).

Thanks

**Comment by rowanwins** [comment]
Thanks for the info @JosephusPaye 

One idea for contributions was to perhaps split the docs out into a separate repo. You could potentially then set someone else up as a contributor to help manage that part of the project without exposing out the core code base. 

You could also potentially get someone to help you manage the issues and do some of the front-line support to free up your time (and just trust them not to commit any code :) ).

Anyway it's a a great project, looking forward to helping in the little ways I can!

Cheers,
Rowan
