### ISSUE TITLE
UiCollapsible height with dynamic contents

### ISSUE THREAD

**Issue by citycide** [JosephusPaye/Keen-UI#97]
Aside from the greatness that is Keen UI, I'm having a lot of issues with the collapsibles when I use them with dynamic content. My two current use cases are:

1. a `max-height` container ( 185px ) with a table generated by `v-for` which will scroll vertically inside this container
2. an explicit height ( 675px ) iframe that embeds a dynamic URL

I've changed `UiCollapsible`'s `setHeight` to use `scrollHeight` rather than `offsetHeight` but that only solves use case 1. Use case 2's height still does not get updated correctly, and is only ever 191px. I'm not even sure where that number comes from.

Obviously that's a change to source and likely not one you'll make so is there something else I can do to make this work, and work across the board?

Edit: I should add that I am using the `ui-collapsible::refresh-height` event but it yields no change. 

Edit2: I played around with it more and I did get both cases to work by refreshing the height when necessary, but it's necessary to use `scrollHeight` instead of `offsetHeight` as above. Maybe this would be something worth adding some configuration for?

**Comment by JosephusPaye** [comment]
Is it possible for you to create a Codepen or JSFiddle demo showing the issue? You can use this template which includes Vue and Keen UI: http://codepen.io/pen?template=NrKmPQ

If your changes fixed the issue, then I see no reason why it shouldn't be merged. So send in a pull request if possible and it will be added after I test it.

Thanks

**Comment by citycide** [comment]
@JosephusPaye I opened #101 for this - see the PR for 2 codepens before & after. Again I hope the lack of built files isn't too much of a problem. There was an unrelated problem with stylus that kept me from building and I wanted to keep this one focused on the collapsible ( there's more on that in the PR ).

**Comment by JosephusPaye** [comment]
See my comment on the pull request, it's been merged.

**Comment by citycide** [comment]
Awesome, thanks! Probably coming with v0.8.9 before Vue 2.0?

**Comment by JosephusPaye** [comment]
Yes
