### ISSUE TITLE
Select ui gives 'Error when evaluating expression'

### ISSUE THREAD

**Issue by meshekhar** [JosephusPaye/Keen-UI#99]
I have created a project using vue-cli with browserify. Then installed the keen-ui as per the instructions and also registered the components globally. Following is the simple component i created to test the select-ui.
```
<template>
  <section class="section section-hello-world">    
      <ui-select name="color" label="Favourite color" 
        validation-rules="required"  :options="colorStrings" placeholder="Select a color"></ui-select>
      <ui-button color="danger">Danger</ui-button>
  </section>
</template>

<script>
let colorStrings = [
    'Red', 'Blue', 'Green', 'Yellow', 'Purple', 'Pink', 'Lavender', 'Orange', 'Peach', 'Lime'
];
export default {
  data () {
    return {
      colorStrings     
    }
  }
}
</script>
```
**I get following error two times:**
-----------------------------
vue.common.js:1019[Vue warn]: Error when evaluating expression "function filteredOptions() {
	            if (this.disableFiltering) {
	                return this.options;
	            }
	            return this.options.filter(this.search);
	        }": 
TypeError: Cannot read property 'toLowerCase' of undefined (found in component: <ui-select>)
-----------------------------

Also When I add **disable-filtering** prop, errors disappear but drop-down does not populate with items as sown in following screen grab.

![screen shot 2016-07-27 at 10 56 59 am](https://cloud.githubusercontent.com/assets/7340685/17182398/f820613e-53e8-11e6-8848-987f08c12185.png)

**Comment by JosephusPaye** [comment]
The problem is with the way you are defining the `colorStrings` array, it should be an array of objects not strings. 

See this [Codepen demo](http://codepen.io/JosephusPaye/pen/yJEqPq?editors=1000).

An array of strings will be supported in the **next** version.

**Comment by meshekhar** [comment]
It makes sense. Thanks for answering my question. BTW I took the select example from src-docs component [UiSelectDocs](https://github.com/JosephusPaye/Keen-UI/blob/master/src-docs/components/UiSelectDocs.vue). 

I will close it now.

**Comment by JosephusPaye** [comment]
The code you linked to is in the `master` branch which is in development for the next version. The docs shown on the site  are in the `gh-pages` branch. 

See: https://github.com/JosephusPaye/Keen-UI/blob/gh-pages/src-docs/components/UiSelectDocs.vue
